//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/**/*.rs` for functions annotated with `#[tool(...)]` and emits
//! a `pub const TOOL_NAMES: &[&str]` with their names. The generated set is
//! pinned against the live router by `tool_surface_pin!` in the server's
//! test module, so a tool added/renamed/unrouted fails the pin instead of
//! degrading to "tool not found" at dispatch. The scan itself lives in the
//! shared support module — one implementation for every server.
//!
//! Swarm-specific: also emits `CLOUD_SWARM_TOOL_NAMES` — the subset
//! declared in the file carrying `#[tool_router(router = cloud_swarm_router)]`.
//! The swarm panel's Steer prompt splits the surface into ABW tools (the
//! cloud router) and local-substrate tools (the complement); deriving the
//! partition here keeps it structural, not hand-maintained. Pinned against
//! the live `cloud_swarm_router()` surface by
//! `cloud_swarm_tool_names_match_live_cloud_router`.

#[path = "../../crates/hkask-mcp-server/build_support/tool_names.rs"]
mod tool_names;

use std::collections::BTreeSet;
use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    let router_pattern =
        regex::Regex::new(r"#\[tool_router\(router\s*=\s*(\w+)").expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    let mut cloud_names: BTreeSet<String> = BTreeSet::new();
    for source in tool_names::rust_sources(&src_dir, true) {
        tool_names::scan_tool_fns(&source, &mut names);
        let router = router_pattern
            .captures(&source)
            .map(|caps| caps[1].to_string());
        if router.as_deref() == Some("cloud_swarm_router") {
            tool_names::scan_tool_fns(&source, &mut cloud_names);
        }
    }

    let entries = tool_names::entries(&names);
    let cloud_entries = tool_names::entries(&cloud_names);
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/**/*.rs` for `#[tool]`-annotated `pub async fn` signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n\
         // The cloud (ABW) router's tools — the swarm panel's ABW/local split.\n\
         pub const CLOUD_SWARM_TOOL_NAMES: &[&str] = &[\n{cloud_entries}];\n"
    );

    tool_names::write_if_changed(&out_path, &generated, &src_dir);
}
