//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/*.rs` for `pub(crate) async fn swarm_<name>` and emits a
//! `pub const TOOL_NAMES: &[&str]` with the discovered fn names. This is the
//! canonical tool-name list — the `tool_surface_is_exactly_52_registered_tools`
//! test in `hkask_mcp_swarm.rs` asserts it matches the live
//! `combined_router().list_all()` surface, so drift is caught at test time.
//!
//! All swarm tools use the fn name as the tool name (no `#[tool(name = "...")]`
//! overrides). If a `name =` override is added in the future, the test will
//! catch the mismatch (the generated const has the fn name, the router has the
//! override) — the fix is to add the override name to the const manually or
//! extend this script to parse `#[tool]` attributes.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    // Regex: `pub(crate) async fn swarm_<name>(`
    // All 52 tool fns follow this exact pattern (verified: no `name =` overrides,
    // all start with `swarm_`). The `#[tool]` attribute may span multiple lines,
    // but the fn signature is always on one line.
    let pattern =
        regex::Regex::new(r"pub\(crate\) async fn (swarm_\w+)\s*\(").expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    for entry in fs::read_dir(&src_dir).expect("src directory exists") {
        let entry = entry.expect("readable dir entry");
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        for caps in pattern.captures_iter(&source) {
            names.insert(caps[1].to_string());
        }
    }

    // Emit the generated const. Sorted for deterministic output.
    let mut entries = String::new();
    for name in &names {
        entries.push_str(&format!("    \"{name}\",\n"));
    }
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/*.rs` for `pub(crate) async fn swarm_*` signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n"
    );

    // Only write if changed (avoids recompilation when the list is stable).
    let existing = fs::read_to_string(&out_path).unwrap_or_default();
    if existing != generated {
        fs::write(&out_path, generated).expect("writable OUT_DIR");
    }

    // Re-run when any source file changes.
    println!("cargo:rerun-if-changed={}", src_dir.display());
}
