//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/*.rs` for `pub(crate) async fn swarm_<name>` and emits a
//! `pub const TOOL_NAMES: &[&str]` with the discovered fn names. This is the
//! canonical tool-name list — the tool surface is asserted against the live
//! `combined_router().list_all()` surface at test time, so drift is caught.
//!
//! Also emits `CLOUD_SWARM_TOOL_NAMES` — the subset declared in the file
//! carrying `#[tool_router(router = cloud_swarm_router)]`. The swarm panel's
//! Steer prompt splits the surface into ABW tools (the cloud router) and
//! local-substrate tools (the complement); generating the partition here
//! keeps it derived from the server's own structure instead of a
//! hand-maintained name list. Pinned against the live `cloud_swarm_router()`
//! surface by `cloud_swarm_tool_names_match_live_cloud_router`.
//!
//! All swarm tools use the fn name as the tool name (no `#[tool(name = "...")]`
//! overrides). If a `name =` override is added in the future, the test will
//! catch the mismatch (the generated const has the fn name, the router has the
//! override) — the fix is to add the override name to the const manually or
//! extend this script to parse `#[tool]` attributes.

#[path = "../../crates/hkask-mcp-server/build_support/tool_names.rs"]
mod tool_names;

use std::collections::BTreeSet;
use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    // Regex: `pub(crate) async fn swarm_<name>(`
    // All tool fns follow this exact pattern (verified: no `name =` overrides,
    // all start with `swarm_`). The `#[tool]` attribute may span multiple lines,
    // but the fn signature is always on one line.
    let pattern =
        regex::Regex::new(r"pub\(crate\) async fn (swarm_\w+)\s*\(").expect("valid regex");
    // The router a file's tools belong to: `#[tool_router(router = <name>`.
    // One router per tool file (cloud_swarm_tools.rs, local_tools.rs,
    // a2a_tools.rs, knowledge_tools.rs).
    let router_pattern =
        regex::Regex::new(r"#\[tool_router\(router\s*=\s*(\w+)").expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    let mut cloud_names: BTreeSet<String> = BTreeSet::new();
    for source in tool_names::rust_sources(&src_dir, false) {
        let router = router_pattern
            .captures(&source)
            .map(|caps| caps[1].to_string());
        for caps in pattern.captures_iter(&source) {
            names.insert(caps[1].to_string());
            if router.as_deref() == Some("cloud_swarm_router") {
                cloud_names.insert(caps[1].to_string());
            }
        }
    }

    // Emit the generated consts. Sorted for deterministic output.
    let entries = tool_names::entries(&names);
    let cloud_entries = tool_names::entries(&cloud_names);
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/*.rs` for `pub(crate) async fn swarm_*` signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n\
         // The cloud (ABW) router's tools — the swarm panel's ABW/local split.\n\
         pub const CLOUD_SWARM_TOOL_NAMES: &[&str] = &[\n{cloud_entries}];\n"
    );

    // Only write if changed (avoids recompilation when the list is stable).
    tool_names::write_if_changed(&out_path, &generated, &src_dir);
}
