//! Build script — embed the kask SKILL.md files at compile time.
//!
//! Scans `../../.agents/skills/*/SKILL.md` (the kask skill catalog shipped
//! in this repo) and emits a static `EMBEDDED_GLOBAL_SKILL_ENTRIES: &[(&str, &str)]`
//! array of `(name, content)` pairs, sorted by name for deterministic
//! override resolution.
//!
//! The SKILL.md files are the *interface* — zed's discovery machinery
//! parses their frontmatter (name + description) to surface them in the
//! slash-command catalog and the model's `<available_skills>` list. The
//! *implementation* (the YAML manifest in `kask/registry/manifests/`) is
//! embedded separately by `hkask-templates/build.rs` and consulted at
//! runtime via `process_manifest_yaml()`.
//!
//! Embedding the SKILL.md files here means the kask skills are available
//! as `SkillSource::Global` in every project, regardless of where the
//! user installed zed-kask or what their CWD is — same approach
//! `hkask-templates/build.rs` already uses for manifests.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Maximum allowed description length in bytes. Mirrors
/// `agent_skills::MAX_SKILL_DESCRIPTION_LEN`. Duplicated here because build
/// scripts can't depend on the crate they build. If this value changes,
/// update `MAX_SKILL_DESCRIPTION_LEN` in `agent_skills.rs` too.
const MAX_SKILL_DESCRIPTION_LEN: usize = 1024;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // crates/agent_skills → repo root
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Could not locate repo root from agent_skills manifest dir");

    let skills_dir = repo_root.join(".agents/skills");
    let mut entries = Vec::new();
    if skills_dir.is_dir() {
        for entry in fs::read_dir(&skills_dir).expect("read .agents/skills") {
            let entry = entry.expect("dir entry");
            let skill_md = entry.path().join("SKILL.md");
            if skill_md.is_file() {
                let name = entry
                    .file_name()
                    .to_str()
                    .expect("UTF-8 skill directory name")
                    .to_string();
                entries.push((name, skill_md));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Validate every embedded skill's description at build time. A shipped
    // SKILL.md with an over-long description is a build-time bug — it would
    // be silently dropped from the catalog at runtime by
    // `parse_embedded_global_skill` (which calls `validate_description`).
    // Failing the build here turns a silent runtime WARN into a loud
    // compile error, catching the regression before it ships.
    let mut failures = Vec::new();
    for (name, path) in &entries {
        let content = match fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) => {
                failures.push(format!("{name}: failed to read SKILL.md: {e}"));
                continue;
            }
        };
        if let Err(msg) = validate_embedded_skill_frontmatter(name, &content) {
            failures.push(format!("{name}: {msg}"));
        }
    }
    if !failures.is_empty() {
        panic!(
            "Embedded global skill validation failed ({} failure(s)):\n  - {}
  \
             Fix by trimming the description in the SKILL.md frontmatter to be \
             at most {MAX_SKILL_DESCRIPTION_LEN} bytes, or update \
             MAX_SKILL_DESCRIPTION_LEN in both build.rs and agent_skills.rs.",
            failures.len(),
            failures.join("\n  - "),
        );
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — embedded kask SKILL.md files.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static EMBEDDED_GLOBAL_SKILL_ENTRIES: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        let abs = path.to_str().expect("UTF-8 SKILL.md path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("embedded_global_skills.rs"), code)
        .expect("write generated embedded_global_skills.rs");

    // Rebuild when the skill set changes or any SKILL.md is touched.
    println!("cargo:rerun-if-changed={}", skills_dir.display());
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

/// Validate a shipped SKILL.md's frontmatter at build time. Mirrors the
/// runtime checks in `parse_embedded_global_skill` so a build break here
/// corresponds exactly to a runtime drop there. Only checks the fields
/// that `parse_embedded_global_skill` hard-rejects on: name and description.
fn validate_embedded_skill_frontmatter(name: &str, content: &str) -> Result<(), String> {
    let content = content.trim_start();
    if !content.starts_with("---") {
        return Err("SKILL.md must start with YAML frontmatter (---)".into());
    }
    // Extract the frontmatter block (between the first and second `---` lines).
    let after_opener = &content[3..];
    let newline_idx = after_opener
        .find('\n')
        .ok_or_else(|| "SKILL.md frontmatter has no closing ---".to_string())?;
    let rest = &after_opener[newline_idx + 1..];
    let closer_idx = rest
        .find("\n---")
        .ok_or_else(|| "SKILL.md frontmatter has no closing ---".to_string())?;
    let frontmatter = &rest[..closer_idx];

    // Parse the `name:` field and confirm it matches the directory name.
    // (Mirrors `validate_name`.)
    let parsed_name = extract_yaml_scalar(frontmatter, "name")
        .ok_or_else(|| "SKILL.md frontmatter missing `name:` field".to_string())?;
    if parsed_name != name {
        return Err(format!(
            "SKILL.md `name: {parsed_name}` does not match directory name `{name}`"
        ));
    }
    if parsed_name.is_empty() {
        return Err("Skill name cannot be empty".into());
    }
    if parsed_name.len() > 64 {
        return Err(format!(
            "Skill name must be at most 64 characters (got {})",
            parsed_name.len()
        ));
    }
    if parsed_name.starts_with('-') || parsed_name.ends_with('-') {
        return Err("Skill name must not start or end with a hyphen".into());
    }
    if !parsed_name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
    {
        return Err("Skill name must contain only lowercase letters, numbers, and hyphens".into());
    }

    // Parse the `description:` field and check its byte length.
    // (Mirrors `validate_description`.)
    let description = extract_yaml_description(frontmatter)?;
    if description.trim().is_empty() {
        return Err("Skill description cannot be empty".into());
    }
    let desc_len = description.len();
    if desc_len > MAX_SKILL_DESCRIPTION_LEN {
        return Err(format!(
            "Skill description is {desc_len} bytes, must be at most \
             {MAX_SKILL_DESCRIPTION_LEN} bytes"
        ));
    }

    Ok(())
}

/// Extract a simple YAML scalar value (`key: value`) from frontmatter.
/// Handles quoted strings (`key: "value"`) by stripping the quotes and
/// unescaping `\"` and `\\`. Does not handle block scalars — use
/// `extract_yaml_description` for those.
fn extract_yaml_scalar(frontmatter: &str, key: &str) -> Option<String> {
    for line in frontmatter.lines() {
        let line = line.trim_start();
        let prefix = format!("{key}:");
        if line.starts_with(&prefix) {
            let value = line[prefix.len()..].trim();
            if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
                return Some(
                    value[1..value.len() - 1]
                        .replace("\\\"", "\"")
                        .replace("\\\\", "\\"),
                );
            }
            return Some(value.to_string());
        }
    }
    None
}

/// Extract the `description:` field from frontmatter, handling both scalar
/// (`description: "..."`) and block-scalar (`description: >\n  ...`) forms.
/// For block scalars, joins the indented continuation lines with spaces
/// (matching YAML `>` folding semantics) and returns the logical value.
fn extract_yaml_description(frontmatter: &str) -> Result<String, String> {
    let lines: Vec<&str> = frontmatter.lines().collect();
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("description:") {
            continue;
        }
        let value = trimmed["description:".len()..].trim();
        // Scalar form: `description: "..."` or `description: ...`
        if !value.is_empty() && value != ">" && value != "|" {
            if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
                return Ok(value[1..value.len() - 1]
                    .replace("\\\"", "\"")
                    .replace("\\\\", "\\"));
            }
            return Ok(value.to_string());
        }
        // Block scalar form: `description: >` followed by indented lines.
        let mut folded = String::new();
        for cont in &lines[i + 1..] {
            if !cont.starts_with("  ") {
                break;
            }
            let unindented = &cont[2..];
            if !folded.is_empty() {
                folded.push(' ');
            }
            folded.push_str(unindented);
        }
        return Ok(folded.trim().to_string());
    }
    Err("SKILL.md frontmatter missing `description:` field".into())
}
