//! Build script — bundle the kask SKILL.md files as a one-time seed payload.
//!
//! Scans `../../.agents/skills/*/SKILL.md` (the kask skill catalog authored
//! in this repo) and emits a static `SHIPPED_SKILL_SEED_ENTRIES: &[(&str, &str)]`
//! array of `(name, content)` pairs, sorted by name.
//!
//! This payload is **seed-only**: at startup `agent_skills::seed_shipped_skills`
//! writes each SKILL.md to the user's on-disk global skills directory
//! (`paths::data_dir()/agents/skills/<name>/SKILL.md`) when missing. The disk
//! copy is the single runtime source of truth — zed's discovery machinery
//! loads skills from disk via `load_skills_from_directory`, never from this
//! compiled payload. User edits to the on-disk files take effect immediately
//! without recompilation; that is the architectural contract this crate
//! honours. The compiled payload exists solely so a self-contained binary can
//! materialise the shipped skills on a fresh install with no source tree.
//!
//! The SKILL.md files are the *interface* (frontmatter parsed for discovery);
//! the *implementation* (YAML manifests + Jinja2 templates) is seeded to disk
//! separately by the skill seeding path.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Maximum allowed description length in bytes. Mirrors
/// `agent_skills::MAX_SKILL_DESCRIPTION_LEN`. Duplicated here because build
/// scripts can't depend on the crate they build. If this value changes,
/// update `MAX_SKILL_DESCRIPTION_LEN` in `agent_skills.rs` too.
const MAX_SKILL_DESCRIPTION_LEN: usize = 1024;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // crates/agent_skills → repo root
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Could not locate repo root from agent_skills manifest dir");

    let skills_dir = repo_root.join(".agents/skills");
    let mut entries = Vec::new();
    if skills_dir.is_dir() {
        for entry in fs::read_dir(&skills_dir).expect("read .agents/skills") {
            let entry = entry.expect("dir entry");
            let skill_md = entry.path().join("SKILL.md");
            if skill_md.is_file() {
                let name = entry
                    .file_name()
                    .to_str()
                    .expect("UTF-8 skill directory name")
                    .to_string();
                entries.push((name, skill_md));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Validate every embedded skill's description at build time. A shipped
    // SKILL.md with an over-long description is a build-time bug — it would
    // be silently dropped from the catalog at runtime by
    // `parse_embedded_global_skill` (which calls `validate_description`).
    // Failing the build here turns a silent runtime WARN into a loud
    // compile error, catching the regression before it ships.
    let mut failures = Vec::new();
    for (name, path) in &entries {
        let content = match fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) => {
                failures.push(format!("{name}: failed to read SKILL.md: {e}"));
                continue;
            }
        };
        if let Err(msg) = validate_embedded_skill_frontmatter(name, &content) {
            failures.push(format!("{name}: {msg}"));
        }
    }
    if !failures.is_empty() {
        panic!(
            "Shipped skill seed validation failed ({} failure(s)):\n  - {}
  \
             Fix by trimming the description in the SKILL.md frontmatter to be \
             at most {MAX_SKILL_DESCRIPTION_LEN} bytes, or update \
             MAX_SKILL_DESCRIPTION_LEN in both build.rs and agent_skills.rs.",
            failures.len(),
            failures.join("\n  - "),
        );
    }

    let mut code = String::new();
    code.push_str(
        "// Auto-generated by build.rs — seed payload for shipped kask SKILL.md files.\n",
    );
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static SHIPPED_SKILL_SEED_ENTRIES: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        let abs = path.to_str().expect("UTF-8 SKILL.md path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("embedded_global_skills.rs"), code)
        .expect("write generated embedded_global_skills.rs");

    // Rebuild when the skill set changes or any SKILL.md is touched.
    println!("cargo:rerun-if-changed={}", skills_dir.display());
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

/// Validate a shipped SKILL.md's frontmatter at build time. Mirrors the
/// runtime checks in `parse_skill_file_content_for_loading` so a build break
/// here corresponds exactly to a runtime load failure there. Only checks the
/// fields that discovery hard-rejects on: name and description.
fn validate_embedded_skill_frontmatter(name: &str, content: &str) -> Result<(), String> {
    let content = content.trim_start();
    if !content.starts_with("---") {
        return Err("SKILL.md must start with YAML frontmatter (---)".into());
    }
    // Extract the frontmatter block (between the first and second `---` lines).
    let after_opener = &content[3..];
    let newline_idx = after_opener
        .find('\n')
        .ok_or_else(|| "SKILL.md frontmatter has no closing ---".to_string())?;
    let rest = &after_opener[newline_idx + 1..];
    let closer_idx = rest
        .find("\n---")
        .ok_or_else(|| "SKILL.md frontmatter has no closing ---".to_string())?;
    let frontmatter = &rest[..closer_idx];

    // Parse the `name:` field and confirm it matches the directory name.
    // (Mirrors `validate_name`.)
    let parsed_name = extract_yaml_scalar(frontmatter, "name")
        .ok_or_else(|| "SKILL.md frontmatter missing `name:` field".to_string())?;
    if parsed_name != name {
        return Err(format!(
            "SKILL.md `name: {parsed_name}` does not match directory name `{name}`"
        ));
    }
    if parsed_name.is_empty() {
        return Err("Skill name cannot be empty".into());
    }
    if parsed_name.len() > 64 {
        return Err(format!(
            "Skill name must be at most 64 characters (got {})",
            parsed_name.len()
        ));
    }
    if parsed_name.starts_with('-') || parsed_name.ends_with('-') {
        return Err("Skill name must not start or end with a hyphen".into());
    }
    if !parsed_name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
    {
        return Err("Skill name must contain only lowercase letters, numbers, and hyphens".into());
    }

    // Parse the `description:` field and check its byte length.
    // (Mirrors `validate_description`.)
    let description = extract_yaml_description(frontmatter)?;
    if description.trim().is_empty() {
        return Err("Skill description cannot be empty".into());
    }
    let desc_len = description.len();
    if desc_len > MAX_SKILL_DESCRIPTION_LEN {
        return Err(format!(
            "Skill description is {desc_len} bytes, must be at most \
             {MAX_SKILL_DESCRIPTION_LEN} bytes"
        ));
    }

    // Validate the `core` field if present. Must be a bare `true` or `false`
    // (unquoted). `serde_yaml_ng` (used at runtime by
    // `parse_skill_file_content_for_loading`) rejects quoted booleans like
    // `core: "true"` with `invalid type: string, expected a boolean`, so
    // the build-time check must reject them too — otherwise a build passes
    // with a `core:` value that silently drops the skill from the catalog at
    // runtime.
    if let Some(raw_core) = extract_raw_yaml_scalar(frontmatter, "core") {
        let trimmed = raw_core.trim();
        if trimmed.starts_with('"') || trimmed.starts_with('\'') {
            return Err(format!(
                "SKILL.md `core:` field must be an unquoted boolean \
                 (true or false), got quoted value `{trimmed}`"
            ));
        }
        if trimmed != "true" && trimmed != "false" {
            return Err(format!(
                "SKILL.md `core:` field must be `true` or `false` (got `{trimmed}`)"
            ));
        }
    }

    Ok(())
}

/// Extract a simple YAML scalar value (`key: value`) from frontmatter.
/// Handles quoted strings (`key: "value"`) by stripping the quotes and
/// unescaping `\"` and `\\`. Does not handle block scalars — use
/// `extract_yaml_description` for those.
fn extract_yaml_scalar(frontmatter: &str, key: &str) -> Option<String> {
    extract_raw_yaml_scalar(frontmatter, key).map(|raw| {
        let value = raw.trim();
        if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
            value[1..value.len() - 1]
                .replace("\\\"", "\"")
                .replace("\\\\", "\\")
        } else {
            value.to_string()
        }
    })
}

/// Extract the raw (unstripped, quote-preserving) value of a simple YAML
/// scalar (`key: value`) from frontmatter. Used by validators that need to
/// distinguish quoted from unquoted values (e.g. `core:` must be a bare
/// boolean, not a quoted string).
fn extract_raw_yaml_scalar(frontmatter: &str, key: &str) -> Option<String> {
    for line in frontmatter.lines() {
        let line = line.trim_start();
        let prefix = format!("{key}:");
        if line.starts_with(&prefix) {
            return Some(line[prefix.len()..].trim().to_string());
        }
    }
    None
}

/// Extract the `description:` field from frontmatter, handling both scalar
/// (`description: "..."`) and block-scalar (`description: >\n  ...`) forms.
/// For block scalars, joins the indented continuation lines with spaces
/// (matching YAML `>` folding semantics) and returns the logical value.
fn extract_yaml_description(frontmatter: &str) -> Result<String, String> {
    let lines: Vec<&str> = frontmatter.lines().collect();
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("description:") {
            continue;
        }
        let value = trimmed["description:".len()..].trim();
        // Scalar form: `description: "..."` or `description: ...`
        if !value.is_empty() && value != ">" && value != "|" {
            if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
                return Ok(value[1..value.len() - 1]
                    .replace("\\\"", "\"")
                    .replace("\\\\", "\\"));
            }
            return Ok(value.to_string());
        }
        // Block scalar form: `description: >` followed by indented lines.
        let mut folded = String::new();
        for cont in &lines[i + 1..] {
            if !cont.starts_with("  ") {
                break;
            }
            let unindented = &cont[2..];
            if !folded.is_empty() {
                folded.push(' ');
            }
            folded.push_str(unindented);
        }
        return Ok(folded.trim().to_string());
    }
    Err("SKILL.md frontmatter missing `description:` field".into())
}
