//! Build script — embed the kask SKILL.md files at compile time.
//!
//! Scans `../../.agents/skills/*/SKILL.md` (the kask skill catalog shipped
//! in this repo) and emits a static `EMBEDDED_GLOBAL_SKILL_ENTRIES: &[(&str, &str)]`
//! array of `(name, content)` pairs, sorted by name for deterministic
//! override resolution.
//!
//! The SKILL.md files are the *interface* — zed's discovery machinery
//! parses their frontmatter (name + description) to surface them in the
//! slash-command catalog and the model's `<available_skills>` list. The
//! *implementation* (the YAML manifest in `kask/registry/manifests/`) is
//! embedded separately by `hkask-templates/build.rs` and consulted at
//! runtime via `process_manifest_yaml()`.
//!
//! Embedding the SKILL.md files here means the kask skills are available
//! as `SkillSource::Global` in every project, regardless of where the
//! user installed zed-kask or what their CWD is — same approach
//! `hkask-templates/build.rs` already uses for manifests.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // crates/agent_skills → repo root
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Could not locate repo root from agent_skills manifest dir");

    let skills_dir = repo_root.join(".agents/skills");
    let mut entries = Vec::new();
    if skills_dir.is_dir() {
        for entry in fs::read_dir(&skills_dir).expect("read .agents/skills") {
            let entry = entry.expect("dir entry");
            let skill_md = entry.path().join("SKILL.md");
            if skill_md.is_file() {
                let name = entry
                    .file_name()
                    .to_str()
                    .expect("UTF-8 skill directory name")
                    .to_string();
                entries.push((name, skill_md));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — embedded kask SKILL.md files.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static EMBEDDED_GLOBAL_SKILL_ENTRIES: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        let abs = path.to_str().expect("UTF-8 SKILL.md path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("embedded_global_skills.rs"), code)
        .expect("write generated embedded_global_skills.rs");

    // Rebuild when the skill set changes or any SKILL.md is touched.
    println!("cargo:rerun-if-changed={}", skills_dir.display());
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}
