//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/*.rs` for `pub async fn kanban_<name>` / `pub async fn
//! contract_<name>` and emits a `pub const TOOL_NAMES: &[&str]` with the
//! discovered fn names. This is the canonical tool-name list — the
//! `tool_names_match_live_router` test in `hkask_mcp_kata_kanban.rs` asserts
//! it matches the live `tool_router().list_all()` surface, so drift is caught
//! at test time. Mirrors `hkask-mcp-swarm/build.rs`.
//!
//! All kanban tools use the fn name as the tool name (no `#[tool(name =
//! "...")]` overrides). If a `name =` override is added in the future, the
//! test will catch the mismatch.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    // All tool fns follow `pub async fn kanban_*(`; the one exception is
    // `contract_propose_expect`, which uses the `contract_` prefix.
    let pattern = regex::Regex::new(r"pub async fn ((?:kanban|contract)_\w+)\s*\(")
        .expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    for entry in fs::read_dir(&src_dir).expect("src directory exists") {
        let entry = entry.expect("readable dir entry");
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        for caps in pattern.captures_iter(&source) {
            names.insert(caps[1].to_string());
        }
    }

    // Emit the generated const. Sorted for deterministic output.
    let mut entries = String::new();
    for name in &names {
        entries.push_str(&format!("    \"{name}\",\n"));
    }
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/*.rs` for `pub async fn kanban_*`/`contract_*` signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n"
    );

    // Only write if changed (avoids recompilation when the list is stable).
    let existing = fs::read_to_string(&out_path).unwrap_or_default();
    if existing != generated {
        fs::write(&out_path, generated).expect("writable OUT_DIR");
    }

    // Re-run when any source file changes.
    println!("cargo:rerun-if-changed={}", src_dir.display());
}
