//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/**/*.rs` for functions annotated with `#[tool(...)]` and emits
//! a `pub const TOOL_NAMES: &[&str]` with their names. The generated set is
//! pinned against the live router by `tool_surface_pin!` in the server's
//! test module, so a tool added/renamed/unrouted fails the pin instead of
//! degrading to "tool not found" at dispatch. The scan itself lives in the
//! shared support module — one implementation for every server, not
//! per-server copies (the former per-server scans drifted: fixed windows
//! missed long doc blocks, local patterns captured non-tool fns).

#[path = "../../crates/hkask-mcp-server/build_support/tool_names.rs"]
mod tool_names;

use std::collections::BTreeSet;
use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    let mut names: BTreeSet<String> = BTreeSet::new();
    for source in tool_names::rust_sources(&src_dir, true) {
        tool_names::scan_tool_fns(&source, &mut names);
    }

    let entries = tool_names::entries(&names);
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/**/*.rs` for `#[tool]`-annotated `pub async fn` signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n"
    );

    tool_names::write_if_changed(&out_path, &generated, &src_dir);
}
