#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! hkask-mcp-kata-kanban — Kata-Kanban workflow coordination MCP server.
//!
//! Provides 25 MCP tools for kanban board, task, and goal management.
//! All tools carry the caller's WebID for P12 compliance.
//!
//! The KanbanServer struct and tool methods are exported from the library
//! target to enable fuzz testing (P5 Testing Discipline, P4 Clear Boundaries).

pub mod idempotency;
pub mod kanban;
pub(crate) mod pko;
pub mod types;

// Re-export the kata-kanban service API at crate root (folded from hkask-services-kata-kanban).
// `KanbanService` is `pub` so external tool-behavior contract tests (tests/) can construct
// a service over an in-memory driver and drive the real `Parameters<T>` tool seam — the
// testing standard (docs/reference/mcp-servers/README.md §Testing standard) requires this.
pub use kanban::KanbanService;
pub(crate) use kanban::{
    ColumnDef, CriterionCitation, CriterionJudgment, GoalVerdict, GoalVerdictValue, KanbanError,
    Priority, SpawnSpec, Task, TaskFilter, TaskSpec, TaskStatus, VerificationCriterion,
};

// Bridge crates: shared ontological vocabulary (P5.4 dual-axis framework)

use hkask_mcp_server::server::{McpToolError, ServerContext, execute_tool, resolve_db_passphrase};
use hkask_mcp_swarm::{LocalAgentCapabilities, LocalAgentCard, LocalAgentRegistry};
use hkask_storage::HMemStore;
use pko::kanban_type_to_pko;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::{tool, tool_router};
use std::sync::Arc;
use types::*;

// ── Canonical tool-name list ─────────────────────────────────────────────
//
// Generated by `build.rs` from `pub async fn kanban_*`/`contract_*`
// signatures in `src/*.rs`. The single source of truth — the
// `tool_names_match_live_router` test below asserts it matches the live
// `tool_router().list_all()` surface, so drift is caught at test time.
// Consumers across the seam (`kanban_panel`, `swarm_panel`) use this const
// to verify their Steer-mode prompt tool advertisements.
include!(concat!(env!("OUT_DIR"), "/tool_names.gen.rs"));

// ── Server ──────────────────────────────────────────────────────────────────

hkask_mcp_server::mcp_server!(
    pub struct KanbanServer {
        pub service: KanbanService,
        /// Local agent registry — reusable expert agents (cards on disk). When a
        /// spawn's `delegated_skills` are covered by an existing card, it is
        /// reused; otherwise a task-specific agent is built in-memory.
        pub local_registry: Arc<LocalAgentRegistry>,
        /// Worktree spawn port — when available, `kanban_task_spawn` creates a
        /// worktree-backed agent thread (isolated git worktree) via the zed IPC
        /// bridge. Missing authority or an uncertain reply never starts a fallback.
        pub worktree_spawn_port: Arc<dyn hkask_types::WorktreeSpawnPort>,
        /// Replay protection for identity-minting mutations, including board,
        /// task, spawn, and aggregate-import creation.
        /// Shares the kanban database, so protection has the same durability as
        /// the writes it guards. See `crate::idempotency`.
        pub idempotency: Arc<idempotency::IdempotencyStore>,
        /// Replay protection for `kanban_goal_create` — the same durable
        /// store as task creates. Goals persist through resolution until
        /// curator-memory acknowledgment (operator ruling 2026-09-16), so a
        /// replayed create returns a live goal's id, not a ghost pointer whose
        /// next `kanban_goal_judge` fails NotFound.
        pub goal_idempotency: Arc<idempotency::IdempotencyStore>,
    }
);

/// Run `work` under replay protection when the caller supplied a key.
///
/// Without a key this is a plain pass-through, so protected tools keep working
/// for callers that do not opt in.
///
/// With a key, the three outcomes map to what the client can safely do:
/// - first call → run the work, record the response for later replays;
/// - replay of a completed call → return the original response verbatim, marked
///   `replayed: true`, without re-running;
/// - replay of a call that never completed → refuse, because whether the work
///   landed is exactly what is unknown. Re-running could duplicate it and
///   claiming success could invent a result.
///
/// A known pre-effect failure releases the claim. Spawn Unavailable errors
/// retain it because the IPC request may already have created a child.
///
/// CONTRACT ON `work`: except for uncertain spawn Unavailable errors, return
/// `Err` only when NO effect landed.
/// Post-effect failures (bookkeeping after the spawn, etc.) must be folded
/// into a successful partial response instead — see `kanban_task_spawn`'s
/// `result_note_error`. Releasing the claim on a post-effect error would let
/// a same-key retry duplicate the effect, which is exactly what this
/// protection exists to prevent.
async fn with_idempotency<F>(
    store: &idempotency::IdempotencyStore,
    tool: &'static str,
    key: Option<&str>,
    caller: &hkask_types::WebID,
    request: serde_json::Value,
    work: F,
) -> Result<serde_json::Value, McpToolError>
where
    F: std::future::Future<Output = Result<serde_json::Value, McpToolError>>,
{
    let Some(key) = key else {
        return work.await;
    };
    idempotency::IdempotencyStore::validate_key(key)
        .map_err(|error| McpToolError::invalid_argument(error.to_string()))?;

    // Fail closed: if the claim cannot be recorded, the caller asked for replay
    // protection and must not be handed a call that silently lacks it.
    let digest = idempotency::request_sha256(&request).map_err(|error| {
        McpToolError::internal(format!("cannot fingerprint replay request: {error}"))
    })?;
    let reservation = store
        .reserve(tool, key, &caller.to_string(), &digest)
        .map_err(|error| {
            McpToolError::unavailable(format!(
                "replay-protection store unavailable, refusing to run {tool} unprotected: {error}"
            ))
        })?;

    match reservation {
        idempotency::Reservation::Replay { response } => {
            // Return the first call's result. `replayed` lets a caller
            // distinguish "your retry was absorbed" from "this ran now".
            // `response` was written by this same function's Fresh arm via
            // `serde_json::to_string`, so a parse failure means our own store is
            // corrupt — not a caller error and not a per-variant domain error.
            let mut value: serde_json::Value = serde_json::from_str(&response).map_err(|e| {
                McpToolError::internal(format!("stored idempotent response is not JSON: {e}")) // rr0044-ok: deserialize-own-struct
            })?;
            if let Some(object) = value.as_object_mut() {
                object.insert("replayed".to_string(), serde_json::Value::Bool(true));
            }
            Ok(value)
        }
        idempotency::Reservation::OtherCaller => Err(McpToolError::permission_denied(
            "idempotency_key belongs to another caller",
        )),
        idempotency::Reservation::DifferentRequest => Err(McpToolError::invalid_argument(
            "idempotency_key was already used for a different request",
        )),
        idempotency::Reservation::UnknownIdentity => Err(McpToolError::unavailable(
            "idempotency_key has unknown prior identity; outcome unknown, do not reuse this key",
        )),
        idempotency::Reservation::Pending => Err(McpToolError::unavailable(format!(
            "a previous {tool} call with this idempotency_key did not complete — its \
             outcome is unknown. Re-read the board to see whether it took effect; do not \
             reuse this key."
        ))),
        idempotency::Reservation::Fresh => match work.await {
            Ok(mut value) => {
                // Tell the caller when the guarantee is only process-local, so a
                // restart-crossing retry is not wrongly believed to be protected.
                if !store.is_durable()
                    && let Some(object) = value.as_object_mut()
                {
                    object.insert(
                        "idempotency_durable".to_string(),
                        serde_json::Value::Bool(false),
                    );
                }
                match serde_json::to_string(&value) {
                    Ok(response) => store.record(tool, key, &response),
                    Err(error) => {
                        // The work succeeded; retain the Pending claim so a
                        // retry is refused rather than duplicating the effect.
                        tracing::warn!(
                            target: "hkask.mcp.kata_kanban",
                            tool = %tool,
                            %error,
                            "could not serialize response for replay protection - \
                             retaining pending claim"
                        );
                    }
                }
                Ok(value)
            }
            Err(error) => {
                // Spawn transport errors do not prove non-delivery. Retain the
                // pending claim so a same-key retry cannot create a second child.
                if tool != "kanban_task_spawn"
                    || error.kind != hkask_types::McpErrorKind::Unavailable
                {
                    store.release(tool, key);
                }
                Err(error)
            }
        },
    }
}

/// Build a task-specific local agent card for `kanban_task_spawn` when no
/// reusable expert agent covers the requested skills. The card is not persisted;
/// its declared MCP tools narrow the parent's worktree grant. An empty tool set
/// grants no tools to the child; skill instructions do not expand that authority.
fn build_task_agent_card(
    task_id: hkask_types::TaskId,
    title: &str,
    skills: &[String],
) -> LocalAgentCard {
    LocalAgentCard {
        agent_id: format!("kanban-task-{task_id}"),
        agent_type: "task".to_string(),
        description: title.to_string(),
        display_name: title.to_string(),
        accepts: vec!["task".to_string()],
        produces: vec!["task_result".to_string()],
        dependencies: Default::default(),
        capabilities: LocalAgentCapabilities {
            system_prompt: Some(
                "You are a task-execution agent spawned by the kata-kanban. \
                 Complete the assigned task using your declared skills. \
                 \
                 ## Output format \
                 \
                 Produce your response as a JSON object with these fields: \
                 - \"deliverable_path\": the path of any file you wrote or edited (string, or null if none). \
                 - \"test_verdict\": the result of running tests (string like \"pass: N ran, M failed\", or null if you did not run tests). \
                 - \"summary\": a concise summary of what you did (string). \
                 - \"approach\": a brief description of your approach (string). \
                 \
                 Only claim a deliverable_path if you actually called a file-writing tool \
                 (edit_file, write_file, terminal) that succeeded. Only claim a test_verdict \
                 if you actually ran tests via the terminal tool and it succeeded. \
                 Do not fabricate file paths or test results."
                    .to_string(),
            ),
            skills: skills.to_vec(),
            ..Default::default()
        },
        cloud_swarm_id: None,
        ..Default::default()
    }
}

/// Derive a one-line `TaskActivity` from a task's most recent comment (R3).
/// The spawn/delegation flow already appends durable comments ("Spawn
/// executed: agent=…, tokens=…", "Spawned worktree agent for task …"), so
/// this surfaces the latest one as the card's status strip without a new
/// ingest channel. The live per-tool-call hook path is a follow-up that
/// swaps this data source without touching the widget.
fn derive_task_activity(task: &Task) -> Option<TaskActivity> {
    let comment = task.comments.last()?;
    Some(TaskActivity {
        text: comment.body.clone(),
        kind: "comment".to_string(),
        at: comment.created_at.to_rfc3339(),
        ontology: kanban_type_to_pko("Task").map(|s| s.to_string()),
    })
}

#[tool_router(server_handler)]
impl KanbanServer {
    #[tool(description = "Create a new kanban board with optional custom columns")]
    pub async fn kanban_board_create(
        &self,
        Parameters(BoardCreateRequest {
            name,
            columns,
            idempotency_key,
        }): Parameters<BoardCreateRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(
            self,
            "kanban_board_create",
            with_idempotency(
                &self.idempotency,
                "kanban_board_create",
                idempotency_key.as_deref(),
                &self.webid,
                serde_json::json!({ "name": name, "columns": columns }),
                async {
                    let column_defs = match columns {
                        Some(inputs) => inputs
                            .into_iter()
                            .enumerate()
                            .map(
                                |(i, input)| match crate::TaskStatus::parse_str(&input.status) {
                                    Some(s) => {
                                        let mut col =
                                            crate::ColumnDef::new(input.name, s, i as u32);
                                        if let Some(wip) = input.wip_limit {
                                            col = col.with_wip_limit(wip);
                                        }
                                        Ok(col)
                                    }
                                    None => Err(format!("invalid status: {}", input.status)),
                                },
                            )
                            .collect::<Result<Vec<_>, _>>(),
                        None => Ok(crate::KanbanService::standard_columns()),
                    };
                    let cols = match column_defs {
                        Ok(c) => c,
                        Err(e) => return Err(McpToolError::invalid_argument(e)),
                    };
                    match self.service.board_create(self.webid, &name, &cols) {
                        Ok(board) => Ok(serde_json::to_value(BoardCreateResponse {
                            board_id: board.id.to_string(),
                            name: board.name,
                            columns: board
                                .columns
                                .iter()
                                .map(|c| ColumnInfo {
                                    id: c.id.to_string(),
                                    name: c.name.clone(),
                                    status: c.status.to_string(),
                                    wip_limit: c.wip_limit,
                                })
                                .collect(),
                            ontology: kanban_type_to_pko("Board").map(|s| s.to_string()),
                        })
                        .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                        Err(e) => Err(map_kanban_error(e)),
                    }
                },
            ),
        )
        .await
    }

    #[tool(description = "List all kanban boards owned by the caller")]
    pub async fn kanban_board_list(
        &self,
        Parameters(BoardListRequest {}): Parameters<BoardListRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_board_list", async {
            match self.service.board_list(&self.webid) {
                Ok(boards) => Ok(serde_json::to_value(BoardListResponse {
                    boards: boards
                        .into_iter()
                        .map(|b| BoardInfo {
                            board_id: b.id.to_string(),
                            name: b.name,
                            column_count: b.columns.len(),
                            columns: b
                                .columns
                                .iter()
                                .map(|c| ColumnInfo {
                                    id: c.id.to_string(),
                                    name: c.name.clone(),
                                    status: c.status.to_string(),
                                    wip_limit: c.wip_limit,
                                })
                                .collect(),
                            ontology: kanban_type_to_pko("Board").map(|s| s.to_string()),
                        })
                        .collect(),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    /// Delete a kanban board and all its tasks. Exposes the existing
    /// `KanbanService::board_delete` method as an MCP tool — closes the gap
    /// where `board_delete` was service-only and unreachable via MCP.
    ///
    /// contract: P3-svc-kanban-011
    /// expect: "I can delete a kanban board I own via MCP" \[P3\]
    /// pre:  board_id is a valid board id owned by the caller
    /// post: the board and all its tasks are deleted; returns the task count
    #[tool(
        description = "Delete a kanban board and all its tasks. Exposes KanbanService::board_delete as an MCP tool."
    )]
    pub async fn kanban_board_delete(
        &self,
        Parameters(BoardDeleteRequest { board_id }): Parameters<BoardDeleteRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_board_delete", async {
            let bid = parse_board_id(&board_id)?;
            // Verify ownership before delete — only the board owner can
            // delete it (P12).
            let board = self
                .service
                .board_get(bid)
                .map_err(map_kanban_error)?
                .ok_or_else(|| McpToolError::not_found(format!("board {bid} not found")))?;
            if board.owner != self.webid {
                return Err(McpToolError::invalid_argument(format!(
                    "board {bid} is not owned by caller — cannot delete"
                )));
            }
            let tasks_deleted = self.service.board_delete(bid).map_err(map_kanban_error)?;
            serde_json::to_value(BoardDeleteResponse {
                board_id: bid.to_string(),
                tasks_deleted,
                ontology: kanban_type_to_pko("kanban_board_delete").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    /// Rename a kanban board. The board name is the addressing key for the
    /// operator and for agents (reference model R6 — every reference
    /// implementation treats rename as first-class), so a mistyped name is
    /// corrected without deleting and recreating the board (which would
    /// orphan the task links). Convergent by construction: replaying the
    /// same rename re-applies the same name, so it carries no idempotency
    /// key (the `task_update` class).
    ///
    /// contract: P3-svc-kanban-014
    /// expect: "I can rename a kanban board I own" \[P3\]
    /// pre:  board_id is a valid board id owned by the caller; name is
    ///       non-empty after trimming
    /// post: the board's name is updated in place; returns the new name
    #[tool(
        description = "Rename a kanban board (owner only). The name is the board's addressing key; trimmed and must be non-empty."
    )]
    pub async fn kanban_board_update(
        &self,
        Parameters(BoardUpdateRequest { board_id, name }): Parameters<BoardUpdateRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_board_update", async {
            let bid = parse_board_id(&board_id)?;
            // Verify ownership before rename — only the board owner can
            // rename it (P12), mirroring `kanban_board_delete` and
            // `kanban_board_export`.
            let board = self
                .service
                .board_get(bid)
                .map_err(map_kanban_error)?
                .ok_or_else(|| McpToolError::not_found(format!("board {bid} not found")))?;
            if board.owner != self.webid {
                return Err(McpToolError::permission_denied(format!(
                    "board {bid} is not owned by caller — cannot rename"
                )));
            }
            let board = self
                .service
                .board_rename(bid, &name)
                .map_err(map_kanban_error)?;
            serde_json::to_value(BoardUpdateResponse {
                board_id: bid.to_string(),
                name: board.name,
                ontology: kanban_type_to_pko("Board").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    /// Create a functional goal — the kata target condition for a bit of
    /// work. The goal is the user's functional requirement in the user's
    /// words, with 1–4 observable criteria and an optional intake
    /// prediction (Brier-scored at `kanban_goal_score`). Native persistence
    /// for the four-moves interaction loop
    /// (`kask/docs/architecture/functional-interaction-spec.md`).
    #[tool(
        description = "Create a functional goal (kata target condition) with observable criteria and an optional intake prediction. Goals persist through resolution until curator-memory ingestion acknowledges the scored outcome, so failed ingestion remains retryable across restarts."
    )]
    pub async fn kanban_goal_create(
        &self,
        Parameters(GoalCreateRequest {
            goal_text,
            criteria,
            prediction,
            task_id,
            idempotency_key,
        }): Parameters<GoalCreateRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(
            self,
            "kanban_goal_create",
            with_idempotency(
                &self.goal_idempotency,
                "kanban_goal_create",
                idempotency_key.as_deref(),
                &self.webid,
                serde_json::json!({ "goal_text": goal_text, "criteria": criteria, "prediction": prediction, "task_id": task_id }),
                async {
                    let tid = match task_id {
                        Some(t) => Some(parse_task_id(&t)?),
                        None => None,
                    };
                    let criteria = criteria
                        .into_iter()
                        .map(|c| VerificationCriterion::new(c.description))
                        .collect();
                    match self
                        .service
                        .goal_create(goal_text, criteria, prediction, tid, self.webid)
                    {
                        Ok(goal) => Ok(serde_json::to_value(GoalCreateResponse {
                            goal_id: goal.id.to_string(),
                            goal_text: goal.goal_text,
                            criteria_count: goal.criteria.len(),
                            prediction: goal.prediction,
                            ontology: kanban_type_to_pko("Goal").map(|s| s.to_string()),
                        })
                        .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                        Err(e) => Err(map_kanban_error(e)),
                    }
                },
            ),
        )
        .await
    }

    /// Record a judge verdict against a goal's criteria. Verdict semantics:
    /// `done` (all criteria
    /// satisfied), `continue` (work continues), `blocked` (unachievable or
    /// needs user input). Verdicts append to a history — the history IS the
    /// learning.
    #[tool(
        description = "Record a judge verdict (done/continue/blocked) with confidence and a result for every criterion of the goal."
    )]
    pub async fn kanban_goal_judge(
        &self,
        Parameters(GoalJudgeRequest {
            goal_id,
            verdict,
            confidence,
            criterion_results,
            reasoning,
        }): Parameters<GoalJudgeRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_goal_judge", async {
            let gid = parse_goal_id(&goal_id)?;
            let verdict_value = parse_goal_verdict(&verdict)?;
            let goal_verdict = GoalVerdict {
                verdict: verdict_value,
                confidence,
                criterion_results: criterion_results
                    .into_iter()
                    .map(|c| CriterionJudgment {
                        index: c.index,
                        passed: c.passed,
                        note: c.note,
                    })
                    .collect(),
                reasoning,
                judged_at: chrono::Utc::now(),
            };
            match self.service.goal_judge(gid, goal_verdict, self.webid) {
                Ok(goal) => Ok(serde_json::to_value(GoalJudgeResponse {
                    goal_id: goal.id.to_string(),
                    verdict: verdict,
                    verdict_count: goal.verdicts.len(),
                    ontology: kanban_type_to_pko("kanban_goal_judge").map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    /// Resolve a goal: record the realized outcome (the user's ground
    /// truth) and Brier-score the intake prediction. `brier` is `null`
    /// with a note when no prediction was recorded — surfaced, never faked.
    #[tool(
        description = "Resolve a goal: record achieved/not-achieved and Brier-score the intake prediction."
    )]
    pub async fn kanban_goal_score(
        &self,
        Parameters(GoalScoreRequest { goal_id, achieved }): Parameters<GoalScoreRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_goal_score", async {
            let gid = parse_goal_id(&goal_id)?;
            match self.service.goal_score(gid, achieved, self.webid) {
                Ok(goal) => {
                    let resolution = goal
                        .resolution
                        .as_ref()
                        .expect("goal_score records a resolution");
                    let note = if resolution.brier.is_none() {
                        Some(
                            "no intake prediction was recorded — Brier not computable \
                                 (this is not a score of 0)"
                                .to_string(),
                        )
                    } else {
                        None
                    };
                    Ok(serde_json::to_value(GoalScoreResponse {
                        goal_id: goal.id.to_string(),
                        achieved,
                        brier: resolution.brier,
                        note,
                        ontology: kanban_type_to_pko("kanban_goal_score").map(|s| s.to_string()),
                    })
                    .map_err(|e| McpToolError::internal(e.to_string()))?) // rr0044-ok: serialize-own-struct
                }
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    /// Internal completion of the goal-memory handoff. The production agent
    /// calls this only after the scored outcome is stored in curator memory.
    #[tool(
        description = "Acknowledge that a resolved goal outcome was stored in curator memory, then remove the retained goal. Internal lifecycle operation; call only with a confirmed memory-ingestion receipt."
    )]
    pub async fn kanban_goal_memory_acknowledge(
        &self,
        Parameters(GoalMemoryAcknowledgeRequest { goal_id }): Parameters<
            GoalMemoryAcknowledgeRequest,
        >,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_goal_memory_acknowledge", async {
            let gid = parse_goal_id(&goal_id)?;
            self.service
                .goal_acknowledge_memory(gid, self.webid)
                .map_err(map_kanban_error)?;
            serde_json::to_value(GoalMemoryAcknowledgeResponse {
                goal_id,
                acknowledged: true,
            })
            .map_err(|e| McpToolError::internal(e.to_string()))
        })
        .await
    }

    /// List the caller's goals, newest first — the cross-session recall
    /// for Move 4 (bank the learning): the next bit of work starts from
    /// these.
    #[tool(
        description = "List the caller's functional goals, including resolved goals retained until curator-memory ingestion is acknowledged, newest first."
    )]
    pub async fn kanban_goal_list(
        &self,
        Parameters(GoalListRequest {}): Parameters<GoalListRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_goal_list", async {
            match self.service.goal_list(&self.webid) {
                Ok(goals) => Ok(serde_json::to_value(GoalListResponse {
                    goals: goals
                        .into_iter()
                        .map(|g| GoalInfo {
                            goal_id: g.id.to_string(),
                            goal_text: g.goal_text,
                            criteria_count: g.criteria.len(),
                            prediction: g.prediction,
                            latest_verdict: g.verdicts.last().map(|v| v.verdict.to_string()),
                            resolution: g.resolution.as_ref().map(|r| {
                                if r.achieved {
                                    "achieved".to_string()
                                } else {
                                    "not-achieved".to_string()
                                }
                            }),
                            created_at: g.created_at.to_rfc3339(),
                        })
                        .collect(),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(description = "Create a new task on a kanban board")]
    pub async fn kanban_task_create(
        &self,
        Parameters(TaskCreateRequest {
            board_id,
            title,
            description,
            criteria,
            advances,
            idempotency_key,
        }): Parameters<TaskCreateRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(
            self,
            "kanban_task_create",
            with_idempotency(
                &self.idempotency,
                "kanban_task_create",
                idempotency_key.as_deref(),
                &self.webid,
                serde_json::json!({ "board_id": board_id, "title": title, "description": description, "criteria": criteria, "advances": advances }),
                async {
                    let bid = parse_board_id(&board_id)?;
                    let mut spec = TaskSpec::new(title);
                    if let Some(d) = description {
                        spec = spec.with_description(d);
                    }
                    if let Some(cs) = criteria {
                        spec = spec.with_criteria(
                            cs.into_iter().map(VerificationCriterion::new).collect(),
                        );
                    }
                    let mut citations = Vec::with_capacity(advances.len());
                    for citation in advances {
                        let goal_id = parse_goal_id(&citation.goal_id)?;
                        citations.push(CriterionCitation {
                            goal_id,
                            criterion_index: citation.criterion_index,
                            criterion_text: citation.criterion_text,
                        });
                    }
                    spec.advances = citations;

                    match self.service.task_create(bid, spec, self.webid) {
                        Ok(task) => Ok(serde_json::to_value(TaskCreateResponse {
                            task_id: task.id.to_string(),
                            board_id: task.board_id.to_string(),
                            title: task.title,
                            status: task.status.to_string(),
                            advances_count: task.advances.len(),
                            ontology: kanban_type_to_pko("Task").map(|s| s.to_string()),
                        })
                        .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                        Err(e) => Err(map_kanban_error(e)),
                    }
                },
            ),
        )
        .await
    }

    #[tool(
        description = "Update editable fields on a task (title, description, criteria, priority, labels, goal-criterion citations). Only the task owner can edit."
    )]
    pub async fn kanban_task_update(
        &self,
        Parameters(TaskUpdateRequest {
            task_id,
            title,
            description,
            criteria,
            priority,
            labels,
            advances,
        }): Parameters<TaskUpdateRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_update", async {
            let tid = parse_task_id(&task_id)?;

            // The MCP layer uses single-Option for description and priority:
            // None means "no change," a present value means "set to this."
            // An empty string for description clears the field; an empty
            // string for priority clears the field.
            let description_update = description.map(|d| if d.is_empty() { None } else { Some(d) });
            let priority_update = match priority {
                None => None,
                Some(ref p) if p.is_empty() => Some(None),
                Some(p) => {
                    let parsed = Priority::parse_str(&p).ok_or_else(|| {
                        McpToolError::invalid_argument(format!("invalid priority: {p}"))
                    })?;
                    Some(Some(parsed))
                }
            };

            let criteria_update =
                criteria.map(|cs| cs.into_iter().map(VerificationCriterion::new).collect());

            let advances_update = advances
                .map(|citations| {
                    citations
                        .into_iter()
                        .map(|citation| {
                            Ok::<_, McpToolError>(CriterionCitation {
                                goal_id: parse_goal_id(&citation.goal_id)?,
                                criterion_index: citation.criterion_index,
                                criterion_text: citation.criterion_text,
                            })
                        })
                        .collect::<Result<Vec<_>, _>>()
                })
                .transpose()?;

            match self.service.task_update(
                tid,
                self.webid,
                title,
                description_update,
                criteria_update,
                priority_update,
                labels,
                advances_update,
            ) {
                Ok(task) => Ok(serde_json::to_value(TaskUpdateResponse {
                    task_id: task.id.to_string(),
                    title: task.title,
                    advances_count: task.advances.len(),
                    ontology: kanban_type_to_pko("Task").map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(description = "List tasks on a kanban board, optionally filtered by status")]
    pub async fn kanban_task_list(
        &self,
        Parameters(TaskListRequest { board_id, status }): Parameters<TaskListRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_list", async {
            let bid = parse_board_id(&board_id)?;
            let filter = match status {
                Some(s) => match crate::TaskStatus::parse_str(&s) {
                    Some(st) => TaskFilter::by_status(st),
                    None => {
                        return Err(McpToolError::invalid_argument(format!(
                            "invalid status: {s}"
                        )));
                    }
                },
                None => TaskFilter::all(),
            };
            match self.service.task_list(bid, filter) {
                Ok(tasks) => Ok(serde_json::to_value(TaskListResponse {
                    tasks: tasks
                        .into_iter()
                        .map(|t| {
                            let activity = derive_task_activity(&t);
                            TaskInfo {
                                task_id: t.id.to_string(),
                                board_id: t.board_id.to_string(),
                                title: t.title,
                                description: t.description,
                                status: t.status.to_string(),
                                assignee: t.assignee.map(|a| a.to_string()),
                                criteria_count: t.criteria.len(),
                                advances_count: t.advances.len(),
                                swarm_id: t.swarm_id,
                                activity,
                                ontology: kanban_type_to_pko("Task").map(|s| s.to_string()),
                            }
                        })
                        .collect(),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(
        description = "Move a task to a new column (status transition). The response carries pko_execution_status — the new status mapped to its PKO execution status (queued/inProgress/verifying/completed) via the shared vocabulary bridge."
    )]
    pub async fn kanban_task_move(
        &self,
        Parameters(TaskMoveRequest {
            task_id,
            target_status,
        }): Parameters<TaskMoveRequest>,
    ) -> Result<String, McpToolError> {
        use pko::kanban_type_to_pko;

        execute_tool(self, "kanban_task_move", async {
            let tid = parse_task_id(&task_id)?;
            let previous_status = match self.service.task_get(tid) {
                Ok(Some(t)) => t.status.to_string(),
                Ok(None) => {
                    return Err(McpToolError::not_found(format!(
                        "task not found: {task_id}"
                    )));
                }
                Err(e) => return Err(map_kanban_error(e)),
            };
            let target = match crate::TaskStatus::parse_str(&target_status) {
                Some(s) => s,
                None => {
                    return Err(McpToolError::invalid_argument(format!(
                        "invalid target_status: {target_status}"
                    )));
                }
            };
            match self.service.task_move(tid, target, self.webid) {
                Ok(task) => Ok(serde_json::to_value(TaskMoveResponse {
                    task_id: task.id.to_string(),
                    previous_status,
                    new_status: task.status.to_string(),
                    ontology: kanban_type_to_pko("kanban_task_move").map(|s| s.to_string()),
                    // Execution axis: the new status as a PKO execution
                    // status (the shared vocabulary mapper — not a local
                    // re-implementation, so it cannot drift from the
                    // bridge contract).
                    pko_execution_status:
                        hkask_bridge_ontology::pko::kanban_status_to_pko_execution(
                            &task.status.to_string(),
                        )
                        .map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(description = "Claim an unassigned task as the authenticated caller")]
    pub async fn kanban_task_assign(
        &self,
        Parameters(TaskAssignRequest { task_id }): Parameters<TaskAssignRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_assign", async {
            let tid = parse_task_id(&task_id)?;
            match self.service.task_claim(tid, self.webid) {
                Ok(task) => Ok(serde_json::to_value(TaskAssignResponse {
                    task_id: task.id.to_string(),
                    assignee: task.assignee.map(|a| a.to_string()).unwrap_or_default(),
                    ontology: kanban_type_to_pko("kanban_task_assign").map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(
        description = "Delete a task and its board index entry. Exposes KanbanService::task_delete as an MCP tool."
    )]
    pub async fn kanban_task_delete(
        &self,
        Parameters(TaskDeleteRequest { task_id }): Parameters<TaskDeleteRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_delete", async {
            let tid = parse_task_id(&task_id)?;
            self.service.task_delete(tid).map_err(map_kanban_error)?;
            serde_json::to_value(TaskDeleteResponse {
                task_id: tid.to_string(),
                ontology: kanban_type_to_pko("Task").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    #[tool(
        description = "Unassign a task — remove the current assignee. Only the task owner can unassign."
    )]
    pub async fn kanban_task_unassign(
        &self,
        Parameters(TaskUnassignRequest { task_id }): Parameters<TaskUnassignRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_unassign", async {
            let tid = parse_task_id(&task_id)?;
            match self.service.task_unassign(tid, self.webid) {
                Ok(task) => Ok(serde_json::to_value(TaskUnassignResponse {
                    task_id: task.id.to_string(),
                    ontology: kanban_type_to_pko("Task").map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(
        description = "Record verification evidence for a task in Review. The evidence text is the pass signal; acceptance criteria are guidance, not a gate."
    )]
    pub async fn kanban_task_verify(
        &self,
        Parameters(TaskVerifyRequest { task_id, evidence }): Parameters<TaskVerifyRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_verify", async {
            let tid = parse_task_id(&task_id)?;
            if evidence.trim().is_empty() {
                return Err(McpToolError::invalid_argument("evidence must not be empty"));
            }
            match self.service.task_verify(tid, &evidence, self.webid) {
                Ok((task, verification)) => Ok(serde_json::to_value(TaskVerifyResponse {
                    task_id: task.id.to_string(),
                    passed: verification.passed,
                    reasoning: verification.reasoning,
                    new_status: task.status.to_string(),
                    ontology: kanban_type_to_pko("kanban_task_verify").map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(
        description = "Add a comment to a task (feedback thread for subagent↔agent communication)"
    )]
    pub async fn kanban_task_comment(
        &self,
        Parameters(TaskCommentRequest { task_id, body }): Parameters<TaskCommentRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_comment", async {
            let tid = parse_task_id(&task_id)?;
            if body.trim().is_empty() {
                return Err(McpToolError::invalid_argument(
                    "comment body must not be empty",
                ));
            }
            match self.service.task_comment(tid, self.webid, &body) {
                Ok(comment) => Ok(serde_json::to_value(TaskCommentResponse {
                    comment_id: comment.id.to_string(),
                    task_id: comment.task_id.to_string(),
                    author: comment.author.to_string(),
                    body: comment.body,
                    created_at: comment.created_at.to_rfc3339(),
                    ontology: kanban_type_to_pko("Comment").map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(
        description = "Fetch task comments starting from an index (for incremental memory ingestion)"
    )]
    pub async fn kanban_task_comments_since(
        &self,
        Parameters(TaskCommentsSinceRequest {
            task_id,
            since_index,
        }): Parameters<TaskCommentsSinceRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_comments_since", async {
            let tid = parse_task_id(&task_id)?;
            match self.service.task_comments_since(tid, since_index) {
                Ok(comments) => {
                    let total = comments.len() + since_index;
                    let mapped: Vec<TaskCommentResponse> = comments
                        .into_iter()
                        .map(|c| TaskCommentResponse {
                            comment_id: c.id.to_string(),
                            task_id: c.task_id.to_string(),
                            author: c.author.to_string(),
                            body: c.body,
                            created_at: c.created_at.to_rfc3339(),
                            ontology: kanban_type_to_pko("Comment").map(|s| s.to_string()),
                        })
                        .collect();
                    Ok(serde_json::to_value(TaskCommentsSinceResponse {
                        task_id: tid.to_string(),
                        comments: mapped,
                        total_count: total,
                    })
                    .map_err(|e| McpToolError::internal(e.to_string()))?) // rr0044-ok: serialize-own-struct
                }
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(description = "Attach a deliverable (file path or URL) to a task as work output")]
    pub async fn kanban_task_add_deliverable(
        &self,
        Parameters(TaskAddDeliverableRequest { task_id, path }): Parameters<
            TaskAddDeliverableRequest,
        >,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_add_deliverable", async {
            let tid = parse_task_id(&task_id)?;
            if path.trim().is_empty() {
                return Err(McpToolError::invalid_argument("path must not be empty"));
            }
            match self.service.task_add_deliverable(tid, &path, self.webid) {
                Ok(task) => Ok(serde_json::to_value(TaskAddDeliverableResponse {
                    task_id: task.id.to_string(),
                    deliverable_count: task.deliverables.len(),
                    ontology: kanban_type_to_pko("kanban_task_add_deliverable")
                        .map(|s| s.to_string()),
                })
                .map_err(|e| McpToolError::internal(e.to_string()))?), // rr0044-ok: serialize-own-struct
                Err(e) => Err(map_kanban_error(e)),
            }
        })
        .await
    }

    #[tool(description = "Reopen a completed task (Done → InProgress)")]
    pub async fn kanban_task_reopen(
        &self,
        Parameters(TaskReopenRequest { task_id }): Parameters<TaskReopenRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_reopen", async {
            let tid = parse_task_id(&task_id)?;
            self.service
                .task_reopen(tid, self.webid)
                .map_err(map_kanban_error)?;
            // Re-read to get final state
            let task = self
                .service
                .task_get(tid)
                .map_err(map_kanban_error)?
                .ok_or_else(|| McpToolError::not_found(format!("task {task_id}")))?;
            serde_json::to_value(TaskReopenResponse {
                task_id: task.id.to_string(),
                new_status: task.status.to_string(),
                ontology: kanban_type_to_pko("kanban_task_reopen").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    // ── Kata tools — scientific-thinking prompts scoped to a task ──────────

    #[tool(
        description = "Generate a kata prompt scoped to a task. stage selects the kata: 'coaching' (5-question Coaching Kata dialogue), 'improvement' (Improvement Kata PDCA cycle), or 'practice' (Starter Kata observation drill — requires sub_problem). The former kanban_task_kata_coaching/improvement/practice trio, merged."
    )]
    pub async fn kanban_task_kata_prompt(
        &self,
        Parameters(TaskKataPromptRequest {
            task_id,
            stage,
            sub_problem,
        }): Parameters<TaskKataPromptRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_kata_prompt", async {
            let tid = parse_task_id(&task_id)?;
            let prompt = match stage.as_str() {
                "coaching" => self
                    .service
                    .task_coaching_prompt(tid)
                    .map_err(map_kanban_error)?,
                "improvement" => self
                    .service
                    .task_improvement_prompt(tid)
                    .map_err(map_kanban_error)?,
                "practice" => {
                    let Some(sub_problem) = sub_problem else {
                        return Err(McpToolError::invalid_argument(
                            "sub_problem is required for stage 'practice'",
                        ));
                    };
                    self.service
                        .task_practice_prompt(tid, &sub_problem)
                        .map_err(map_kanban_error)?
                }
                other => {
                    return Err(McpToolError::invalid_argument(format!(
                        "stage must be 'coaching', 'improvement', or 'practice', got '{other}'"
                    )));
                }
            };
            serde_json::to_value(TaskKataResponse {
                task_id: tid.to_string(),
                prompt,
                ontology: kanban_type_to_pko("kanban_task_kata_prompt").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    // ── Spawn — activate a subagent pod for task execution ─────────────────

    /// Spawn a subagent for task execution. Tries worktree-isolated spawn
    /// via the parent-authorized `WorktreeSpawnPort`. Children auto-run with the
    /// parent grant intersected with the selected agent card's declared MCP tools.
    /// A missing grant or uncertain outcome is surfaced without fallback execution.
    #[tool(description = "Spawn a subagent for task execution with delegated skills")]
    pub async fn kanban_task_spawn(
        &self,
        Parameters(TaskSpawnRequest {
            task_id,
            idempotency_key,
            delegation_level,
            delegated_skills,
            memory_scope,
            swarm_id,
        }): Parameters<TaskSpawnRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(
            self,
            "kanban_task_spawn",
            with_idempotency(
                &self.idempotency,
                "kanban_task_spawn",
                idempotency_key.as_deref(),
                &self.webid,
                serde_json::json!({ "task_id": task_id, "delegation_level": delegation_level, "delegated_skills": delegated_skills, "memory_scope": memory_scope, "swarm_id": swarm_id }),
                async {
                    let tid = self.validate_and_prepare_spawn(
                        &task_id,
                        &delegation_level,
                        &memory_scope,
                    )?;
                    let skills_for_agent = delegated_skills.clone();
                    let spec = crate::SpawnSpec::new(tid)
                        .with_level(&delegation_level)
                        .with_skills(delegated_skills)
                        .with_swarm(swarm_id.clone());
                    let spec = if let Some(ref ms) = memory_scope {
                        spec.with_memory(ms)
                    } else {
                        spec
                    };
                    // Record the spawn configuration on the task (config comment).
                    self.service
                        .spawn_task(tid, spec, self.webid)
                        .map_err(map_kanban_error)?;

                    let task = self
                        .service
                        .task_get(tid)
                        .map_err(map_kanban_error)?
                        .ok_or_else(|| McpToolError::not_found(format!("task {tid} not found")))?;

                    // Resolve the agent: reuse an expert agent whose declared skills
                    // cover the requested set; otherwise build a task-specific agent
                    // card in-memory ("create agents w/ skills for tasks").
                    let agent = self
                        .local_registry
                        .list()
                        .into_iter()
                        .find(|card| {
                            !skills_for_agent.is_empty()
                                && skills_for_agent
                                    .iter()
                                    .all(|s| card.capabilities.skills.iter().any(|cs| cs == s))
                        })
                        .unwrap_or_else(|| {
                            build_task_agent_card(tid, &task.title, &skills_for_agent)
                        });

                    // Fail closed: a refusal or lost reply never authorizes another executor.
                    let response = self
                        .spawn_via_worktree(
                            tid,
                            &task,
                            &skills_for_agent,
                            &agent.capabilities.mcp_tools,
                        )
                        .await?;
                    serde_json::to_value(response)
                        .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
                },
            ),
        )
        .await
    }

    fn validate_and_prepare_spawn(
        &self,
        task_id: &str,
        delegation_level: &str,
        memory_scope: &Option<String>,
    ) -> Result<hkask_types::TaskId, McpToolError> {
        let tid = parse_task_id(task_id)?;
        match delegation_level {
            "minimal" | "standard" | "maximal" => {}
            other => {
                return Err(McpToolError::invalid_argument(format!(
                    "invalid delegation_level: {other} (expected minimal|standard|maximal)"
                )));
            }
        }
        if let Some(ms) = memory_scope {
            match ms.as_str() {
                "none" | "episodic" | "full" => {}
                other => {
                    return Err(McpToolError::invalid_argument(format!(
                        "invalid memory_scope: {other} (expected none|episodic|full)"
                    )));
                }
            }
        }
        Ok(tid)
    }

    async fn spawn_via_worktree(
        &self,
        tid: hkask_types::TaskId,
        task: &Task,
        skills_for_agent: &[String],
        allowed_tools: &[String],
    ) -> Result<TaskSpawnResponse, McpToolError> {
        let task_text = match task.description.as_deref() {
            Some(desc) if !desc.trim().is_empty() => format!("{}: {}", task.title, desc),
            _ => task.title.clone(),
        };
        let spawn_prompt = format!(
            "You are working on kanban task '{}' (id: {}).\n\
             Task description: {}\n\
             Delegated skills: {}\n\
             Execute the task and report results via kanban_task_delegate_result.",
            task.title,
            tid,
            task_text,
            skills_for_agent.join(", ")
        );
        let spawn_title = format!("Kanban: {}", task.title);
        match self
            .worktree_spawn_port
            .create_worktree_thread(&spawn_prompt, &spawn_title, None, None, allowed_tools)
            .await
        {
            Ok(message) => {
                let result_note = format!(
                    "Worktree thread queued for task '{}' ({}). \
                     Native session establishment and auto-submit are asynchronous; execution is not yet confirmed.\n{}",
                    task.title, tid, message
                );
                // Post-spawn bookkeeping: the agent thread already exists, so
                // a comment failure must NOT fail the call — an Err here would
                // release the replay-protection claim and a same-key retry
                // would spawn a SECOND agent. Fold the failure into the
                // response instead. Session startup remains asynchronous, so
                // queuing alone does not advance the task to InProgress.
                let result_note_error =
                    match self.service.task_comment(tid, self.webid, &result_note) {
                        Ok(_) => None,
                        Err(error) => {
                            tracing::warn!(
                                target: "hkask.mcp.kata_kanban",
                                task_id = %tid,
                                %error,
                                "could not record the worktree spawn note — the spawn \
                                 itself succeeded; surfacing the partial outcome"
                            );
                            Some(error.to_string())
                        }
                    };
                Ok(TaskSpawnResponse {
                    task_id: tid.to_string(),
                    message: format!(
                        "Queued worktree thread for task '{}' ({}). \
                         Session establishment and auto-submit are pending; task status is unchanged.",
                        task.title, tid
                    ),
                    result_note_error,
                    ontology: kanban_type_to_pko("kanban_task_spawn").map(|s| s.to_string()),
                })
            }
            Err(hkask_types::InferenceError::Auth(message)) => {
                Err(McpToolError::permission_denied(message))
            }
            Err(error) => Err(McpToolError::unavailable(format!(
                "Worktree spawn did not return success: {error}. No fallback was started; reconcile before retrying because effects may have occurred."
            ))),
        }
    }

    /// Read the structured delegation result and deterministic verdict for a
    /// task that was spawned via `kanban_task_spawn`. Returns the persisted
    /// `LocalDelegateResult` and `TaskSuccessVerdict` fields, enabling the
    /// swarm-intelligence SENSE phase and the Curator to query the durable
    /// coordination state without parsing free-text comments.
    ///
    /// contract: P3-svc-kanban-010
    /// expect: "I can read the structured delegation result for a spawned task" \[P3\]
    /// pre:  task_id is a valid task id
    /// post: returns the delegation result + verdict, or `has_result: false`
    #[tool(
        description = "Read the structured delegation result and deterministic verdict for a task spawned via kanban_task_spawn. Returns the persisted LocalDelegateResult and TaskSuccessVerdict."
    )]
    pub async fn kanban_task_delegate_result(
        &self,
        Parameters(TaskDelegateResultRequest { task_id }): Parameters<TaskDelegateResultRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_task_delegate_result", async {
            let tid = parse_task_id(&task_id)?;
            let task = self
                .service
                .task_get(tid)
                .map_err(map_kanban_error)?
                .ok_or_else(|| McpToolError::not_found(format!("task {tid} not found")))?;
            serde_json::to_value(TaskDelegateResultResponse {
                task_id: tid.to_string(),
                has_result: task.delegate_result.is_some(),
                delegate_result: task.delegate_result.clone(),
                deterministic_verdict: task.deterministic_verdict.clone(),
                swarm_id: task.swarm_id,
                ontology: kanban_type_to_pko("kanban_task_delegate_result").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    /// Create kanban tasks for contracts missing `expect:` user-voice annotations.
    ///
    /// Takes a JSON list of ExpectProposal structs (from test-harness
    /// `propose_missing_expect_annotations`) and creates a task per contract gap.
    /// Owning agents can claim and resolve these tasks by submitting
    /// `expect:` annotation PRs (P2 consent required for merge).
    ///
    /// contract: P3-svc-kanban-009
    /// expect: "I can create kanban tasks from contract expectation gaps so agents can ground them" \[P3\]
    /// \[P5\] Constraining: Essentialism — one batch operation, no individual task editing
    /// pre:  proposals is a non-empty JSON array of ExpectProposal structs
    /// pre:  board_id is a valid board ID
    /// post: returns created task IDs (one per proposal)
    #[tool(
        description = "Create kanban tasks for contracts missing expect: annotations. Takes JSON from propose_missing_expect_annotations."
    )]
    pub async fn contract_propose_expect(
        &self,
        Parameters(ContractProposeExpect {
            board_id,
            proposals,
        }): Parameters<ContractProposeExpect>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "contract_propose_expect", async {
            let bid = parse_board_id(&board_id)?;

            let proposals: Vec<hkask_types::ExpectProposal> =
                match serde_json::from_value(serde_json::Value::from(proposals)) {
                    Ok(p) => p,
                    Err(e) => return Err(McpToolError::invalid_argument(format!("invalid proposals: {e}"))),
                };

            if proposals.is_empty() {
                return Err(McpToolError::invalid_argument("proposals must be non-empty"));
            }

            let mut created: Vec<String> = Vec::new();
            for prop in &proposals {
                let title = format!(
                    "contract({}): add expect: to {}",
                    prop.crate_name, prop.function,
                );
                let description = format!(
                    "File: {}:{}\nContract: {}\nPre: {}\nPost: {}\n\nTemplate:\n{}\n\nSuggested principle: {}\nConstraining: {:?}",
                    prop.file,
                    prop.line,
                    prop.contract_id,
                    prop.pre,
                    prop.post,
                    prop.expect_template,
                    prop.suggested_goal_principle,
                    prop.existing_constraining_principles,
                );
                let spec = TaskSpec::new(title).with_description(description);
                match self.service.task_create(bid, spec, self.webid) {
                    Ok(task) => created.push(task.id.to_string()),
                    Err(e) => {
                        return Err(map_kanban_error(e));
                    }
                }
            }

            Ok(serde_json::json!({
                "created": created.len(),
                "task_ids": created,
                "crate": proposals[0].crate_name,
                "pko": kanban_type_to_pko("contract_propose_expect").map(|s| s.to_string()),
            }))
        })
        .await
    }

    /// Export a kanban board as mermaid kanban markdown (structure only:
    /// columns, task titles, task IDs). The markdown round-trips through
    /// `kanban_board_import`. Only the board owner can export (P12).
    ///
    /// contract: P3-svc-kanban-012
    /// expect: "I can export a kanban board I own as mermaid markdown" \[P3\]
    /// pre:  board_id is a valid board id owned by the caller
    /// post: returns the mermaid markdown plus a structural summary
    #[tool(
        description = "Export a kanban board as mermaid kanban markdown (columns + task titles)."
    )]
    pub async fn kanban_board_export(
        &self,
        Parameters(BoardExportRequest { board_id }): Parameters<BoardExportRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(self, "kanban_board_export", async {
            let bid = parse_board_id(&board_id)?;
            let board = self
                .service
                .board_get(bid)
                .map_err(map_kanban_error)?
                .ok_or_else(|| McpToolError::not_found(format!("board {bid} not found")))?;
            if board.owner != self.webid {
                return Err(McpToolError::permission_denied(format!(
                    "board {bid} is not owned by caller — cannot export"
                )));
            }
            let tasks = self
                .service
                .task_list(bid, TaskFilter::all())
                .map_err(map_kanban_error)?;
            let task_count = tasks.len();
            let column_count = board.columns.len();
            let markdown = kanban::mermaid::export_board_to_mermaid(&board, &tasks);
            serde_json::to_value(BoardExportResponse {
                markdown,
                board_id: bid.to_string(),
                board_name: board.name,
                column_count,
                task_count,
                ontology: kanban_type_to_pko("kanban_board_export").map(|s| s.to_string()),
            })
            .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
        })
        .await
    }

    /// Import mermaid kanban markdown as one atomic board aggregate. The MCP
    /// adapter parses the document; `KanbanService::board_import` publishes the
    /// board, task payloads, and indexes together with their parsed statuses.
    /// Replay-safe via `idempotency_key`.
    ///
    /// contract: P3-svc-kanban-013
    /// expect: "I can import mermaid kanban markdown as a new board" \[P3\]
    /// pre:  markdown contains a `kanban` directive and at least one `section`
    /// post: returns the new board id and a structural summary
    #[tool(
        description = "Import mermaid kanban markdown as a new board with tasks in parsed columns."
    )]
    pub async fn kanban_board_import(
        &self,
        Parameters(BoardImportRequest {
            markdown,
            board_name,
            idempotency_key,
        }): Parameters<BoardImportRequest>,
    ) -> Result<String, McpToolError> {
        execute_tool(
            self,
            "kanban_board_import",
            with_idempotency(
                &self.idempotency,
                "kanban_board_import",
                idempotency_key.as_deref(),
                &self.webid,
                serde_json::json!({ "markdown": markdown, "board_name": board_name }),
                async {
                    let mut parsed = kanban::mermaid::parse_mermaid_kanban(&markdown)
                        .map_err(|e| McpToolError::invalid_argument(e.to_string()))?;
                    if parsed.columns.is_empty() {
                        return Err(McpToolError::invalid_argument(
                            "mermaid kanban markdown has no sections — nothing to import",
                        ));
                    }
                    let name = board_name
                        .or(parsed.name.take())
                        .unwrap_or_else(|| "Imported Board".to_string());
                    let (board, task_count) = self
                        .service
                        .board_import(self.webid, &name, &parsed)
                        .map_err(map_kanban_error)?;
                    let column_count = board.columns.len();

                    serde_json::to_value(BoardImportResponse {
                        board_id: board.id.to_string(),
                        board_name: board.name,
                        column_count,
                        task_count,
                        ontology: kanban_type_to_pko("kanban_board_import").map(|s| s.to_string()),
                    })
                    .map_err(|e| McpToolError::internal(e.to_string())) // rr0044-ok: serialize-own-struct
                },
            ),
        )
        .await
    }
}

/// Parse a task id string or return an `invalid_argument` MCP error.
///
/// Replaces the repeated `match task_id.parse::<hkask_types::TaskId>() { Ok(id) => id, Err(e) => return Err(McpToolError::invalid_argument(...)) }`
/// block across the kanban tool methods.
fn parse_task_id(task_id: &str) -> Result<hkask_types::TaskId, McpToolError> {
    task_id
        .parse::<hkask_types::TaskId>()
        .map_err(|e| McpToolError::invalid_argument(format!("invalid task_id: {e}")))
}

/// Parse a board id string or return an `invalid_argument` MCP error.
fn parse_board_id(board_id: &str) -> Result<hkask_types::BoardId, McpToolError> {
    board_id
        .parse::<hkask_types::BoardId>()
        .map_err(|e| McpToolError::invalid_argument(format!("invalid board_id: {e}")))
}

/// Parse a goal id string or return an `invalid_argument` MCP error.
fn parse_goal_id(goal_id: &str) -> Result<hkask_types::GoalID, McpToolError> {
    goal_id
        .parse::<hkask_types::GoalID>()
        .map_err(|e| McpToolError::invalid_argument(format!("invalid goal_id: {e}")))
}

/// Parse a goal verdict string ("done" | "continue" | "blocked") into a
/// `GoalVerdictValue`.
fn parse_goal_verdict(verdict: &str) -> Result<GoalVerdictValue, McpToolError> {
    match verdict {
        "done" => Ok(GoalVerdictValue::Done),
        "continue" => Ok(GoalVerdictValue::Continue),
        "blocked" => Ok(GoalVerdictValue::Blocked),
        other => Err(McpToolError::invalid_argument(format!(
            "invalid verdict {other:?} — expected \"done\", \"continue\", or \"blocked\""
        ))),
    }
}

/// Map a service-layer `KanbanError` to the correct `McpToolError` variant.
///
/// Each `KanbanError` variant maps to a semantically appropriate MCP error kind
/// so that callers can distinguish not-found, permission-denied, precondition
/// failures, and internal errors from simple invalid-input errors.
///
/// contract: kanban-error-mapping
/// expect: "I can distinguish not-found, permission, and workflow errors from invalid-input errors" \[P4\]
/// pre:  e is a valid KanbanError
/// post: returns McpToolError with appropriate McpErrorKind
fn map_kanban_error(e: KanbanError) -> McpToolError {
    match e {
        KanbanError::NotFound(nf) => McpToolError::not_found(nf.to_string()),
        KanbanError::InvalidInput(msg) => McpToolError::invalid_argument(msg),
        KanbanError::InvalidTransition { .. } => McpToolError::failed_precondition(e.to_string()),
        KanbanError::PermissionDenied(msg) => McpToolError::permission_denied(msg),
        KanbanError::WipLimitExceeded { .. } => McpToolError::failed_precondition(e.to_string()),
        KanbanError::Internal(msg) => McpToolError::internal(msg), // rr0044-ok: kanban internal-error arm
    }
}

/// Run the kanban MCP server (used by binary target).
pub async fn run() -> Result<(), hkask_mcp_server::McpError> {
    hkask_mcp_server::run_server(
        hkask_types::kanban_wire::KANBAN_SERVER_NAME,
        env!("CARGO_PKG_VERSION"),
        |ctx: ServerContext| {
            (|| -> anyhow::Result<KanbanServer> {
                // D28 — Standardized Artifact Storage. Default DB path is
                // `{kask_data_dir}/mcp/kata-kanban/kanban.db`, resolved via
                // `resolve_under_data_dir`. Override via `HKASK_KANBAN_DB`.
                // `HKASK_KANBAN_DB` is a non-secret config path — read via
                // `std::env::var` (matching every other DB-path env var:
                // `HKASK_CURATOR_DB`, `HKASK_RESEARCH_DB`, etc.)
                // and injected via `config_env`, not `credentials`.
                let kanban_db_path = std::env::var("HKASK_KANBAN_DB")
                    .unwrap_or_else(|_| {
                        let relative_path =
                            hkask_types::agent_paths::mcp_server_db("kata-kanban", "kanban");
                        let default_path =
                            hkask_types::agent_paths::resolve_under_data_dir(&relative_path);
                        if let Some(Err(error)) = default_path.parent().map(std::fs::create_dir_all)
                        {
                            tracing::warn!(
                                target: "hkask.mcp.kata_kanban",
                                path = %default_path.display(),
                                %error,
                                "Failed to create default kanban DB directory \
                                 — the subsequent DB open will surface the failure"
                            );
                        }
                        tracing::info!(
                            target: "hkask.mcp.kata_kanban",
                            path = %default_path.display(),
                            "Using default per-agent kanban database"
                        );
                        default_path.to_string_lossy().to_string()
                    });
                // Resolve the DB passphrase through the canonical 2-tier chain
                // (ctx.credentials → resolve_credential which does env → keychain).
                // See `hkask_mcp_server::server::resolve_db_passphrase`.
                let passphrase = resolve_db_passphrase(&ctx.credentials)
                    .map_err(|error| anyhow::anyhow!("HKASK_DB_PASSPHRASE: {error}"))?;
                let db = hkask_storage::open_or_repair(&kanban_db_path, &passphrase)
                    .map_err(|error| anyhow::anyhow!("{error}"))?;
                let pool = db
                    .sqlite_pool()
                    .map_err(|error| anyhow::anyhow!("pool: {error}"))?;
                let driver: Arc<dyn hkask_storage::database::driver::DatabaseDriver> = Arc::new(
                    hkask_storage::database::sqlite::SqliteDriver::new_labeled(
                        pool,
                        kanban_db_path.as_str(),
                    ),
                );
                // Clone the handle before `HMemStore` takes ownership: replay
                // protection lives in the same database as the writes it guards.
                let idempotency_driver = driver.clone();
                let store = HMemStore::from_driver(driver)
                    .map_err(|e| anyhow::anyhow!("hmem store init: {e}"))?;
                let service = KanbanService::new(store);

                // Local swarm delegation surface (kanban_task_spawn). No
                // ledger: local agents run on the operator's own substrate
                // (operator ruling 2026-09-04 — no local budget).
                // Local agent registry — same dir resolution as hkask-mcp-swarm
                // (relative paths resolve under the hKask data dir, not CWD).
                // The FALLBACK default must match the swarm server's
                // (`mcp/swarm/agents/curated`) so a standalone kanban run
                // reads the same registry the swarm server reads — zed
                // always injects `HKASK_LOCAL_AGENTS_DIR`, but the two
                // servers must not silently diverge when it is absent.
                let local_agents_dir = std::env::var("HKASK_LOCAL_AGENTS_DIR")
                    .ok()
                    .filter(|s| !s.trim().is_empty())
                    .unwrap_or_else(|| "mcp/swarm/agents/curated".to_string());
                let local_agents_dir =
                    if std::path::Path::new(&local_agents_dir).is_absolute() {
                        local_agents_dir
                    } else {
                        hkask_types::agent_paths::resolve_under_data_dir(
                            std::path::Path::new(&local_agents_dir),
                        )
                        .to_string_lossy()
                        .to_string()
                    };
                let local_registry = Arc::new(LocalAgentRegistry::new(local_agents_dir));
                if let Err(error) = local_registry.load() {
                    tracing::warn!(
                        target: "hkask.mcp.kata_kanban",
                        %error,
                        "failed to load local agent cards — kanban_task_spawn will fall back to creating task-specific agents"
                    );
                }

                let worktree_spawn_port =
                    tokio::task::block_in_place(|| {
                        tokio::runtime::Handle::current()
                            .block_on(hkask_inference::resolve_worktree_spawn_port())
                    });

                // Replay protection shares the durable encrypted kanban driver.
                // Schema initialization failure aborts startup; accepting writes
                // without durable replay protection would violate the same
                // persistence contract as an unavailable kanban database.
                let idempotency = idempotency::IdempotencyStore::with_driver(
                    idempotency_driver,
                )
                .map_err(|error| anyhow::anyhow!(
                    "replay-protection schema initialization failed: {error}"
                ))?;

                // Goals persist through resolution until curator-memory
                // acknowledgment (operator ruling 2026-09-16), so their replay
                // protection shares the durable store — a replayed create
                // returns a live goal's id.
                let idempotency = Arc::new(idempotency);
                let goal_idempotency = Arc::clone(&idempotency);

                Ok(KanbanServer::new(ctx.webid, service, local_registry, worktree_spawn_port, idempotency, goal_idempotency))
            })()
            .map_err(|e| hkask_mcp_server::McpError::UnexpectedResponse {
                context: "kanban server init".into(),
                detail: e.to_string(),
            })
        },
        vec![
            hkask_mcp_server::CredentialRequirement::required(
                "HKASK_DB_PASSPHRASE",
                "SQLCipher encryption passphrase (resolved via hkask keystore chain when not set)",
            ),
        ],
    )
    .await
}

// Pins the generated TOOL_NAMES const against the live rmcp tool surface —
// a tool added/renamed without regenerating (or a `name =` override the
// build script can't see) fails here instead of degrading to "tool not
// found" at dispatch time.
#[test]
fn tool_names_match_live_router() {
    let mut live: Vec<String> = KanbanServer::tool_router()
        .list_all()
        .iter()
        .map(|tool| tool.name.to_string())
        .collect();
    live.sort();
    let generated: Vec<&str> = TOOL_NAMES.to_vec();
    assert_eq!(
        generated,
        live.iter().map(String::as_str).collect::<Vec<_>>(),
        "TOOL_NAMES (build.rs-generated) must match the live tool_router surface"
    );
}

/// expect: "Kanban refuses startup rather than accepting mutations without durable encrypted state."
/// [P1] Motivating: User Sovereignty — the operator can trust persisted workflow state.
/// [P2] Constraining: Transparent Imperfection — missing durability is an explicit startup failure.
/// pre: the production startup source is compiled
/// post: no volatile DB/replay fallback remains and HKASK_DB_PASSPHRASE is required
#[test]
fn kanban_startup_requires_durable_storage() {
    let source = include_str!("hkask_mcp_kata_kanban.rs");
    let volatile_database = ["Database", "::in_memory()"].concat();
    let volatile_replay = ["IdempotencyStore", "::default()"].concat();
    let required_passphrase = [
        "CredentialRequirement::required(",
        "\n                \"HKASK_DB_PASSPHRASE\"",
    ]
    .concat();
    assert!(!source.contains(&volatile_database));
    assert!(!source.contains(&volatile_replay));
    assert!(source.contains(&required_passphrase));
}

// D28 — pins the default DB path resolution.
#[test]
fn default_db_path_follows_standardized_layout() {
    let relative = hkask_types::agent_paths::mcp_server_db("kata-kanban", "kanban");
    assert_eq!(
        relative,
        std::path::PathBuf::from("mcp")
            .join("kata-kanban")
            .join("kanban.db"),
        "kata-kanban default DB path must follow mcp/kata-kanban/kanban.db"
    );
}
