//! PKO (Procedural Knowledge Ontology) mapping for hkask-mcp-kata-kanban.
//!
//! Maps kanban types and field names to PKO standard concepts. PKO is the
//! ISWC 2024 process ontology from the EU PERKS project (Grant 101120323).
//! PKO extends P-Plan and PROV-O via soft reuse.
//!
//! Reference: <https://w3id.org/pko> — Carriero et al., arXiv:2503.20634
//!
//! Key PKO modules used:
//! - pko:Procedure                 — procedure specification (board)
//! - pko:Step / pko:MultiStep      — atomic/composite steps (tasks)
//! - pko:StepExecution             — step occurrence (in-progress task)
//! - pko:StepVerification          — verification of step completion
//! - pko:ChangeOfStatus            — status transitions
//! - pko:UserFeedbackOccurrence    — feedback left during execution
//! - pko:UserQuestionOccurrence    — questions asked during execution
//! - pko:IssueOccurrence           — errors/problems encountered
//! - ppro:RoleInTime               — agent role scoped to time period
//! - prov:Agent / prov:Activity    — PROV-O provenance base

/// A PKO concept curie — namespace-prefixed short form.
/// e.g. "pko:StepExecution", "pko:UserFeedbackOccurrence"
pub type PkoConcept = &'static str;

// ── PKO concept constants ──────────────────────────────────────────────────

/// Procedure specification — the board itself.
pub const PROCEDURE: PkoConcept = "pko:Procedure";
/// A step within a procedure — a single task.
pub const STEP: PkoConcept = "pko:Step";
/// A composite step decomposed into sub-steps — task with sub-tasks.
pub(crate) const MULTISTEP: PkoConcept = "pko:MultiStep";
/// A single execution of a procedure.
pub const PROCEDURE_EXECUTION: PkoConcept = "pko:ProcedureExecution";
/// A single execution of a step — a task being worked on.
pub const STEP_EXECUTION: PkoConcept = "pko:StepExecution";
/// Status of a procedure execution (e.g. in progress, completed).
pub const PROCEDURE_EXECUTION_STATUS: PkoConcept = "pko:ProcedureExecutionStatus";
/// A transition between two statuses.
pub(crate) const CHANGE_OF_STATUS: PkoConcept = "pko:ChangeOfStatus";
/// Verification that a step was executed correctly.
pub const STEP_VERIFICATION: PkoConcept = "pko:StepVerification";
/// User feedback left during or after execution.
pub const USER_FEEDBACK_OCCURRENCE: PkoConcept = "pko:UserFeedbackOccurrence";
/// A question asked by an agent during execution.
pub const USER_QUESTION_OCCURRENCE: PkoConcept = "pko:UserQuestionOccurrence";
/// An issue/error that occurred during execution.
pub const ISSUE_OCCURRENCE: PkoConcept = "pko:IssueOccurrence";
/// An error code or description.
pub const ERROR: PkoConcept = "pko:Error";

/// Expected duration of a step/procedure.
pub(crate) const HAS_EXPECTED_DURATION: PkoConcept = "pko:hasExpectedDuration";

// ── Reused ontology concepts ────────────────────────────────────────────────

/// Agent — PROV-O base.
pub const AGENT: PkoConcept = "prov:Agent";
/// Agent associated with an activity — PROV-O.
pub(crate) const WAS_ASSOCIATED_WITH: PkoConcept = "prov:wasAssociatedWith";
/// Entity generated by an activity — PROV-O.
pub(crate) const WAS_GENERATED_BY: PkoConcept = "prov:wasGeneratedBy";
/// Entity used by an activity — PROV-O.
pub(crate) const USED: PkoConcept = "prov:used";

// ── Kanban type → PKO concept mapping ──────────────────────────────────────

/// Map a kanban type name to its PKO concept URI.
/// Returns None for internal types without a PKO equivalent.
pub(crate) fn kanban_type_to_pko(type_name: &str) -> Option<PkoConcept> {
    match type_name {
        "Board"
        | "kanban_board_create"
        | "kanban_board_list"
        | "kanban_board_delete"
        | "kanban_board_export"
        | "kanban_board_import" => Some(PROCEDURE),
        "Task" | "kanban_task_create" | "kanban_task_list" => Some(STEP),
        "Task.decomposed" | "kanban_task_decompose" => Some(MULTISTEP),
        "Task.execution" | "Task.in_progress" | "kanban_task_spawn" => Some(STEP_EXECUTION),
        "Board.execution" => Some(PROCEDURE_EXECUTION),
        "Column" | "TaskStatus" => Some(PROCEDURE_EXECUTION_STATUS),
        "kanban_task_move" | "kanban_task_reopen" => Some(CHANGE_OF_STATUS),
        "kanban_task_verify" | "Verification" | "VerificationCriterion" => Some(STEP_VERIFICATION),
        "Comment" | "kanban_task_comment" => Some(USER_FEEDBACK_OCCURRENCE),
        "Comment.question"
        | "kanban_task_kata_coaching"
        | "kanban_task_kata_improvement"
        | "kanban_task_kata_practice" => Some(USER_QUESTION_OCCURRENCE),
        "UnjamItem" | "kanban_unjam" => Some(ISSUE_OCCURRENCE),
        "UnjamItem.error" => Some(ERROR),
        "Assignee" | "kanban_task_assign" => Some(WAS_ASSOCIATED_WITH),
        "Deliverable" | "kanban_task_add_deliverable" => Some(WAS_GENERATED_BY),
        "SpendEntry" | "kanban_task_add_rjoules" => Some(USED),
        "estimated_hours" => Some(HAS_EXPECTED_DURATION),
        "Agent" | "assignee" => Some(AGENT),
        _ => None,
    }
}
