//! PKO (Procedural Knowledge Ontology) mapping for hkask-mcp-kata-kanban.
//!
//! Maps kanban types and field names to PKO standard concepts. PKO is the
//! ISWC 2024 process ontology from the EU PERKS project (Grant 101120323).
//! PKO extends P-Plan and PROV-O via soft reuse.
//!
//! Reference: <https://w3id.org/pko> — Carriero et al., arXiv:2503.20634
//!
//! Key PKO modules used:
//! - pko:Procedure                 — procedure specification (board)
//! - pko:Step / pko:MultiStep      — atomic/composite steps (tasks)
//! - pko:StepExecution             — step occurrence (in-progress task)
//! - pko:StepVerification          — verification of step completion
//! - pko:ChangeOfStatus            — status transitions
//! - pko:UserFeedbackOccurrence    — feedback left during execution
//! - pko:UserQuestionOccurrence    — questions asked during execution
//! - pko:IssueOccurrence           — errors/problems encountered
//! - ppro:RoleInTime               — agent role scoped to time period
//! - prov:Agent / prov:Activity    — PROV-O provenance base

/// A PKO concept curie — namespace-prefixed short form.
/// e.g. "pko:StepExecution", "pko:UserFeedbackOccurrence"
pub type PkoConcept = &'static str;

// ── PKO concept constants ──────────────────────────────────────────────────

/// Procedure specification — the board itself.
pub const PROCEDURE: PkoConcept = "pko:Procedure";
/// A step within a procedure — a single task.
pub const STEP: PkoConcept = "pko:Step";
/// A composite step decomposed into sub-steps — task with sub-tasks.
pub const MULTISTEP: PkoConcept = "pko:MultiStep";
/// A single execution of a procedure.
pub const PROCEDURE_EXECUTION: PkoConcept = "pko:ProcedureExecution";
/// A single execution of a step — a task being worked on.
pub const STEP_EXECUTION: PkoConcept = "pko:StepExecution";
/// Status of a procedure (e.g. draft, approved, archived).
pub const PROCEDURE_STATUS: PkoConcept = "pko:ProcedureStatus";
/// Status of a procedure execution (e.g. in progress, completed).
pub const PROCEDURE_EXECUTION_STATUS: PkoConcept = "pko:ProcedureExecutionStatus";
/// A transition between two statuses.
pub const CHANGE_OF_STATUS: PkoConcept = "pko:ChangeOfStatus";
/// Verification that a step was executed correctly.
pub const STEP_VERIFICATION: PkoConcept = "pko:StepVerification";
/// User feedback left during or after execution.
pub const USER_FEEDBACK_OCCURRENCE: PkoConcept = "pko:UserFeedbackOccurrence";
/// A question asked by an agent during execution.
pub const USER_QUESTION_OCCURRENCE: PkoConcept = "pko:UserQuestionOccurrence";
/// An issue/error that occurred during execution.
pub const ISSUE_OCCURRENCE: PkoConcept = "pko:IssueOccurrence";
/// An error code or description.
pub const ERROR: PkoConcept = "pko:Error";
/// A human action required by a step.
pub const ACTION: PkoConcept = "pko:Action";
/// A software function required by a step.
pub const FUNCTION: PkoConcept = "pko:Function";

/// Expected duration of a step/procedure.
pub const HAS_EXPECTED_DURATION: PkoConcept = "pko:hasExpectedDuration";
/// The first step in a procedure or multistep.
pub const HAS_FIRST_STEP: PkoConcept = "pko:hasFirstStep";
/// Link from a step to the next step in sequence.
pub const NEXT_STEP: PkoConcept = "pko:nextStep";
/// The step linked to a procedure.
pub const HAS_STEP: PkoConcept = "pko:hasStep";
/// The procedure a step belongs to.
pub const IS_STEP_OF_PLAN: PkoConcept = "pplan:isStepOfPlan";
/// The procedure being executed.
pub const HAS_EXECUTED_PROCEDURE: PkoConcept = "pko:hasExecutedProcedure";
/// The step being executed.
pub const HAS_EXECUTED_STEP: PkoConcept = "pko:hasExecutedStep";
/// Error addressed by a fallback step.
pub const ADDRESSES_ERROR: PkoConcept = "pko:addressesError";
/// Error encountered during execution.
pub const HAS_ENCOUNTERED_ERROR: PkoConcept = "pko:hasEncounteredError";
/// Fallback (multi)step for an error.
pub const HAS_FALLBACK_STEP: PkoConcept = "pko:hasFallbackStep";
/// An issue that occurred during execution.
pub const HAS_ISSUE_OCCURRENCE: PkoConcept = "pko:hasIssueOccurrence";
/// Source status in a change of status.
pub const FROM_STATUS: PkoConcept = "pko:fromStatus";

// ── Reused ontology concepts ────────────────────────────────────────────────

/// Agent — PROV-O base.
pub const AGENT: PkoConcept = "prov:Agent";
/// Activity — PROV-O base.
pub const ACTIVITY: PkoConcept = "prov:Activity";
/// Agent associated with an activity — PROV-O.
pub const WAS_ASSOCIATED_WITH: PkoConcept = "prov:wasAssociatedWith";
/// Entity generated by an activity — PROV-O.
pub const WAS_GENERATED_BY: PkoConcept = "prov:wasGeneratedBy";
/// Entity used by an activity — PROV-O.
pub const USED: PkoConcept = "prov:used";

// ── Kanban type → PKO concept mapping ──────────────────────────────────────

/// Map a kanban type name to its PKO concept URI.
/// Returns None for internal types without a PKO equivalent.
pub fn kanban_type_to_pko(type_name: &str) -> Option<PkoConcept> {
    match type_name {
        "Board" | "kanban_board_create" | "kanban_board_list" => Some(PROCEDURE),
        "Task" | "kanban_task_create" | "kanban_task_list" => Some(STEP),
        "Task.decomposed" | "kanban_task_decompose" => Some(MULTISTEP),
        "Task.execution" | "Task.in_progress" | "kanban_task_spawn" => Some(STEP_EXECUTION),
        "Board.execution" => Some(PROCEDURE_EXECUTION),
        "Column" | "TaskStatus" => Some(PROCEDURE_EXECUTION_STATUS),
        "kanban_task_move" | "kanban_task_reopen" => Some(CHANGE_OF_STATUS),
        "kanban_task_verify" | "Verification" | "VerificationCriterion" => Some(STEP_VERIFICATION),
        "Comment" | "kanban_task_comment" => Some(USER_FEEDBACK_OCCURRENCE),
        "Comment.question"
        | "kanban_task_kata_coaching"
        | "kanban_task_kata_improvement"
        | "kanban_task_kata_practice" => Some(USER_QUESTION_OCCURRENCE),
        "UnjamItem" | "kanban_unjam" => Some(ISSUE_OCCURRENCE),
        "UnjamItem.error" => Some(ERROR),
        "Assignee" | "kanban_task_assign" => Some(WAS_ASSOCIATED_WITH),
        "Deliverable" | "kanban_task_add_deliverable" => Some(WAS_GENERATED_BY),
        "GasEntry" | "gas_spend" | "kanban_task_add_gas" | "kanban_task_add_rjoules" => Some(USED),
        "estimated_hours" => Some(HAS_EXPECTED_DURATION),
        "Agent" | "assignee" => Some(AGENT),
        _ => None,
    }
}

/// Map a kanban task status to its PKO ProcedureExecutionStatus concept.
pub fn task_status_to_pko(status: &str) -> Option<PkoConcept> {
    match status {
        "backlog" | "ready" => Some("pko:ProcedureExecutionStatus"), // pending
        "in_progress" => Some("pko:ProcedureExecutionStatus"),       // active
        "review" => Some("pko:ProcedureExecutionStatus"),            // under review
        "done" => Some("pko:ProcedureExecutionStatus"),              // completed
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kanban_type_to_pko_maps_all_core_types() {
        for (type_name, _expected) in &[
            ("Board", PROCEDURE),
            ("Task", STEP),
            ("kanban_task_move", CHANGE_OF_STATUS),
            ("kanban_task_verify", STEP_VERIFICATION),
            ("Comment", USER_FEEDBACK_OCCURRENCE),
            ("UnjamItem", ISSUE_OCCURRENCE),
            ("Assignee", WAS_ASSOCIATED_WITH),
            ("Deliverable", WAS_GENERATED_BY),
            ("GasEntry", USED),
            ("estimated_hours", HAS_EXPECTED_DURATION),
        ] {
            assert!(
                kanban_type_to_pko(type_name).is_some(),
                "type '{type_name}' must have PKO mapping"
            );
        }
    }

    #[test]
    fn kanban_type_to_pko_unknown_returns_none() {
        assert!(kanban_type_to_pko("InternalDbConnection").is_none());
        assert!(kanban_type_to_pko("").is_none());
    }

    #[test]
    fn task_status_to_pko_all_statuses() {
        for status in &["backlog", "ready", "in_progress", "review", "done"] {
            assert!(
                task_status_to_pko(status).is_some(),
                "status '{status}' must map"
            );
        }
    }
}
