//! Build script — auto-discovers per-skill template and process manifests at compile time.
//!
//! Scans four things:
//! 1. `registry/templates/*/manifest.yaml` — per-skill template manifests (WordAct/KnowAct).
//! 2. `registry/manifests/*.yaml` — process manifests (FlowDef cascade definitions).
//! 3. `registry/templates/*/*.j2` — Jinja2 template files (WordAct/KnowAct/RenderAct).
//! 4. `registry/templates/*/*.yaml` — YAML template files (FlowDef sub-manifests +
//!    RenderAct `.yaml` reference docs). Excludes `manifest.yaml` which is
//!    already embedded by scan #1.
//!
//! All four are embedded via `include_str!` so the runtime binary has the full
//! registry available as a fallback. The filesystem is the primary source at
//! runtime — YAML/J2 edits take effect immediately without recompilation.
//! Embedded copies are used when the registry directory is not present on disk
//! (production deployments without the source tree).
//!
//! Per-skill template manifests are the canonical source of truth (AGENTS.md),
//! eliminating the hand-maintained `bootstrap-registry.yaml` flat index.
//!
//! The `.yaml` template files (scan #4) cover two of the four Pattern A template
//! types: FlowDef sub-manifests (composable `.yaml` pipelines invoked by
//! `action: flowdef` steps) and RenderAct `.yaml` reference docs (structured
//! reference content never sent to the LLM). The `.j2` files (scan #3) cover
//! WordAct, KnowAct, and RenderAct Jinja2 components.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let kask_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Could not locate kask root from crate manifest dir");

    // ── Per-skill template manifests (registry/templates/<skill>/manifest.yaml) ──
    let templates_dir = kask_root.join("registry/templates");
    let mut template_skills = Vec::new();
    if templates_dir.is_dir() {
        for entry in fs::read_dir(&templates_dir).expect("read registry/templates") {
            let entry = entry.expect("dir entry");
            let manifest_path = entry.path().join("manifest.yaml");
            if manifest_path.is_file() {
                let skill_name = entry
                    .file_name()
                    .to_str()
                    .expect("UTF-8 skill directory name")
                    .to_string();
                template_skills.push((skill_name, manifest_path));
            }
        }
    }
    template_skills.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — per-skill template manifests.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static MANIFEST_YAMLS: &[(&str, &str)] = &[\n");
    for (name, path) in &template_skills {
        let abs = path.to_str().expect("UTF-8 manifest path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];\n");

    // ── Process manifests (registry/manifests/<skill>.yaml) ──
    let process_manifests_dir = kask_root.join("registry/manifests");
    let mut process_manifests = Vec::new();
    if process_manifests_dir.is_dir() {
        for entry in fs::read_dir(&process_manifests_dir).expect("read registry/manifests") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.is_file() && path.extension().is_some_and(|e| e == "yaml") {
                let skill_name = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .expect("UTF-8 manifest filename")
                    .to_string();
                process_manifests.push((skill_name, path));
            }
        }
    }
    process_manifests.sort_by(|a, b| a.0.cmp(&b.0));

    code.push_str("\n// Auto-generated by build.rs — process manifests (FlowDef cascades).\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static PROCESS_MANIFEST_YAMLS: &[(&str, &str)] = &[\n");
    for (name, path) in &process_manifests {
        let abs = path.to_str().expect("UTF-8 process manifest path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];\n");

    // ── Jinja2 template files (registry/templates/<skill>/*.j2) ──
    // Embedded so `template_ref` resolution works without filesystem access.
    // The key is the path relative to `registry/templates/` (e.g.
    // `grill-me/grill-me-assess.j2`). `template_file()` in registry.rs handles
    // both the with-extension and without-extension forms of lookup.
    let mut template_files: Vec<(String, PathBuf)> = Vec::new();
    if templates_dir.is_dir() {
        for entry in fs::read_dir(&templates_dir).expect("read registry/templates for .j2") {
            let entry = entry.expect("dir entry");
            let skill_dir = entry.path();
            if !skill_dir.is_dir() {
                continue;
            }
            let skill_name = entry
                .file_name()
                .to_str()
                .expect("UTF-8 skill directory name")
                .to_string();
            for j2_entry in fs::read_dir(&skill_dir).expect("read skill template dir") {
                let j2_entry = j2_entry.expect("dir entry");
                let j2_path = j2_entry.path();
                if j2_path.is_file() && j2_path.extension().is_some_and(|e| e == "j2") {
                    let file_name = j2_entry
                        .file_name()
                        .to_str()
                        .expect("UTF-8 template filename")
                        .to_string();
                    let key = format!("{skill_name}/{file_name}");
                    template_files.push((key, j2_path));
                }
            }
        }
    }
    template_files.sort_by(|a, b| a.0.cmp(&b.0));

    code.push_str("\n// Auto-generated by build.rs — Jinja2 template files.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static TEMPLATE_FILES: &[(&str, &str)] = &[\n");
    for (key, path) in &template_files {
        let abs = path.to_str().expect("UTF-8 template file path");
        code.push_str(&format!("    (\"{key}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];");

    // ── YAML template files (registry/templates/<skill>/*.yaml, excluding manifest.yaml) ──
    // These are FlowDef sub-manifests (composable `.yaml` pipelines invoked by
    // `action: flowdef` steps) and RenderAct `.yaml` reference docs (structured
    // reference content never sent to the LLM). `manifest.yaml` is excluded
    // because it's already embedded by the per-skill template manifest scan above.
    //
    // The key is the path relative to `registry/templates/` (e.g.
    // `media/logo-discovery.yaml`). `template_yaml_file()` in registry.rs handles
    // both the with-extension and without-extension forms of lookup.
    let mut template_yaml_files: Vec<(String, PathBuf)> = Vec::new();
    if templates_dir.is_dir() {
        for entry in fs::read_dir(&templates_dir).expect("read registry/templates for .yaml") {
            let entry = entry.expect("dir entry");
            let skill_dir = entry.path();
            if !skill_dir.is_dir() {
                continue;
            }
            let skill_name = entry
                .file_name()
                .to_str()
                .expect("UTF-8 skill directory name")
                .to_string();
            for yaml_entry in fs::read_dir(&skill_dir).expect("read skill template dir for .yaml") {
                let yaml_entry = yaml_entry.expect("dir entry");
                let yaml_path = yaml_entry.path();
                // Skip manifest.yaml (already embedded above) and non-yaml files.
                // Also skip subdirectories — only one level deep.
                if !yaml_path.is_file() {
                    continue;
                }
                let file_name = yaml_entry
                    .file_name()
                    .to_str()
                    .expect("UTF-8 template filename")
                    .to_string();
                if file_name == "manifest.yaml" {
                    continue;
                }
                if yaml_path.extension().is_some_and(|e| e == "yaml") {
                    let key = format!("{skill_name}/{file_name}");
                    template_yaml_files.push((key, yaml_path));
                }
            }
        }
    }
    template_yaml_files.sort_by(|a, b| a.0.cmp(&b.0));

    code.push_str("\n// Auto-generated by build.rs — YAML template files (FlowDef sub-manifests + RenderAct reference).\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static TEMPLATE_YAML_FILES: &[(&str, &str)] = &[\n");
    for (key, path) in &template_yaml_files {
        let abs = path.to_str().expect("UTF-8 template yaml path");
        code.push_str(&format!("    (\"{key}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];");

    // ── Company-source manifests (registry/company-sources/*.yaml) ──
    // Corpus-specific resource manifests (SEC filing source lists, YouTube
    // channel allowlists). Not skill manifests or templates — a separate
    // resource class consumed by the corpus MCP server's
    // `corpus_discover_company` tool. Embedded so the seeding path can
    // materialise them to disk in production (where the source tree is
    // absent). The key is the filename stem (e.g. `msft`), matching the
    // `corpus_discover_company` default path convention
    // `company-sources/{symbol}.yaml`.
    let company_sources_dir = kask_root.join("registry/company-sources");
    let mut company_sources = Vec::new();
    if company_sources_dir.is_dir() {
        for entry in fs::read_dir(&company_sources_dir).expect("read registry/company-sources") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.is_file() && path.extension().is_some_and(|e| e == "yaml") {
                let symbol = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .expect("UTF-8 company-source filename")
                    .to_string();
                company_sources.push((symbol, path));
            }
        }
    }
    company_sources.sort_by(|a, b| a.0.cmp(&b.0));

    code.push_str("\n// Auto-generated by build.rs — company-source manifests.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static COMPANY_SOURCE_YAMLS: &[(&str, &str)] = &[\n");
    for (symbol, path) in &company_sources {
        let abs = path.to_str().expect("UTF-8 company-source path");
        code.push_str(&format!("    (\"{symbol}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("];");

    // ── MCP tool surface scan ─────────────────────────────────────────────
    // Scan every `kask/mcp-servers/hkask-mcp-*/src/**/*.rs` file for `#[tool]`-
    // annotated `pub async fn <name>` / `pub(crate) async fn <name>` methods and
    // emit a sorted, dedup'd `KNOWN_MCP_TOOLS` const. This replaces the hand-
    // maintained list in `tests/manifest_load_validation.rs` that drifted (the
    // `gemba-walk` manifest referenced `curator_grounding_trend` / `_coverage` /
    // `_violations` but the static list was never updated). The scan runs at
    // build time so the list refreshes automatically when a server adds a tool
    // — no manual step, no drift.
    //
    // The scanner is a simple line-by-line state machine:
    //   1. Skip `mod tests` / `mod tool_surface_tests` blocks (brace-counted).
    //   2. Skip `#[cfg(test)]`-annotated items (the attribute is on the line
    //      before the item; we track it and skip the next item).
    //   3. When we see `#[tool` (possibly multi-line `#[tool(\n ... \n)]`),
    //      set a pending flag.
    //   4. When we see `pub async fn <name>` / `pub(crate) async fn <name>` /
    //      `pub fn <name>` / `pub(crate) fn <name>` with the flag set, extract
    //      `<name>` and clear the flag.
    //
    // This is robust because rmcp's `#[tool]` attribute is always directly
    // above the method it annotates, and the method name IS the tool name
    // (the `#[tool]` macro derives the tool name from the method name).
    let mcp_servers_dir = kask_root.join("mcp-servers");
    let mut mcp_tools: Vec<String> = Vec::new();
    if mcp_servers_dir.is_dir() {
        for entry in fs::read_dir(&mcp_servers_dir).expect("read mcp-servers") {
            let entry = entry.expect("dir entry");
            let server_dir = entry.path();
            if !server_dir.is_dir() {
                continue;
            }
            let server_name = entry.file_name().to_string_lossy().to_string();
            if !server_name.starts_with("hkask-mcp-") {
                continue;
            }
            let src_dir = server_dir.join("src");
            if !src_dir.is_dir() {
                continue;
            }
            scan_rust_files_for_tools(&src_dir, &mut mcp_tools);
        }
    }
    mcp_tools.sort();
    mcp_tools.dedup();

    let mut tools_code = String::new();
    tools_code
        .push_str("// Auto-generated by build.rs — MCP tool names from #[tool] annotations.\n");
    tools_code.push_str("// Do not edit manually. Regenerated on every build.\n");
    tools_code
        .push_str("// Scans kask/mcp-servers/hkask-mcp-*/src/**/*.rs for `#[tool]`-annotated\n");
    tools_code.push_str("// `pub async fn <name>` / `pub(crate) async fn <name>` methods.\n");
    tools_code.push_str("// The method name IS the tool name (rmcp #[tool] derives it).\n\n");
    tools_code.push_str("pub static KNOWN_MCP_TOOLS: &[&str] = &[\n");
    for tool in &mcp_tools {
        tools_code.push_str(&format!("    \"{tool}\",\n"));
    }
    tools_code.push_str("];");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("manifest_skills.rs"), code).expect("write generated file");
    fs::write(out_dir.join("known_mcp_tools.rs"), tools_code).expect("write known_mcp_tools.rs");

    // Rebuild when manifests or templates change or skill directories are added/removed.
    println!("cargo:rerun-if-changed={}", templates_dir.display());
    for (_, path) in &template_skills {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", process_manifests_dir.display());
    for (_, path) in &process_manifests {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    for (_, path) in &template_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    for (_, path) in &template_yaml_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", company_sources_dir.display());
    for (_, path) in &company_sources {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", mcp_servers_dir.display());
}

/// Recursively scan a directory for `.rs` files and extract `#[tool]`-annotated
/// `pub async fn <name>` / `pub(crate) async fn <name>` method names.
fn scan_rust_files_for_tools(dir: &std::path::Path, tools: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        let path = entry.path();
        if path.is_dir() {
            scan_rust_files_for_tools(&path, tools);
        } else if path.extension().is_some_and(|e| e == "rs") {
            scan_rust_file_for_tools(&path, tools);
        }
    }
}

/// Scan a single `.rs` file for `#[tool]`-annotated method names.
///
/// State machine:
/// - `test_depth`: brace depth inside `mod tests` / `mod tool_surface_tests`.
///   `None` when not inside a test module. Tools inside test modules are
///   skipped (they're test fixtures, not registered MCP tools).
/// - `cfg_test_pending`: set when a line contains `#[cfg(test)]` — the next
///   item (fn, impl, mod) is skipped.
/// - `tool_pending`: set when we see `#[tool` — the next `pub (async )? fn <name>`
///   or `pub(crate) (async )? fn <name>` is extracted as a tool name.
fn scan_rust_file_for_tools(path: &std::path::Path, tools: &mut Vec<String>) {
    let source = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(_) => return,
    };

    let mut test_depth: Option<i32> = None;
    let mut cfg_test_pending = false;
    let mut tool_pending = false;
    let mut brace_depth_in_test = 0i32;

    for line in source.lines() {
        let trimmed = line.trim();

        // Track `#[cfg(test)]` — the next item is test-only.
        if trimmed.contains("#[cfg(test)]") {
            cfg_test_pending = true;
            continue;
        }

        // Track entry into `mod tests` / `mod tool_surface_tests` blocks.
        if test_depth.is_none()
            && (trimmed.starts_with("mod tests") || trimmed.starts_with("mod tool_surface_tests"))
        {
            if trimmed.contains('{') {
                test_depth = Some(0);
                brace_depth_in_test = 1;
                cfg_test_pending = false;
                tool_pending = false;
                continue;
            }
            // `mod tests;` — a separate file not compiled in non-test builds.
            cfg_test_pending = false;
            tool_pending = false;
            continue;
        }

        // If inside a test module, count braces to find the exit.
        if test_depth.is_some() {
            for ch in line.chars() {
                if ch == '{' {
                    brace_depth_in_test += 1;
                } else if ch == '}' {
                    brace_depth_in_test -= 1;
                    if brace_depth_in_test == 0 {
                        test_depth = None;
                        break;
                    }
                }
            }
            continue;
        }

        // Detect `#[tool` (start of a tool attribute, possibly multi-line).
        if trimmed.starts_with("#[tool") {
            tool_pending = true;
            continue;
        }

        // If a tool attribute is pending, look for the method declaration.
        if tool_pending {
            // Skip doc comments and other attributes between `#[tool]` and the fn.
            if trimmed.starts_with("///") || trimmed.starts_with("//") || trimmed.starts_with("#[")
            {
                continue;
            }
            // Extract the method name from `pub async fn <name>`,
            // `pub(crate) async fn <name>`, `pub fn <name>`, or
            // `pub(crate) fn <name>`.
            if let Some(name) = extract_tool_method_name(trimmed) {
                if !cfg_test_pending {
                    tools.push(name.to_string());
                }
                tool_pending = false;
                cfg_test_pending = false;
            } else if trimmed.contains("fn ") {
                // A `fn` line that we couldn't extract a name from — clear
                // the pending flag to avoid mis-attributing a later fn.
                tool_pending = false;
                cfg_test_pending = false;
            }
        } else {
            // Reset cfg_test_pending if we hit a non-attribute, non-fn line.
            if !trimmed.starts_with("#[") && !trimmed.starts_with("///") && !trimmed.is_empty() {
                cfg_test_pending = false;
            }
        }
    }
}

/// Extract the method name from a line like `pub async fn curator_ping(`,
/// `pub(crate) async fn swarm_get_swarm(`, or `pub fn example(`. Returns
/// `None` if the line isn't a pub fn declaration.
///
/// Handles `pub`, `pub(crate)`, and `pub(super)` visibility — the `#[tool]`
/// macro registers tools regardless of visibility, so `pub(crate)` is common
/// in servers that don't expose their methods outside the crate.
fn extract_tool_method_name(line: &str) -> Option<&str> {
    // Strip the visibility prefix: `pub `, `pub(crate) `, or `pub(super) `.
    let after_vis = line
        .strip_prefix("pub(crate) ")
        .or_else(|| line.strip_prefix("pub(super) "))
        .or_else(|| line.strip_prefix("pub "))?;
    // Strip `async fn ` or `fn `.
    let after_fn = after_vis
        .strip_prefix("async fn ")
        .or_else(|| after_vis.strip_prefix("fn "))?;
    // The method name is the identifier immediately after `fn `.
    let name_end = after_fn
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(after_fn.len());
    if name_end == 0 {
        return None;
    }
    Some(&after_fn[..name_end])
}
