//! Build script — auto-discovers per-skill template and process manifests at compile time.
//!
//! Scans three things:
//! 1. `registry/templates/*/manifest.yaml` — per-skill template manifests (WordAct/KnowAct).
//! 2. `registry/manifests/*.yaml` — process manifests (FlowDef cascade definitions).
//! 3. `registry/templates/*/*.j2` — Jinja2 template files referenced by `template_ref`.
//!
//! All three are embedded via `include_str!` so the runtime binary has the full
//! registry baked in. This eliminates the install-time path-resolution problem:
//! skills execute via the embedded manifests and templates regardless of CWD or
//! install location. The filesystem paths in `main.rs` are dev-only fallbacks.
//!
//! Per-skill template manifests are the canonical source of truth (AGENTS.md),
//! eliminating the hand-maintained `bootstrap-registry.yaml` flat index.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let kask_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Could not locate kask root from crate manifest dir");

    // ── Per-skill template manifests (registry/templates/<skill>/manifest.yaml) ──
    let templates_dir = kask_root.join("registry/templates");
    let mut template_skills = Vec::new();
    if templates_dir.is_dir() {
        for entry in fs::read_dir(&templates_dir).expect("read registry/templates") {
            let entry = entry.expect("dir entry");
            let manifest_path = entry.path().join("manifest.yaml");
            if manifest_path.is_file() {
                let skill_name = entry
                    .file_name()
                    .to_str()
                    .expect("UTF-8 skill directory name")
                    .to_string();
                template_skills.push((skill_name, manifest_path));
            }
        }
    }
    template_skills.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — per-skill template manifests.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static MANIFEST_YAMLS: &[(&str, &str)] = &[\n");
    for (name, path) in &template_skills {
        let abs = path.to_str().expect("UTF-8 manifest path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("]\n");

    // ── Process manifests (registry/manifests/<skill>.yaml) ──
    let process_manifests_dir = kask_root.join("registry/manifests");
    let mut process_manifests = Vec::new();
    if process_manifests_dir.is_dir() {
        for entry in fs::read_dir(&process_manifests_dir).expect("read registry/manifests") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.is_file() && path.extension().is_some_and(|e| e == "yaml") {
                let skill_name = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .expect("UTF-8 manifest filename")
                    .to_string();
                process_manifests.push((skill_name, path));
            }
        }
    }
    process_manifests.sort_by(|a, b| a.0.cmp(&b.0));

    code.push_str("\n// Auto-generated by build.rs — process manifests (FlowDef cascades).\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static PROCESS_MANIFEST_YAMLS: &[(&str, &str)] = &[\n");
    for (name, path) in &process_manifests {
        let abs = path.to_str().expect("UTF-8 process manifest path");
        code.push_str(&format!("    (\"{name}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("]\n");

    // ── Jinja2 template files (registry/templates/<skill>/*.j2) ──
    // Embedded so `template_ref` resolution works without filesystem access.
    // The key is the path relative to `registry/templates/` (e.g.
    // `grill-me/grill-me-assess.j2`). `template_file()` in registry.rs handles
    // both the with-extension and without-extension forms of lookup.
    let mut template_files: Vec<(String, PathBuf)> = Vec::new();
    if templates_dir.is_dir() {
        for entry in fs::read_dir(&templates_dir).expect("read registry/templates for .j2") {
            let entry = entry.expect("dir entry");
            let skill_dir = entry.path();
            if !skill_dir.is_dir() {
                continue;
            }
            let skill_name = entry
                .file_name()
                .to_str()
                .expect("UTF-8 skill directory name")
                .to_string();
            for j2_entry in fs::read_dir(&skill_dir).expect("read skill template dir") {
                let j2_entry = j2_entry.expect("dir entry");
                let j2_path = j2_entry.path();
                if j2_path.is_file() && j2_path.extension().is_some_and(|e| e == "j2") {
                    let file_name = j2_entry
                        .file_name()
                        .to_str()
                        .expect("UTF-8 template filename")
                        .to_string();
                    let key = format!("{skill_name}/{file_name}");
                    template_files.push((key, j2_path));
                }
            }
        }
    }
    template_files.sort_by(|a, b| a.0.cmp(&b.0));

    code.push_str("\n// Auto-generated by build.rs — Jinja2 template files.\n");
    code.push_str("// Do not edit manually. Regenerated on every build.\n\n");
    code.push_str("pub(crate) static TEMPLATE_FILES: &[(&str, &str)] = &[\n");
    for (key, path) in &template_files {
        let abs = path.to_str().expect("UTF-8 template file path");
        code.push_str(&format!("    (\"{key}\", include_str!(\"{abs}\")),\n"));
    }
    code.push_str("]\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("manifest_skills.rs"), code).expect("write generated file");

    // Rebuild when manifests or templates change or skill directories are added/removed.
    println!("cargo:rerun-if-changed={}", templates_dir.display());
    for (_, path) in &template_skills {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", process_manifests_dir.display());
    for (_, path) in &process_manifests {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    for (_, path) in &template_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}
