//! Property tests for the hkask-regulation sensor providers.
//!
//! These replace the deleted stub-based tests that faked the `Sensor` trait
//! (the `TestSensor` double with hardcoded values in the old `sensor_provider`
//! `mod tests`). No fake `Sensor` implementations are constructed here. The
//! tests exercise the real `TestCoverageSensor` / `MutationScoreSensor`
//! `metrics.json` extraction logic — the pure parsing path inside `sense()` —
//! over arbitrary JSON content generated by `arb_json_value`, adjudicated
//! through the `hkask-test-harness` Oracle taxonomy (reference + invariant
//! oracles). The private `latest_metrics_path` helper is exercised through the
//! public `sense()` API.
//!
//! Coverage focus:
//! - For arbitrary `metrics.json` content, the sensor returns a signal iff
//!   the numeric target field is present and below the set-point; otherwise
//!   it returns `None` (graceful degradation — never panics).
//! - `latest_metrics_path` selects the most-recently-modified `metrics.json`.
//! - Missing trace dir, empty trace dir, malformed JSON, non-numeric field,
//!   and at/above-set-point values all yield `None`.

use hkask_regulation::sensor_provider::{MutationScoreSensor, Sensor, TestCoverageSensor};
use hkask_regulation::types::loops::{Signal, SignalMetric};
use hkask_test_harness::{
    Oracle, OracleVerdict, arb_json_value, oracle_hardcoded, oracle_invariant, oracle_reference,
};
use proptest::prelude::*;
use serde_json::Value as JsonValue;
use std::path::Path;
use tempfile::TempDir;

/// Run an async `sense()` on a current-thread tokio runtime (proptest!
/// generates a sync `#[test]`, so we block on the future locally).
fn block_on_sense<S: Sensor + ?Sized>(sensor: &S) -> Option<Signal> {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("tokio runtime");
    rt.block_on(sensor.sense())
}

/// Serialize a `Signal` (or `None`) into the canonical JSON shape the
/// reference oracle compares against: `null` for no signal, or
/// `{"value": v, "set_point": sp, "metric": "<as_str>"}`.
fn signal_to_json(signal: Option<Signal>) -> JsonValue {
    match signal {
        None => JsonValue::Null,
        Some(s) => serde_json::json!({
            "value": s.value,
            "set_point": s.set_point,
            "metric": s.metric.as_str(),
        }),
    }
}

/// Write `contents` to `{trace_dir}/{run_name}/metrics.json`.
fn write_run_metrics(trace_dir: &Path, run_name: &str, contents: &str) {
    let run_dir = trace_dir.join(run_name);
    std::fs::create_dir_all(&run_dir).expect("create run dir");
    std::fs::write(run_dir.join("metrics.json"), contents).expect("write metrics.json");
}

fn assert_pass(oracle: &dyn Oracle, input: &JsonValue, output: &JsonValue) {
    match oracle.verify(input, output) {
        OracleVerdict::Pass => {}
        other => panic!("oracle verdict was {other:?}"),
    }
}

// ── Reference-oracle property tests ────────────────────────────────────────
//
// The reference oracle re-implements the extraction contract independently:
//   signal = Some(value)  iff  metrics["<field>"].as_f64() == Some(c) && c < set_point
//   signal = None          otherwise
// and compares against the sensor's actual output. This cross-checks the
// sensor's JSON path against an independent implementation.

proptest! {
    /// `TestCoverageSensor` extracts `coverage_pct` exactly when the
    /// reference says it should, for arbitrary `metrics.json` content.
    #[test]
    fn coverage_sensor_matches_reference_extraction(
        value in arb_json_value(),
        set_point in 0.0f64..1.0,
    ) {
        let dir = TempDir::new().expect("temp dir");
        let raw = serde_json::to_string(&value).unwrap_or_default();
        write_run_metrics(dir.path(), "run-1", &raw);

        let sensor = TestCoverageSensor::new(dir.path().to_path_buf(), set_point);
        let output_json = signal_to_json(block_on_sense(&sensor));

        let input_json = serde_json::json!({ "metrics": value, "set_point": set_point });
        let oracle = oracle_reference(|input: &JsonValue| -> JsonValue {
            let sp = input.get("set_point").and_then(|v| v.as_f64()).unwrap_or(0.0);
            let metrics = input.get("metrics").unwrap_or(&JsonValue::Null);
            match metrics.get("coverage_pct").and_then(|f| f.as_f64()) {
                Some(c) if c < sp => serde_json::json!({
                    "value": c,
                    "set_point": sp,
                    "metric": SignalMetric::TestCoverage.as_str(),
                }),
                _ => JsonValue::Null,
            }
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// `MutationScoreSensor` extracts `mutation_score` exactly when the
    /// reference says it should, for arbitrary `metrics.json` content.
    #[test]
    fn mutation_sensor_matches_reference_extraction(
        value in arb_json_value(),
        set_point in 0.0f64..1.0,
    ) {
        let dir = TempDir::new().expect("temp dir");
        let raw = serde_json::to_string(&value).unwrap_or_default();
        write_run_metrics(dir.path(), "run-1", &raw);

        let sensor = MutationScoreSensor::new(dir.path().to_path_buf(), set_point);
        let output_json = signal_to_json(block_on_sense(&sensor));

        let input_json = serde_json::json!({ "metrics": value, "set_point": set_point });
        let oracle = oracle_reference(|input: &JsonValue| -> JsonValue {
            let sp = input.get("set_point").and_then(|v| v.as_f64()).unwrap_or(0.0);
            let metrics = input.get("metrics").unwrap_or(&JsonValue::Null);
            match metrics.get("mutation_score").and_then(|f| f.as_f64()) {
                Some(c) if c < sp => serde_json::json!({
                    "value": c,
                    "set_point": sp,
                    "metric": SignalMetric::MutationScore.as_str(),
                }),
                _ => JsonValue::Null,
            }
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// Invariant: the sensor never panics on arbitrary content, and when it
    /// returns a signal the value is strictly below the set-point and the
    /// metric is `TestCoverage`.
    #[test]
    fn coverage_sensor_signal_invariants(
        value in arb_json_value(),
        set_point in 0.0f64..1.0,
    ) {
        let dir = TempDir::new().expect("temp dir");
        let raw = serde_json::to_string(&value).unwrap_or_default();
        write_run_metrics(dir.path(), "run-1", &raw);

        let sensor = TestCoverageSensor::new(dir.path().to_path_buf(), set_point);
        let output_json = signal_to_json(block_on_sense(&sensor));
        let input_json = serde_json::json!({ "set_point": set_point });

        let oracle = oracle_invariant(|input, output| {
            let sp = input.get("set_point").and_then(|v| v.as_f64()).unwrap_or(0.0);
            if output.is_null() {
                return Ok(());
            }
            let v = output.get("value").and_then(|x| x.as_f64()).unwrap_or(f64::INFINITY);
            let metric = output.get("metric").and_then(|x| x.as_str()).unwrap_or("");
            if v.partial_cmp(&sp) != Some(std::cmp::Ordering::Less) {
                return Err(format!("signal value {v} must be < set_point {sp}"));
            }
            if metric != SignalMetric::TestCoverage.as_str() {
                return Err(format!("metric {metric:?} != test_coverage"));
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// Invariant: when `MutationScoreSensor` returns a signal the value is
    /// strictly below the set-point and the metric is `mutation_score`.
    #[test]
    fn mutation_sensor_signal_invariants(
        value in arb_json_value(),
        set_point in 0.0f64..1.0,
    ) {
        let dir = TempDir::new().expect("temp dir");
        let raw = serde_json::to_string(&value).unwrap_or_default();
        write_run_metrics(dir.path(), "run-1", &raw);

        let sensor = MutationScoreSensor::new(dir.path().to_path_buf(), set_point);
        let output_json = signal_to_json(block_on_sense(&sensor));
        let input_json = serde_json::json!({ "set_point": set_point });

        let oracle = oracle_invariant(|input, output| {
            let sp = input.get("set_point").and_then(|v| v.as_f64()).unwrap_or(0.0);
            if output.is_null() {
                return Ok(());
            }
            let v = output.get("value").and_then(|x| x.as_f64()).unwrap_or(f64::INFINITY);
            let metric = output.get("metric").and_then(|x| x.as_str()).unwrap_or("");
            if v.partial_cmp(&sp) != Some(std::cmp::Ordering::Less) {
                return Err(format!("signal value {v} must be < set_point {sp}"));
            }
            if metric != SignalMetric::MutationScore.as_str() {
                return Err(format!("metric {metric:?} != mutation_score"));
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

// ── latest_metrics_path: most-recently-modified selection ──────────────────

#[test]
fn coverage_sensor_reads_most_recently_modified_metrics() {
    let dir = TempDir::new().expect("temp dir");
    write_run_metrics(dir.path(), "run-old", r#"{"coverage_pct": 0.2}"#);
    // Ensure a strictly newer mtime for run-new (filesystem resolution varies).
    std::thread::sleep(std::time::Duration::from_millis(20));
    write_run_metrics(dir.path(), "run-new", r#"{"coverage_pct": 0.5}"#);

    let sensor = TestCoverageSensor::new(dir.path().to_path_buf(), 0.9);
    let output_json = signal_to_json(block_on_sense(&sensor));
    let oracle = oracle_hardcoded(serde_json::json!({
        "value": 0.5,
        "set_point": 0.9,
        "metric": SignalMetric::TestCoverage.as_str(),
    }));
    assert_pass(&*oracle, &JsonValue::Null, &output_json);
}

#[test]
fn mutation_sensor_reads_most_recently_modified_metrics() {
    let dir = TempDir::new().expect("temp dir");
    write_run_metrics(dir.path(), "run-old", r#"{"mutation_score": 0.1}"#);
    std::thread::sleep(std::time::Duration::from_millis(20));
    write_run_metrics(dir.path(), "run-new", r#"{"mutation_score": 0.4}"#);

    let sensor = MutationScoreSensor::new(dir.path().to_path_buf(), 0.6);
    let output_json = signal_to_json(block_on_sense(&sensor));
    let oracle = oracle_hardcoded(serde_json::json!({
        "value": 0.4,
        "set_point": 0.6,
        "metric": SignalMetric::MutationScore.as_str(),
    }));
    assert_pass(&*oracle, &JsonValue::Null, &output_json);
}

// ── Graceful-degradation scenarios (None, not panic) ────────────────────────

/// Helper: assert the sensor returns `None` for a given `metrics.json` body
/// via an `oracle_hardcoded(Null)` oracle.
fn assert_none(body: &str, make_sensor: impl Fn(std::path::PathBuf) -> Box<dyn Sensor>) {
    let dir = TempDir::new().expect("temp dir");
    if !body.is_empty() {
        write_run_metrics(dir.path(), "run-1", body);
    }
    let sensor = make_sensor(dir.path().to_path_buf());
    let output_json = signal_to_json(block_on_sense(&*sensor));
    assert_pass(
        &*oracle_hardcoded(JsonValue::Null),
        &JsonValue::Null,
        &output_json,
    );
}

#[test]
fn coverage_sensor_missing_trace_dir_returns_none() {
    // No TempDir created at all → the path does not exist.
    let bogus = std::env::temp_dir().join(format!(
        "hkask-regulation-sensor-missing-{}-{}",
        std::process::id(),
        std::thread::current().name().unwrap_or("t").len()
    ));
    let _ = std::fs::remove_dir_all(&bogus);
    let sensor = TestCoverageSensor::new(bogus.clone(), 0.9);
    let output_json = signal_to_json(block_on_sense(&sensor));
    assert_pass(
        &*oracle_hardcoded(JsonValue::Null),
        &JsonValue::Null,
        &output_json,
    );
    let _ = std::fs::remove_dir_all(&bogus);
}

#[test]
fn coverage_sensor_empty_trace_dir_returns_none() {
    let dir = TempDir::new().expect("temp dir");
    // No run subdirs, no metrics.json.
    let sensor = TestCoverageSensor::new(dir.path().to_path_buf(), 0.9);
    let output_json = signal_to_json(block_on_sense(&sensor));
    assert_pass(
        &*oracle_hardcoded(JsonValue::Null),
        &JsonValue::Null,
        &output_json,
    );
}

#[test]
fn coverage_sensor_run_without_metrics_json_returns_none() {
    let dir = TempDir::new().expect("temp dir");
    let run_dir = dir.path().join("run-1");
    std::fs::create_dir_all(&run_dir).expect("create run dir");
    // A run dir exists but has no metrics.json.
    let sensor = TestCoverageSensor::new(dir.path().to_path_buf(), 0.9);
    let output_json = signal_to_json(block_on_sense(&sensor));
    assert_pass(
        &*oracle_hardcoded(JsonValue::Null),
        &JsonValue::Null,
        &output_json,
    );
}

#[test]
fn coverage_sensor_malformed_json_returns_none() {
    assert_none("{not valid json", |p| {
        Box::new(TestCoverageSensor::new(p, 0.9))
    });
}

#[test]
fn coverage_sensor_non_numeric_field_returns_none() {
    assert_none(r#"{"coverage_pct": "high"}"#, |p| {
        Box::new(TestCoverageSensor::new(p, 0.9))
    });
}

#[test]
fn coverage_sensor_field_absent_returns_none() {
    assert_none(r#"{"mutation_score": 0.8}"#, |p| {
        Box::new(TestCoverageSensor::new(p, 0.9))
    });
}

#[test]
fn coverage_sensor_at_or_above_set_point_returns_none() {
    // value == set_point → healthy → None.
    assert_none(r#"{"coverage_pct": 0.9}"#, |p| {
        Box::new(TestCoverageSensor::new(p, 0.9))
    });
    // value > set-point → healthy → None.
    assert_none(r#"{"coverage_pct": 0.99}"#, |p| {
        Box::new(TestCoverageSensor::new(p, 0.7))
    });
}

#[test]
fn mutation_sensor_malformed_json_returns_none() {
    assert_none("<<broken", |p| Box::new(MutationScoreSensor::new(p, 0.5)));
}

#[test]
fn mutation_sensor_field_absent_returns_none() {
    assert_none(r#"{"coverage_pct": 0.8}"#, |p| {
        Box::new(MutationScoreSensor::new(p, 0.5))
    });
}

#[test]
fn mutation_sensor_at_or_above_set_point_returns_none() {
    assert_none(r#"{"mutation_score": 0.5}"#, |p| {
        Box::new(MutationScoreSensor::new(p, 0.5))
    });
    assert_none(r#"{"mutation_score": 0.9}"#, |p| {
        Box::new(MutationScoreSensor::new(p, 0.4))
    });
}

// ── Positive extraction: exact value propagation ───────────────────────────

#[test]
fn coverage_sensor_returns_exact_value_below_set_point() {
    let dir = TempDir::new().expect("temp dir");
    write_run_metrics(dir.path(), "run-1", r#"{"coverage_pct": 0.42}"#);
    let sensor = TestCoverageSensor::new(dir.path().to_path_buf(), 0.7);
    let output_json = signal_to_json(block_on_sense(&sensor));
    let oracle = oracle_hardcoded(serde_json::json!({
        "value": 0.42,
        "set_point": 0.7,
        "metric": SignalMetric::TestCoverage.as_str(),
    }));
    assert_pass(&*oracle, &JsonValue::Null, &output_json);
}

#[test]
fn mutation_sensor_returns_exact_value_below_set_point() {
    let dir = TempDir::new().expect("temp dir");
    write_run_metrics(dir.path(), "run-1", r#"{"mutation_score": 0.33}"#);
    let sensor = MutationScoreSensor::new(dir.path().to_path_buf(), 0.5);
    let output_json = signal_to_json(block_on_sense(&sensor));
    let oracle = oracle_hardcoded(serde_json::json!({
        "value": 0.33,
        "set_point": 0.5,
        "metric": SignalMetric::MutationScore.as_str(),
    }));
    assert_pass(&*oracle, &JsonValue::Null, &output_json);
}
