//! Property tests for the JSON-field-extraction logic of the file-backed
//! regulation sensors (`TestCoverageSensor`, `MutationScoreSensor`).
//!
//! These tests replaced the deleted `mod tests` block in `sensor_provider.rs`
//! that used a `TestSensor` stub. They construct the *real* sensors pointed at
//! real temporary trace directories, write a real `metrics.json` whose content
//! is generated by `arb_json_value`, and call the real `Sensor::sense` method.
//!
//! Oracle taxonomy: an invariant oracle cross-checks that the sensor either
//! returns `None` gracefully (field absent, non-numeric, or value at/above the
//! set-point) or returns a `Signal` whose `value`/`set_point`/`metric`/`source`
//! exactly match an independent re-derivation of the expected value. The
//! sensors must never panic on arbitrary JSON content.

#![forbid(unsafe_code)]

use hkask_regulation::sensor_provider::{MutationScoreSensor, Sensor, TestCoverageSensor};
use hkask_regulation::types::loops::{Signal, SignalMetric};
use hkask_test_harness::{Oracle, OracleVerdict, arb_json_value, oracle_invariant};
use proptest::prelude::*;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};

/// Monotonic counter so each proptest case (and each parallel test function)
/// gets a unique trace directory under the system temp dir, avoiding any
/// cross-case file contention.
static DIR_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Create a fresh, empty trace directory for one sensor case. The caller is
/// responsible for removing it when done.
fn fresh_trace_dir(label: &str) -> PathBuf {
    let n = DIR_COUNTER.fetch_add(1, Ordering::Relaxed);
    let dir = std::env::temp_dir().join(format!(
        "hkask-sensor-prop-{label}-{}-{n}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    dir
}

/// Write `metrics.json` into a single run subdirectory of `trace_dir`.
fn write_metrics(trace_dir: &std::path::Path, json: &serde_json::Value) {
    std::fs::create_dir_all(trace_dir.join("run-1")).expect("create run dir");
    std::fs::write(
        trace_dir.join("run-1").join("metrics.json"),
        json.to_string(),
    )
    .expect("write metrics.json");
}

/// Float equality tolerant of Ryu round-trip noise; exact for the values
/// produced by `arb_json_value` (finite f64 / i64 / u64), but guarded so a
/// future serialization change surfaces as a small drift rather than flakiness.
fn approx_eq(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-9 * (1.0 + a.abs().max(b.abs()))
}

/// Shared invariant: given the metrics JSON and the set-point, verify the
/// sensor either returns `None` or a correctly-populated `Signal`.
fn field_extraction_oracle(field: &'static str, metric: SignalMetric) -> Box<dyn Oracle> {
    oracle_invariant(move |input, output| {
        let json = &input["json"];
        let set_point = input["set_point"].as_f64().ok_or("set_point not f64")?;
        let expected_coverage = json.get(field).and_then(|v| v.as_f64());
        let expected_signal_value = expected_coverage.filter(|&c| c < set_point);

        let has_signal = output["has_signal"]
            .as_bool()
            .ok_or("has_signal not bool")?;
        match (has_signal, expected_signal_value) {
            (false, None) => Ok(()),
            (true, Some(expected)) => {
                let value = output["value"].as_f64().ok_or("value not f64")?;
                let sig_set_point = output["set_point"].as_f64().ok_or("set_point not f64")?;
                let got_metric = output["metric"].as_str().ok_or("metric not str")?;
                let got_source = output["source"].as_str().ok_or("source not str")?;
                if !approx_eq(value, expected) {
                    return Err(format!("value {value} != expected {expected}"));
                }
                if !approx_eq(sig_set_point, set_point) {
                    return Err(format!("set_point {sig_set_point} != {set_point}"));
                }
                if got_metric != metric.as_str() {
                    return Err(format!("metric {got_metric} != {}", metric.as_str()));
                }
                if got_source != "cybernetics" {
                    return Err(format!("source {got_source} != cybernetics"));
                }
                Ok(())
            }
            (false, Some(expected)) => Err(format!(
                "expected Some({expected}) (field present, {expected} < {set_point}) but sensor returned None"
            )),
            (true, None) => Err(format!(
                "sensor returned Some but expected None (field absent/non-numeric, or >= {set_point})"
            )),
        }
    })
}

/// Encode a `sense` outcome as the JSON consumed by the oracle's `output`.
fn encode_signal(signal: Option<Signal>) -> serde_json::Value {
    match signal {
        None => serde_json::json!({ "has_signal": false }),
        Some(s) => serde_json::json!({
            "has_signal": true,
            "value": s.value,
            "set_point": s.set_point,
            "metric": s.metric.as_str(),
            "source": s.source.to_string(),
        }),
    }
}

/// Drive a sensor's async `sense` on a dedicated single-threaded runtime from a
/// synchronous proptest body. `block_on` is reentrant-safe here because the
/// proptest body runs on a plain OS thread with no ambient async context.
fn block_sense<S: Sensor + ?Sized>(
    runtime: &tokio::runtime::Runtime,
    sensor: &S,
) -> Option<Signal> {
    runtime.block_on(async { sensor.sense().await })
}

proptest! {
    /// `TestCoverageSensor` extracts `coverage_pct` from the newest run's
    /// `metrics.json`. It must return `None` (not panic, not a default signal)
    /// when the field is absent or non-numeric, or when coverage is at/above
    /// the set-point; otherwise it emits a `TestCoverage` signal on the
    /// Cybernetics loop carrying the exact coverage value and set-point.
    #[test]
    fn prop_test_coverage_sensor_extracts_field(
        json in arb_json_value(),
        set_point in 0.0f64..=100.0,
    ) {
        let runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("build runtime");

        let dir = fresh_trace_dir("coverage");
        write_metrics(&dir, &json);

        let sensor = TestCoverageSensor::new(dir.clone(), set_point);
        let signal = block_sense(&runtime, &sensor);
        let produced = encode_signal(signal);
        let input = serde_json::json!({ "json": json, "set_point": set_point });

        let oracle = field_extraction_oracle("coverage_pct", SignalMetric::TestCoverage);
        prop_assert_eq!(oracle.verify(&input, &produced), OracleVerdict::Pass);

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// `MutationScoreSensor` mirrors the coverage sensor over the
    /// `mutation_score` field with the `MutationScore` metric.
    #[test]
    fn prop_mutation_score_sensor_extracts_field(
        json in arb_json_value(),
        set_point in 0.0f64..=1.0,
    ) {
        let runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("build runtime");

        let dir = fresh_trace_dir("mutation");
        write_metrics(&dir, &json);

        let sensor = MutationScoreSensor::new(dir.clone(), set_point);
        let signal = block_sense(&runtime, &sensor);
        let produced = encode_signal(signal);
        let input = serde_json::json!({ "json": json, "set_point": set_point });

        let oracle = field_extraction_oracle("mutation_score", SignalMetric::MutationScore);
        prop_assert_eq!(oracle.verify(&input, &produced), OracleVerdict::Pass);

        let _ = std::fs::remove_dir_all(&dir);
    }
}

proptest! {
    /// `latest_metrics_path` is private, but its absence contract is observable
    /// through `sense`: a trace directory with no run subdirectories (and thus
    /// no `metrics.json`) must yield `None`, never a panic, never a fabricated
    /// signal. This pins the "absent field → None, not default" invariant at the
    /// directory level (not just the JSON-field level).
    #[test]
    fn prop_sense_none_when_no_metrics_file(set_point in 0.0f64..=100.0) {
        let runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("build runtime");

        let dir = fresh_trace_dir("empty");
        std::fs::create_dir_all(&dir).expect("create trace dir");

        let coverage = TestCoverageSensor::new(dir.clone(), set_point);
        let mutation = MutationScoreSensor::new(dir.clone(), set_point);

        let cov_signal = block_sense(&runtime, &coverage);
        let mut_signal = block_sense(&runtime, &mutation);

        prop_assert!(cov_signal.is_none(), "coverage sensor produced a signal from an empty trace dir");
        prop_assert!(mut_signal.is_none(), "mutation sensor produced a signal from an empty trace dir");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A `metrics.json` whose root is not a JSON object (array/string/null) has
    /// no `coverage_pct`/`mutation_score` field, so both sensors must return
    /// `None` without panicking. This exercises the `value.get(...)` path on
    /// non-object roots.
    #[test]
    fn prop_sense_none_when_root_not_object(
        non_object in prop_oneof![
            Just(serde_json::Value::Null),
            any::<bool>().prop_map(serde_json::Value::Bool),
            any::<i64>().prop_map(|n| serde_json::json!(n)),
            any::<String>().prop_map(serde_json::Value::String),
            prop::collection::vec(arb_json_value(), 0..4).prop_map(serde_json::Value::Array),
        ],
        set_point in 0.0f64..=100.0,
    ) {
        let runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("build runtime");

        let dir = fresh_trace_dir("nonobj");
        write_metrics(&dir, &non_object);

        let coverage = TestCoverageSensor::new(dir.clone(), set_point);
        let mutation = MutationScoreSensor::new(dir.clone(), set_point);

        let cov_signal = block_sense(&runtime, &coverage);
        let mut_signal = block_sense(&runtime, &mutation);

        prop_assert!(cov_signal.is_none(), "coverage sensor found a field on a non-object root");
        prop_assert!(mut_signal.is_none(), "mutation sensor found a field on a non-object root");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
