//! Matrix command handlers for `kask matrix`
//!
//! Implements sidecar deployment, agent/user registration, sync listener,
//! and health checks for the Matrix integration.

use crate::cli::MatrixAction;
use crate::error::CliError;
use std::path::{Path, PathBuf};

/// pre:  action is a valid MatrixAction variant
/// post: dispatches to deploy_sidecar, register_agent, register_user, or status_sidecar
pub fn run(action: MatrixAction) {
    match action {
        MatrixAction::DeploySidecar {
            domain,
            with_web_client,
            output,
        } => run_deploy_sidecar(&domain, with_web_client, output),
        MatrixAction::RegisterAgent { agent, homeserver } => {
            run_register_agent(&agent, &homeserver)
        }
        MatrixAction::RegisterUser { user, homeserver } => run_register_user(&user, &homeserver),
        MatrixAction::StatusSidecar => run_status_sidecar(),
    }
}

// ── deploy-sidecar ────────────────────────────────────────────────────────

fn run_deploy_sidecar(domain: &str, with_web_client: bool, output: Option<PathBuf>) {
    let output_dir = output.unwrap_or_else(|| {
        let mut path = dirs::config_local_dir().unwrap_or_else(|| PathBuf::from("."));
        path.push("hkask");
        path.push("sidecar");
        path
    });

    if let Err(e) = std::fs::create_dir_all(&output_dir) {
        eprintln!(
            "Failed to create output directory {}: {}",
            output_dir.display(),
            e
        );
        std::process::exit(1);
    }

    // Generate random admin token (64 hex chars)
    let admin_token = generate_admin_token();

    // ── docker-compose.yml ──
    let compose = format!(
        r#"# Generated by: kask matrix deploy-sidecar --domain {domain}
# Location: {output_dir}/docker-compose.yml

version: "3.8"
services:
  # ── TLS reverse proxy (auto-Let's Encrypt) ──
  caddy:
    image: caddy:2-alpine
    container_name: hkask-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data
    networks:
      - hkask-sidecar

  # ── Matrix homeserver ──
  conduit:
    image: registry.gitlab.com/famedly/conduit:0.9.0
    container_name: hkask-conduit
    restart: unless-stopped
    expose:
      - "8008"
    volumes:
      - ./conduit-data:/var/lib/conduit
      - ./conduit.toml:/etc/conduit/conduit.toml:ro
    environment:
      - CONDUIT_CONFIG=/etc/conduit/conduit.toml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/_matrix/client/versions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - hkask-sidecar
{hydrogen_service}
networks:
  hkask-sidecar:
    driver: bridge
"#,
        domain = domain,
        output_dir = output_dir.display(),
        hydrogen_service = if with_web_client {
            r#"
  # ── Optional lightweight web client ──
  hydrogen:
    image: element-hq/hydrogen-web:latest
    container_name: hkask-hydrogen
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./hydrogen-config.json:/app/config.json:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - hkask-sidecar
    profiles:
      - with-web-client
"#
            .to_string()
        } else {
            String::new()
        }
    );

    // ── Caddyfile ──
    let caddyfile = format!(
        r#"# Generated by: kask matrix deploy-sidecar --domain {domain}
{domain} {{
    # Matrix client API + .well-known delegation
    reverse_proxy /_matrix/* conduit:8008
    reverse_proxy /_well-known/* conduit:8008
{hydrogen_route}
}}
"#,
        domain = domain,
        hydrogen_route = if with_web_client {
            "    # Hydrogen web client\n    reverse_proxy /* hydrogen:80\n"
        } else {
            "    # No web client — Matrix API only\n    respond /* 404\n"
        }
    );

    // ── conduit.toml ──
    let conduit_toml = format!(
        r#"# Generated by: kask matrix deploy-sidecar --domain {domain}
server_name = "{domain}"
allow_registration = true
admin_token = "{admin_token}"
well_known_client = "https://{domain}"
max_request_size = 20_000_000
db_path = "/var/lib/conduit/conduit.db"
log_level = "info"
port = 8008
address = "0.0.0.0"
"#,
        domain = domain,
        admin_token = admin_token,
    );

    // ── hydrogen-config.json (if enabled) ──
    let hydrogen_config = if with_web_client {
        Some(format!(
            r#"{{ "default_homeserver": "https://{domain}" }}
"#,
            domain = domain
        ))
    } else {
        None
    };

    // ── Write files ──
    write_file(&output_dir, "docker-compose.yml", &compose);
    write_file(&output_dir, "Caddyfile", &caddyfile);
    write_file(&output_dir, "conduit.toml", &conduit_toml);
    if let Some(config) = &hydrogen_config {
        write_file(&output_dir, "hydrogen-config.json", config);
    }

    // ── Store admin token in keystore ──
    let keychain = hkask_keystore::Keychain::default();
    if let Err(e) = keychain.store_by_key(
        hkask_types::keychain_keys::KEY_MATRIX_ADMIN_TOKEN,
        &admin_token,
    ) {
        eprintln!("Warning: Failed to store admin token in keychain: {}", e);
        eprintln!(
            "The admin token is in {}/conduit.toml — keep it secure.",
            output_dir.display()
        );
    }

    // ── Summary ──
    println!();
    println!("  Sidecar files generated in {}", output_dir.display());
    println!();
    println!("  Files:");
    println!(
        "    docker-compose.yml   — Caddy + Conduit{}",
        if with_web_client { " + Hydrogen" } else { "" }
    );
    println!("    Caddyfile            — Auto-TLS reverse proxy config");
    println!("    conduit.toml         — Homeserver configuration");
    if with_web_client {
        println!("    hydrogen-config.json — Web client configuration");
    }
    println!();
    println!("  Admin token stored in OS keychain as HKASK_MATRIX_ADMIN_TOKEN.");
    println!();
    println!("  Next steps:");
    println!(
        "    1. Ensure DNS A record for {} points to this server",
        domain
    );
    println!("    2. cd {} && docker compose up -d", output_dir.display());
    println!("    3. Wait ~30s for Caddy to obtain Let's Encrypt certificate");
    println!("    4. kask matrix status-sidecar  (verify health)");
    println!("    5. kask matrix register --agent <name>  (register your userpod)");
    println!();
}

// ── register-agent ─────────────────────────────────────────────────────────

fn run_register_agent(agent: &str, homeserver: &str) {
    // 1. Read admin token from keystore
    let keychain = hkask_keystore::Keychain::default();
    let admin_token =
        match keychain.retrieve_by_key(hkask_types::keychain_keys::KEY_MATRIX_ADMIN_TOKEN) {
            Ok(t) => t,
            Err(_) => {
                eprintln!("  No admin token found. Run 'kask matrix deploy-sidecar' first.");
                std::process::exit(1);
            }
        };

    // 2. Prompt for userpod credential (no AI — direct human input)
    println!();
    println!("  ═══════════════════════════════════════════════════════════");
    println!("  Agent Registration — Identity Verification");
    println!("  ═══════════════════════════════════════════════════════════");
    println!();
    println!("  UserPod: {}", agent);
    println!("  Homeserver: {}", homeserver);
    println!();
    println!("  Enter the full userpod credential to authorize");
    println!("  Matrix registration for this agent.");
    println!();
    println!("  Format: FirstName-LastName/Passphrase");
    println!("  Example: Alice-Smith/mysecret");
    println!();

    let credential = rpassword::prompt_password("  Credential: ").unwrap_or_default();

    if credential.is_empty() {
        println!("  Aborted — no credential entered.");
        return;
    }

    // 3. Verify credential format
    // Full credential-hash verification requires the onboarding credential
    // hash infrastructure (not yet implemented). We check the expected
    // FirstName-LastName/Passphrase format and proceed with a warning for
    // non-standard formats (API keys, tokens, etc.).
    if !credential.contains('/') {
        println!();
        println!("  ⚠️  Credential format: expected FirstName-LastName/Passphrase");
        println!("  The credential does not match the expected format. If you are");
        println!("  using an API key or token, this is expected — proceeding.");
        println!();
    }

    // 4. Derive MXID from userpod name
    let mxid = derive_mxid(agent, homeserver);
    let password = generate_password();

    println!();
    println!("  Deriving Matrix identity...");
    println!("  MXID: {}", mxid);
    println!();

    // 5. Register on Conduit via admin API
    match call_conduit_admin_register(homeserver, &admin_token, agent, &password) {
        Ok(()) => {
            println!("  ✓ Agent registered on Matrix homeserver");
        }
        Err(e) => {
            eprintln!("  ✗ Registration failed: {}", e);
            eprintln!("  Check that Conduit is running and the admin token is correct.");
            std::process::exit(1);
        }
    }

    // 6. Store agent Matrix credentials in keystore
    let _ = keychain.store_by_key(
        &format!(
            "{}{}",
            hkask_types::keychain_keys::KEY_MATRIX_AGENT_USERNAME_PREFIX,
            agent
        ),
        &mxid,
    );
    let _ = keychain.store_by_key(
        &format!(
            "{}{}",
            hkask_types::keychain_keys::KEY_MATRIX_AGENT_PASSWORD_PREFIX,
            agent
        ),
        &password,
    );

    // 7. Output labeled QR code placeholder
    // Full SAS QR code generation requires matrix-sdk crypto (deferred to v2).
    // For v1, output the verification instructions for manual SAS.
    println!();
    println!("  ═══════════════════════════════════════════════════════════");
    println!("  Device Verification — Share with the human user");
    println!("  ═══════════════════════════════════════════════════════════");
    println!();
    println!("  UserPod: {}", agent);
    println!("  Matrix:    {}", mxid);
    println!();
    println!("  The human user should:");
    println!("  1. Open FluffyChat and log into {}", homeserver);
    println!("  2. Search for {}", mxid);
    println!("  3. Start a DM — FluffyChat will prompt for device verification");
    println!("  4. Compare the emoji string shown in FluffyChat with the");
    println!("     emoji string shown by the agent (SAS verification)");
    println!();
    println!("  Agent credentials stored in OS keychain:");
    println!("    HKASK_MATRIX_AGENT_USERNAME_{}", agent);
    println!("    HKASK_MATRIX_AGENT_PASSWORD_{}", agent);
    println!();
    println!("  Next step: kask matrix listen --agent {}", agent);
    println!();
}

// ── register-user ──────────────────────────────────────────────────────────

fn run_register_user(user: &str, homeserver: &str) {
    // 1. Try to read admin token from keystore (may not exist in dev mode)
    let keychain = hkask_keystore::Keychain::default();
    let admin_token = keychain
        .retrieve_by_key(hkask_types::keychain_keys::KEY_MATRIX_ADMIN_TOKEN)
        .unwrap_or_default();

    // 2. Derive MXID and generate password
    let mxid = derive_mxid(user, homeserver);
    let password = generate_password();

    println!();
    println!("  Creating Matrix user...");
    println!("  Username: {}", user);
    println!("  MXID:     {}", mxid);
    println!();

    // 3. Register on Conduit (tries admin API, then registration token)
    match call_conduit_admin_register(homeserver, &admin_token, user, &password) {
        Ok(()) => {
            println!("  \u{2713} User created on Matrix homeserver");
        }
        Err(e) => {
            eprintln!("  \u{2717} Registration failed: {}", e);
            eprintln!("  Check that Conduit is running and registration is enabled.");
            eprintln!("  If open registration is enabled, the user can also create");
            eprintln!("  their account directly in FluffyChat.");
            std::process::exit(1);
        }
    }

    // 4. Output credentials with connection instructions
    println!();
    println!("  ═══════════════════════════════════════════════════════════");
    println!("  Human User Credentials — Share securely");
    println!("  ═══════════════════════════════════════════════════════════");
    println!();
    println!("  Homeserver: {}", homeserver);
    println!("  MXID:       {}", mxid);
    println!("  Password:   {}", password);
    println!();
    println!("  Share these with the human user through a secure channel");
    println!("  (in person, Signal, or an existing encrypted DM).");
    println!();
    println!("  The human user then:");
    println!("  1. Installs a Matrix client:");
    println!("     Mobile:  FluffyChat or Element X");
    println!("     Desktop: Element or FluffyChat");
    println!("     (any Matrix-compliant client works)");
    println!("  2. Selects 'Use custom server' → {}", homeserver);
    println!("  3. Logs in with the MXID and password above");
    println!("  4. Searches for their agent and starts a DM");
    println!();
}

// ── status-sidecar ─────────────────────────────────────────────────────────

fn run_status_sidecar() {
    let sidecar_dir = {
        let mut path = dirs::config_local_dir().unwrap_or_else(|| PathBuf::from("."));
        path.push("hkask");
        path.push("sidecar");
        path
    };

    if !sidecar_dir.exists() {
        println!("  Sidecar not deployed. Run: kask matrix deploy-sidecar --domain <domain>");
        return;
    }

    println!("  Checking sidecar health...");
    println!();

    // Check Docker containers
    let compose_file = sidecar_dir.join("docker-compose.yml");
    let ps_output = std::process::Command::new("docker")
        .args(["compose", "-f"])
        .arg(compose_file.to_string_lossy().as_ref())
        .args(["ps", "--format", "json"])
        .output();

    match ps_output {
        Ok(output) if output.status.success() => {
            let stdout = String::from_utf8_lossy(&output.stdout);
            if stdout.trim().is_empty() {
                println!("  No containers running. Start with: docker compose up -d");
            } else {
                // Parse JSON lines for container status
                for line in stdout.lines() {
                    if let Ok(parsed) = serde_json::from_str::<serde_json::Value>(line) {
                        let name = parsed["Name"].as_str().unwrap_or("unknown");
                        let state = parsed["State"].as_str().unwrap_or("unknown");
                        let status = parsed["Status"].as_str().unwrap_or("");
                        let icon = if state == "running" { "✓" } else { "✗" };
                        println!("  {} {}: {} ({})", icon, name, state, status);
                    }
                }
            }
        }
        Ok(_) => println!("  docker compose ps failed — check Docker installation."),
        Err(e) => println!("  Cannot check Docker: {} — is Docker installed?", e),
    }

    println!();
    println!("  For full health check (API + database integrity), use:");
    println!("    curl http://localhost:8008/_matrix/client/versions");
    println!("    sqlite3 <conduit-data>/conduit.db \"PRAGMA integrity_check\"");
}

// ── helpers ────────────────────────────────────────────────────────────────

fn generate_admin_token() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    hex::encode(bytes)
}

fn generate_password() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 16];
    rand::rng().fill_bytes(&mut bytes);
    hex::encode(bytes)
}

/// Derive a Matrix MXID from a userpod name and homeserver domain.
///
/// Rules (per spec §2.3, Gap B2):
/// 1. Lowercase the full name
/// 2. Replace spaces with hyphens
/// 3. Strip any character not in `[a-z0-9-._=]`
/// 4. If empty after stripping, use `agent-{random-8-hex}`
fn derive_mxid(name: &str, homeserver: &str) -> String {
    let domain = homeserver
        .trim_start_matches("http://")
        .trim_start_matches("https://")
        .split(':')
        .next()
        .unwrap_or("localhost");

    let localpart: String = name
        .to_lowercase()
        .chars()
        .map(|c| if c == ' ' { '-' } else { c })
        .filter(|c| matches!(c, 'a'..='z' | '0'..='9' | '-' | '.' | '_' | '='))
        .collect();

    let localpart = if localpart.is_empty() {
        use rand::RngCore;
        let mut bytes = [0u8; 4];
        rand::rng().fill_bytes(&mut bytes);
        format!("agent-{}", hex::encode(bytes))
    } else {
        localpart
    };

    format!("@{}:{}", localpart, domain)
}

/// Call Conduit's admin API to register a new user.
///
/// Uses `POST /_conduit/admin/register` with the admin token.
/// Falls back to the standard Matrix registration API if the admin
/// endpoint is not available (e.g., on non-Conduit homeservers).
fn call_conduit_admin_register(
    homeserver: &str,
    admin_token: &str,
    username: &str,
    password: &str,
) -> Result<(), CliError> {
    let localpart = derive_mxid(username, homeserver)
        .trim_start_matches('@')
        .split(':')
        .next()
        .unwrap_or(username)
        .to_string();

    let handle = tokio::runtime::Handle::current();

    handle.block_on(async {
        let client = reqwest::Client::new();

        // Try Conduit-specific admin endpoint first
        let admin_url = format!(
            "{}/_conduit/admin/register",
            homeserver.trim_end_matches('/')
        );
        let body = serde_json::json!({
            "username": localpart,
            "password": password,
            "device_display_name": format!("hKask Agent {}", username),
        });

        let response = client
            .post(&admin_url)
            .header("Authorization", format!("Bearer {}", admin_token))
            .json(&body)
            .send()
            .await
            .map_err(|e| CliError::Matrix(format!("HTTP request failed: {}", e)))?;

        if response.status().is_success() {
            return Ok(());
        }

        // Fallback 1: try standard Matrix registration API with admin token
        let register_url = format!(
            "{}/_matrix/client/v3/register",
            homeserver.trim_end_matches('/')
        );
        let body = serde_json::json!({
            "username": localpart,
            "password": password,
            "initial_device_display_name": format!("hKask Agent {}", username),
            "admin_token": admin_token,
        });

        let response = client
            .post(&register_url)
            .json(&body)
            .send()
            .await
            .map_err(|e| CliError::Matrix(format!("HTTP request failed: {}", e)))?;

        if response.status().is_success() {
            return Ok(());
        }

        // Fallback 2: try registration token (hkask-dev mode)
        let reg_token = std::env::var("HKASK_MATRIX_REGISTRATION_TOKEN")
            .unwrap_or_else(|_| "hkask-dev".to_string());
        let body = serde_json::json!({
            "username": localpart,
            "password": password,
            "initial_device_display_name": format!("hKask Agent {}", username),
            "auth": {"type": "m.login.registration_token", "token": reg_token},
        });

        let response = client
            .post(&register_url)
            .json(&body)
            .send()
            .await
            .map_err(|e| CliError::Matrix(format!("HTTP request failed: {}", e)))?;

        let status = response.status();
        let body_text = response
            .text()
            .await
            .unwrap_or_else(|_| "(no body)".to_string());

        if status.is_success() {
            Ok(())
        } else {
            Err(CliError::Matrix(format!(
                "Server returned {} {}: {}",
                status.as_u16(),
                status.canonical_reason().unwrap_or("Unknown"),
                body_text
            )))
        }
    })
}

fn write_file(dir: &Path, name: &str, content: &str) {
    let path = dir.join(name);
    match std::fs::write(&path, content) {
        Ok(()) => println!("  ✓ wrote {}", name),
        Err(e) => {
            eprintln!("  ✗ failed to write {}: {}", name, e);
            std::process::exit(1);
        }
    }
}
