#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! hkask-mcp-evolution — the experiment registry for the sharded evolution
//! program (repair plan §P8).
//!
//! One server owns the durable record of evolution experiments across the
//! six artifact layers (§P8.3): registered experiments with pre-registered
//! Brier-scored predictions, variant lineages, grounded fitness records
//! (recorded report refs only — never simulated), and selection fossils
//! (selected and rejected both retained, §P8.7-Q4). The registry is the only
//! record path from day one (§P8.7-Q5 — no backward compatibility, no
//! legacy-import surface).

pub mod server;
pub mod store;
pub mod types;

// ── Canonical tool-name list ─────────────────────────────────────────────
//
// Generated by `build.rs` from the six designed `pub async fn` signatures in
// `src/*.rs` (§P8.4). The `tool_names_match_live_router` test pins the
// generated list against the live router.
include!(concat!(env!("OUT_DIR"), "/tool_names.gen.rs"));

pub use server::run;

#[cfg(test)]
mod tool_name_pin {
    // Pins the generated TOOL_NAMES const against the live rmcp tool surface —
    // a tool added/renamed fails here instead of degrading to "tool not found"
    // at dispatch.
    #[test]
    fn tool_names_match_live_router() {
        let mut live: Vec<String> = crate::server::EvolutionServer::evolution_router()
            .list_all()
            .iter()
            .map(|tool| tool.name.to_string())
            .collect();
        live.sort();
        let generated: Vec<&str> = crate::TOOL_NAMES.to_vec();
        assert_eq!(
            generated,
            live.iter().map(String::as_str).collect::<Vec<_>>(),
            "TOOL_NAMES (build.rs-generated) must match the live evolution_router surface"
        );
    }
}
