//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/*.rs` for `pub async fn portfolio_<name>` / `pub async fn
//! ledger_<name>` and emits a `pub const TOOL_NAMES: &[&str]`. Mirrors
//! `hkask-mcp-kata-kanban/build.rs`. The `tool_names_match_live_router` test
//! in `hkask_mcp_portfolio.rs` pins the generated list against the live
//! `portfolio_router().list_all()` surface.

#[path = "../../crates/hkask-mcp-server/build_support/tool_names.rs"]
mod tool_names;

use std::collections::BTreeSet;
use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    // All tool fns follow `pub async fn portfolio_*(` or `pub async fn ledger_*(`.
    let pattern =
        regex::Regex::new(r"pub async fn ((?:portfolio|ledger)_\w+)\s*\(").expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    for source in tool_names::rust_sources(&src_dir, false) {
        for caps in pattern.captures_iter(&source) {
            names.insert(caps[1].to_string());
        }
    }

    let entries = tool_names::entries(&names);
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/*.rs` for `pub async fn portfolio_*`/`ledger_*` signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n"
    );

    tool_names::write_if_changed(&out_path, &generated, &src_dir);
}
