//! Skill loader — discovers, parses, and registers SKILL.md files from both zones
//!
//! Two-zone model (src→dist pattern):
//! - **Private zone** (`.agents/skills/`) — source of truth, author's working copies
//! - **Public zone** (`skills/`) — export surface, generated by `kask skill publish`
//!
//! The loader scans both zones, parses YAML front matter from each SKILL.md,
//! validates zone-vs-visibility consistency, and registers skills into a
//! `SkillRegistryIndex`. Zone-vs-visibility mismatches emit a warning but
//! do not block registration — the `visibility` field in SKILL.md wins.

use hkask_types::template_type::TemplateType;
use hkask_types::visibility::Visibility;
use hkask_types::{Skill, SkillRegistryIndex, SkillZone};
use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};
use tracing;

use crate::ports::{FsSkillReader, Result, SkillReader, TemplateError};

/// Parsed SKILL.md front matter.
///
/// Uses `deny_unknown_fields` to catch typos (e.g. `visibilty` instead of
/// `visibility`) at parse time rather than silently dropping them.
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SkillFrontMatter {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub visibility: Option<String>,
    #[serde(default)]
    pub namespace: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
}

/// Minimal manifest shape used to infer a skill's domain from its registry layer.
#[derive(Debug, Default, Deserialize)]
struct SkillManifest {
    #[serde(default)]
    templates: Vec<ManifestTemplateEntry>,
}

#[derive(Debug, Default, Deserialize)]
struct ManifestTemplateEntry {
    #[serde(default)]
    path: String,
    #[serde(default)]
    #[serde(rename = "type")]
    template_type: String,
}

/// Result of loading skills from both zones.
#[derive(Debug)]
pub struct SkillLoadResult {
    pub loaded: Vec<Skill>,
    pub warnings: Vec<String>,
}

/// Skill loader — discovers SKILL.md files from both zones, parses front matter,
/// validates zone-vs-visibility consistency, and registers skills.
pub struct SkillLoader {
    /// Root directory for skill discovery (typically the project root).
    project_root: PathBuf,
    /// Injected filesystem reader (purity seam). Production uses
    /// `FsSkillReader`; tests inject a mock. Defaults to `FsSkillReader`.
    reader: Box<dyn SkillReader>,
}

impl SkillLoader {
    /// Create a new skill loader rooted at `project_root` with the production
    /// filesystem reader.
    ///
    /// expect: "The system loads skills into the template registry"
    /// \[P3\] Motivating: Generative Space — loader for skill registry entries
    /// pre:  project_root is a valid directory path
    /// post: returns SkillLoader configured for the given root
    pub fn new(project_root: impl Into<PathBuf>) -> Self {
        Self {
            project_root: project_root.into(),
            reader: Box::new(FsSkillReader),
        }
    }

    /// Create a new skill loader with an injected reader (test seam).
    ///
    /// expect: "The system loads skills into the template registry"
    /// \[P3\] Motivating: Generative Space — testable loader with injected I/O
    /// pre:  project_root is a valid directory path, reader implements SkillReader
    /// post: returns SkillLoader configured for the given root and reader
    pub fn with_reader(project_root: impl Into<PathBuf>, reader: Box<dyn SkillReader>) -> Self {
        Self {
            project_root: project_root.into(),
            reader,
        }
    }

    /// Discover and load skills from both zones, registering them into the registry.
    ///
    /// expect: "The system loads skills into the template registry"
    /// \[P3\] Motivating: Generative Space — loads skill into registry
    /// pre:  registry is initialized
    /// post: skills from private and public zones loaded and registered
    /// post: returns SkillLoadResult with loaded skills and any warnings
    pub fn load_into(&self, registry: &mut dyn SkillRegistryIndex) -> SkillLoadResult {
        let mut result = SkillLoadResult {
            loaded: Vec::new(),
            warnings: Vec::new(),
        };

        // Scan private zone first (source of truth), then public zone (export surface).
        for zone in [SkillZone::Private, SkillZone::Public] {
            let zone_dir = self.project_root.join(zone.directory());
            if !zone_dir.exists() {
                continue;
            }

            let discovered = match Self::discover_skills(&zone_dir) {
                Ok(skills) => skills,
                Err(e) => {
                    result.warnings.push(format!(
                        "Failed to scan {} zone at {}: {}",
                        zone.as_str(),
                        zone_dir.display(),
                        e
                    ));
                    continue;
                }
            };

            for skill_dir in discovered {
                match self.load_skill(&skill_dir, zone) {
                    Ok(skill) => {
                        // P9: Regulation span — skill activation
                        tracing::info!(
                            target: "reg.skill.lifecycle",
                            operation = "skill_activated",
                            skill_id = %skill.id,
                            domain = %skill.domain,
                            visibility = ?skill.visibility,
                            zone = %zone.as_str(),
                            "REG"
                        );
                        // Validate zone-vs-visibility consistency.
                        if let Some(warning) = Self::check_zone_visibility(&skill, zone) {
                            result.warnings.push(warning);
                        }
                        if let Err(e) = registry.register_skill(skill.clone()) {
                            result
                                .warnings
                                .push(format!("Failed to register skill '{}': {}", skill.id, e));
                        }
                        result.loaded.push(skill);
                    }
                    Err(e) => {
                        result.warnings.push(format!(
                            "Failed to load skill from {}: {}",
                            skill_dir.display(),
                            e
                        ));
                    }
                }
            }
        }

        // P9: Regulation span — skills loaded summary
        tracing::info!(
            target: "reg.skill.lifecycle",
            operation = "skills_loaded",
            loaded = result.loaded.len(),
            warnings = result.warnings.len(),
            "REG"
        );

        result
    }

    /// Discover skill directories within a zone directory.
    /// A skill directory is any directory containing a `SKILL.md` file.
    fn discover_skills(zone_dir: &Path) -> Result<Vec<PathBuf>> {
        let mut skill_dirs = Vec::new();
        let entries = fs::read_dir(zone_dir).map_err(|e| TemplateError::SkillLoad {
            path: zone_dir.display().to_string(),
            source: e,
        })?;

        for entry in entries {
            let entry = entry.map_err(|e| TemplateError::SkillLoad {
                path: zone_dir.display().to_string(),
                source: e,
            })?;
            let path = entry.path();
            if path.is_dir() && path.join("SKILL.md").exists() {
                skill_dirs.push(path);
            }
        }

        skill_dirs.sort();
        Ok(skill_dirs)
    }

    /// Load a single skill from its directory.
    fn load_skill(&self, skill_dir: &Path, zone: SkillZone) -> Result<Skill> {
        let skill_md_path = skill_dir.join("SKILL.md");
        let content =
            self.reader
                .read_to_string(&skill_md_path)
                .map_err(|e| TemplateError::SkillLoad {
                    path: skill_md_path.display().to_string(),
                    source: e,
                })?;

        let front_matter = Self::parse_front_matter(&content)?;

        // Derive ID and namespace from directory name + zone.
        //
        // In the public zone, directory names are `<namespace>--<id>` (e.g. "alice--diagnose").
        // In the private zone, directory names are just `<id>` (no namespace).
        let dir_name = skill_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&front_matter.name);

        let (namespace_from_dir, id_from_dir) = match zone {
            SkillZone::Public => Skill::parse_qualified_id(dir_name)
                .unwrap_or_else(|| (String::new(), dir_name.to_string())),
            SkillZone::Private => (String::new(), dir_name.to_string()),
        };

        // Front matter namespace wins over directory-inferred namespace.
        // Directory structure is the fallback for skills published before
        // namespace was added to SKILL.md.
        let namespace = front_matter.namespace.or({
            if namespace_from_dir.is_empty() {
                None
            } else {
                Some(namespace_from_dir)
            }
        });
        let id = id_from_dir;

        let visibility = front_matter
            .visibility
            .as_deref()
            .and_then(Visibility::parse_str)
            .unwrap_or(Visibility::Private);

        let domain = self.infer_domain_from_registry(&id);

        // P5.1: Verify registry manifest and template path integrity.
        // Non-blocking — drift is recorded as a Regulation span for skill-maintenance to audit.
        let registry_manifest = self
            .project_root
            .join("registry")
            .join("templates")
            .join(&id)
            .join("manifest.yaml");
        let (registry_present, template_count, broken_paths) =
            self.validate_registry_integrity(&registry_manifest);
        tracing::info!(
            target: "reg.skill.lifecycle",
            operation = "registry_validated",
            skill_id = %id,
            registry_present = registry_present,
            template_count = template_count,
            broken_paths = broken_paths.len(),
            "REG"
        );

        let mut skill = Skill::new(&id, domain)
            .with_visibility(visibility)
            .with_zone(zone);

        if let Some(ref ns) = namespace {
            skill = skill.with_namespace(ns.clone());
        }

        skill.compute_content_hash();

        Ok(skill)
    }

    /// Infer the skill's domain from its registry layer manifest.
    ///
    /// If `registry/templates/<id>/manifest.yaml` exists under the project root,
    /// use the most representative template type: FlowDef if any flow is declared,
    /// otherwise KnowAct if any cognition template is present, otherwise WordAct.
    /// If no registry layer exists, default to KnowAct because a Zed-only SKILL.md
    /// is a reasoning companion guide.
    ///
    /// expect: "The system loads skills into the template registry"
    /// \[P3\] Motivating: Generative Space — infers skill domain from registry contents
    /// pre:  id is non-empty
    /// post: returns a TemplateType representing the skill's runtime domain
    fn infer_domain_from_registry(&self, id: &str) -> TemplateType {
        let registry_manifest = self
            .project_root
            .join("registry")
            .join("templates")
            .join(id)
            .join("manifest.yaml");

        // F-03 fix: distinguish "file not found" (legitimate — Zed-only skill,
        // default to KnowAct) from "file present but unparseable" (error — a
        // malformed manifest.yaml is a real defect, not a default case).
        let content = match self.reader.read_to_string(&registry_manifest) {
            Ok(c) => c,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                // Legitimate: no registry layer for this skill (Zed-only).
                return TemplateType::KnowAct;
            }
            Err(_) => {
                // File exists but unreadable — emit a Regulation span and default.
                // (Non-blocking: the skill still loads, but the drift is visible.)
                tracing::warn!(
                    target: "reg.skill.lifecycle",
                    operation = "manifest_unreadable",
                    skill_id = %id,
                    "registry manifest exists but is unreadable — defaulting to KnowAct"
                );
                return TemplateType::KnowAct;
            }
        };

        let manifest: SkillManifest = match serde_yaml_neo::from_str(&content) {
            Ok(m) => m,
            Err(e) => {
                // F-03: malformed manifest is a real error, not a silent default.
                tracing::warn!(
                    target: "reg.skill.lifecycle",
                    operation = "manifest_unparseable",
                    skill_id = %id,
                    error = %e,
                    "registry manifest.yaml is malformed — defaulting to KnowAct"
                );
                return TemplateType::KnowAct;
            }
        };

        let mut has_flowdef = false;
        let mut has_knowact = false;
        let mut has_wordact = false;
        for entry in &manifest.templates {
            match entry.template_type.as_str() {
                "FlowDef" | "flowdef" => has_flowdef = true,
                "KnowAct" | "knowact" => has_knowact = true,
                "WordAct" | "wordact" => has_wordact = true,
                _ => {}
            }
        }

        if has_flowdef {
            TemplateType::FlowDef
        } else if has_knowact {
            TemplateType::KnowAct
        } else if has_wordact {
            TemplateType::WordAct
        } else {
            TemplateType::KnowAct
        }
    }

    /// Validate registry manifest and template path integrity per P5.1.
    ///
    /// Returns (registry_present, template_count, broken_paths).
    /// Non-blocking — records drift for skill-maintenance to audit via Regulation.
    fn validate_registry_integrity(&self, manifest_path: &Path) -> (bool, usize, Vec<String>) {
        let content = match self.reader.read_to_string(manifest_path) {
            Ok(c) => c,
            Err(_) => return (false, 0, Vec::new()),
        };

        let manifest: SkillManifest = match serde_yaml_neo::from_str(&content) {
            Ok(m) => m,
            Err(_) => return (true, 0, Vec::new()),
        };

        let template_count = manifest.templates.len();
        let parent = manifest_path.parent().unwrap_or(Path::new("."));
        let mut broken_paths = Vec::new();
        for entry in &manifest.templates {
            let template_path = parent.join(&entry.path);
            if !template_path.exists() {
                broken_paths.push(entry.path.clone());
            }
        }

        (true, template_count, broken_paths)
    }

    /// Parse YAML front matter from a SKILL.md file.
    /// Expects `---\n` delimiters at the start and end of the front matter block.
    ///
    /// expect: "The system loads skills into the template registry"
    /// \[P3\] Motivating: Generative Space — parses skill front matter metadata
    /// pre:  content is a valid SKILL.md file content
    /// post: returns SkillFrontMatter parsed from YAML front matter
    /// post: returns Err(TemplateError::Frontmatter) if front matter is missing or malformed
    ///       (F-02 fix: silent default-on-missing was a defect — a SKILL.md with no
    ///       frontmatter would silently register with an empty name. Now it errors.)
    pub fn parse_front_matter(content: &str) -> Result<SkillFrontMatter> {
        let content = content.trim_start();

        if !content.starts_with("---") {
            // F-02: missing frontmatter is now an error, not a silent default.
            // A SKILL.md without frontmatter cannot be registered — the name and
            // description fields are required for the registry to function.
            return Err(TemplateError::Frontmatter {
                detail: "no YAML frontmatter — SKILL.md opens with `---`".to_string(),
            });
        }

        // Find the closing `---`.
        let after_first = &content[3..];
        let rest = after_first.trim_start_matches(['-', '\n', '\r']);

        let end_marker = rest
            .find("\n---")
            .ok_or_else(|| TemplateError::Frontmatter {
                detail: "opening `---` found but no closing `---`".to_string(),
            })?;

        let yaml_str = &rest[..end_marker];

        let fm: SkillFrontMatter =
            serde_yaml_neo::from_str(yaml_str).map_err(|e| TemplateError::Frontmatter {
                detail: format!("YAML parse error: {e}"),
            })?;

        Ok(fm)
    }

    /// Check zone-vs-visibility consistency.
    ///
    /// Rules:
    /// - A skill in the public zone MUST have `visibility: public` or `visibility: shared`.
    /// - A skill in the private zone MAY have any visibility.
    ///
    /// If they disagree, the `visibility` field wins and a warning is emitted.
    fn check_zone_visibility(skill: &Skill, zone: SkillZone) -> Option<String> {
        match (zone, skill.visibility) {
            (SkillZone::Public, Visibility::Private) => Some(format!(
                "Skill '{}' is in the public zone ({}) but declares visibility: private. \
                 The declared visibility wins — this skill will be treated as private. \
                 Move it to .agents/skills/ or change visibility to 'public' or 'shared'.",
                skill.id,
                zone.directory()
            )),
            _ => None,
        }
    }
}
