#!/usr/bin/env bash
# QA driver for hKask MCP servers.
#
# Runs the per-tool contract tests defined in
# kask/docs/qa/per-tool-contracts.md against one or all MCP servers.
# Writes pass/fail/skipped rows to kask/docs/qa/coverage-matrix.md.
#
# This driver does NOT emit reg.qa.run spans — that namespace is not
# registered in CANONICAL_NAMESPACES (see Gap A in
# kask/docs/qa/mcp-server-qa-strategy.md). It emits reg.tool spans via
# the tools themselves and records pass/fail in the coverage matrix.
#
# Usage:
#   bash scripts/qa-mcp-servers.sh <server-name>   # one server
#   bash scripts/qa-mcp-servers.sh --all          # all 10 servers
#   bash scripts/qa-mcp-servers.sh <server> --dry-run  # skip live deps
#
# Bounds:
#   --timeout 30        per-tool-call timeout in seconds
#   --server-timeout 600 per-server timeout in seconds
#   --max-iterations 1  passes per (tool, category)
#
# Exit codes:
#   0 — every non-N/A cell is pass | fail | skipped-with-reason (converged)
#   1 — a cell is still pending (did not converge) OR a hard error occurred
#
# This script is a driver — the actual per-tool assertions live in
# each server's tests/qa_contract.rs file, instantiated from the
# contract in kask/docs/qa/per-tool-contracts.md.

set -euo pipefail

KASK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MATRIX="$KASK_ROOT/docs/qa/coverage-matrix.md"
ORACLE_DIR="$KASK_ROOT/docs/qa/oracle"
REGRESSIONS_DIR="$KASK_ROOT/security/regressions"

PER_TOOL_TIMEOUT=30
SERVER_TIMEOUT=600
MAX_ITERATIONS=1
DRY_RUN=0
SERVER=""

# Canonical server list (mirrors BUILTIN_SERVERS in
# crates/hkask-mcp-server/src/hkask_mcp_server.rs — single source of truth).
ALL_SERVERS=(
  hkask-mcp-codegraph
  hkask-mcp-companies
  hkask-mcp-condenser
  hkask-mcp-corpus
  hkask-mcp-curator
  hkask-mcp-kata-kanban
  hkask-mcp-media
  hkask-mcp-research
  hkask-mcp-scenarios
  hkask-mcp-training
)

usage() {
  cat <<EOF
Usage: $0 <server-name | --all> [--dry-run] [--timeout N] [--server-timeout N] [--max-iterations N]
Servers: ${ALL_SERVERS[*]}
EOF
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --all) SERVER="all" ;;
    --dry-run) DRY_RUN=1 ;;
    --timeout) PER_TOOL_TIMEOUT="$2"; shift ;;
    --server-timeout) SERVER_TIMEOUT="$2"; shift ;;
    --max-iterations) MAX_ITERATIONS="$2"; shift ;;
    -h|--help) usage ;;
    *) [ -z "$SERVER" ] && SERVER="$1" || usage ;;
  esac
  shift
done

[ -z "$SERVER" ] && usage

# Validate server name.
is_known() {
  local s
  for s in "${ALL_SERVERS[@]}"; do [ "$s" = "$1" ] && return 0; done
  return 1
}

mkdir -p "$ORACLE_DIR"

# Initialize the coverage matrix on first run.
init_matrix() {
  cat > "$MATRIX" <<'EOF'
# hKask MCP Server QA Coverage Matrix

Generated by `scripts/qa-mcp-servers.sh`. Convergence = no `pending` rows.

| server | tool | category | skill | status | evidence |
|---|---|---|---|---|---|
EOF
}

# Run one server's contract tests.
run_server() {
  local server="$1"
  echo "=== QA pass: $server (dry-run=$DRY_RUN, timeout=${PER_TOOL_TIMEOUT}s) ==="

  # Build the server binary. Failures here are a hard error.
  if ! (cd "$KASK_ROOT" && cargo build --bin "$server" --quiet 2>&1); then
    echo "::error:: failed to build $server"
    echo "| $server | (build) | (build) | n/a | fail | cargo build exit non-zero |" >> "$MATRIX"
    return 1
  fi

  # Run the contract test crate. The qa_contract module is responsible for:
  #   - instantiating the 7 categories per tool
  #   - spawning the server over stdio with a controlled env
  #   - emitting one row per (tool, category) to stdout as TAP-like lines:
  #     qa: <server> <tool> <category> <status> <evidence>
  #   - writing oracle reports for any fail/adversarial finding
  local env_prefix=()
  if [ "$DRY_RUN" -eq 1 ]; then
    env_prefix+=(env HKASK_QA_DRY_RUN=1)
  fi
  env_prefix+=(
    env HKASK_QA_PER_TOOL_TIMEOUT="$PER_TOOL_TIMEOUT"
    env HKASK_QA_MAX_ITERATIONS="$MAX_ITERATIONS"
    env HKASK_QA_MATRIX="$MATRIX"
    env HKASK_QA_ORACLE_DIR="$ORACLE_DIR"
    env HKASK_QA_REGRESSIONS_DIR="$REGRESSIONS_DIR"
  )

  # The test binary is invoked via cargo test so it runs under the
  # server's dev-dependencies. The --server-timeout bounds the whole
  # server pass; per-tool timeout is enforced inside the test.
  (
    cd "$KASK_ROOT"
    "${env_prefix[@]}" timeout "$SERVER_TIMEOUT" \
      cargo test --package "$server" --test qa_contract -- --nocapture --test-threads=1
  ) || {
    local rc=$?
    if [ "$rc" -eq 124 ]; then
      echo "::error:: $server exceeded server-timeout ${SERVER_TIMEOUT}s"
      echo "| $server | (timeout) | (timeout) | n/a | fail | server-timeout ${SERVER_TIMEOUT}s |" >> "$MATRIX"
    else
      echo "::error:: $server contract tests exited $rc"
    fi
    return 1
  }
}

# Main
[ -f "$MATRIX" ] || init_matrix

if [ "$SERVER" = "all" ]; then
  rc=0
  for s in "${ALL_SERVERS[@]}"; do
    run_server "$s" || rc=1
  done
else
  is_known "$SERVER" || { echo "unknown server: $SERVER"; usage; }
  run_server "$SERVER"
  rc=$?
fi

# Convergence check: count pending rows.
pending=$(grep -c '| pending |' "$MATRIX" 2>/dev/null || echo 0)
if [ "$pending" -gt 0 ]; then
  echo "::warning:: $pending pending cell(s) — not converged"
  rc=1
fi

echo "coverage matrix: $MATRIX"
exit "$rc"
