#!/usr/bin/env bash
# QA driver for hKask MCP servers.
#
# Runs the per-tool contract tests defined in
# kask/docs/qa/per-tool-contracts.md against one or all MCP servers.
# Writes pass/fail/skipped rows to kask/docs/qa/coverage-matrix.md.
#
# This driver does NOT emit reg.qa.run spans — that namespace is not
# registered in CANONICAL_NAMESPACES (see Gap A in
# kask/docs/qa/mcp-server-qa-strategy.md). It emits reg.tool spans via
# the tools themselves and records pass/fail in the coverage matrix.
#
# Usage:
#   bash scripts/qa-mcp-servers.sh <server-name>   # one server
#   bash scripts/qa-mcp-servers.sh --all          # all 10 servers
#   bash scripts/qa-mcp-servers.sh <server> --dry-run  # skip live deps
#
# Bounds:
#   --timeout 30        per-tool-call timeout in seconds
#   --server-timeout 600 per-server timeout in seconds
#   --max-iterations 1  passes per (tool, category)
#
# Exit codes:
#   0 — every non-N/A cell is pass | fail | skipped-with-reason (converged)
#   1 — a cell is still pending (did not converge) OR a hard error occurred
#
# This script is a driver — the actual per-tool assertions live in
# each server's tests/qa_contract.rs file, instantiated from the
# contract in kask/docs/qa/per-tool-contracts.md.

set -euo pipefail

KASK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MATRIX="$KASK_ROOT/docs/qa/coverage-matrix.md"
ORACLE_DIR="$KASK_ROOT/docs/qa/oracle"
REGRESSIONS_DIR="$KASK_ROOT/security/regressions"

PER_TOOL_TIMEOUT=30
SERVER_TIMEOUT=600
MAX_ITERATIONS=1
DRY_RUN=0
SERVER=""

# Canonical server list (mirrors BUILTIN_SERVERS in
# crates/hkask-mcp-server/src/hkask_mcp_server.rs — single source of truth).
ALL_SERVERS=(
  hkask-mcp-codegraph
  hkask-mcp-companies
  hkask-mcp-condenser
  hkask-mcp-corpus
  hkask-mcp-curator
  hkask-mcp-kata-kanban
  hkask-mcp-media
  hkask-mcp-research
  hkask-mcp-scenarios
  hkask-mcp-training
)

usage() {
  cat <<EOF
Usage: $0 <server-name | --all> [--dry-run] [--timeout N] [--server-timeout N] [--max-iterations N]
Servers: ${ALL_SERVERS[*]}
EOF
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --all) SERVER="all" ;;
    --dry-run) DRY_RUN=1 ;;
    --timeout) PER_TOOL_TIMEOUT="$2"; shift ;;
    --server-timeout) SERVER_TIMEOUT="$2"; shift ;;
    --max-iterations) MAX_ITERATIONS="$2"; shift ;;
    -h|--help) usage ;;
    *) [ -z "$SERVER" ] && SERVER="$1" || usage ;;
  esac
  shift
done

[ -z "$SERVER" ] && usage

# Validate server name.
is_known() {
  local s
  for s in "${ALL_SERVERS[@]}"; do [ "$s" = "$1" ] && return 0; done
  return 1
}

mkdir -p "$ORACLE_DIR"

# Initialize the coverage matrix on first run.
init_matrix() {
  cat > "$MATRIX" <<'EOF'
# hKask MCP Server QA Coverage Matrix

Generated by `scripts/qa-mcp-servers.sh`. Convergence = no `pending` rows.

| server | tool | category | skill | status | evidence |
|---|---|---|---|---|---|
EOF
}

# Run one server's contract tests.
run_server() {
  local server="$1"
  echo "=== QA pass: $server (dry-run=$DRY_RUN, timeout=${PER_TOOL_TIMEOUT}s) ==="

  # Build the server binary. Failures here are a hard error.
  # Use -p to scope to the package (workspace --bin lookup is ambiguous).
  if ! (cd "$KASK_ROOT" && cargo build -p "$server" --bin "$server" --quiet 2>&1); then
    echo "::error:: failed to build $server"
    echo "| $server | (build) | (build) | n/a | fail | cargo build exit non-zero |" >> "$MATRIX"
    return 1
  fi

  # Run the contract test crate. The qa_contract module uses standard
  # #[tokio::test] with module names matching the tool name and test names
  # matching the category (e.g. `board_create::happy`). The driver parses
  # cargo's test output to extract pass/fail per (tool, category) and writes
  # the coverage matrix rows.
  #
  # Test naming convention (from qa_contract.rs):
  #   mod <tool_name_without_kanban_prefix> { fn <category> }
  # e.g. `board_create::happy`, `task_move::error_propagation_invalid_transition`
  #
  # The driver maps each test result to a matrix row.
  local env_prefix=()
  if [ "$DRY_RUN" -eq 1 ]; then
    env_prefix+=(env HKASK_QA_DRY_RUN=1)
  fi
  env_prefix+=(
    env HKASK_QA_PER_TOOL_TIMEOUT="$PER_TOOL_TIMEOUT"
    env HKASK_QA_MAX_ITERATIONS="$MAX_ITERATIONS"
    env HKASK_QA_MATRIX="$MATRIX"
    env HKASK_QA_ORACLE_DIR="$ORACLE_DIR"
    env HKASK_QA_REGRESSIONS_DIR="$REGRESSIONS_DIR"
  )

  # Run tests with --nocapture and parse output. cargo test emits lines like:
  #   test board_create::happy ... ok
  #   test task_move::error_propagation_invalid_transition ... FAILED
  # We extract (test_name, status) pairs and write matrix rows.
  local test_output
  test_output=$(
    cd "$KASK_ROOT"
    "${env_prefix[@]}" timeout "$SERVER_TIMEOUT" \
      cargo test --package "$server" --test qa_contract -- --nocapture --test-threads=1 2>&1
  ) || true  # cargo test exits non-zero on any failure; we capture per-test

  # Parse test result lines and write matrix rows.
  # Lines look like: "test <mod>::<fn> ... ok" or "test <mod>::<fn> ... FAILED"
  local pass_count=0 fail_count=0
  while IFS= read -r line; do
    # Match: test <name> ... ok|FAILED|ignored
    if [[ "$line" =~ ^test\ ([a-zA-Z0-9_:]+)\ \.\.\.\ (ok|FAILED|ignored) ]]; then
      local test_name="${BASH_REMATCH[1]}"
      local status="${BASH_REMATCH[2]}"
      local matrix_status
      case "$status" in
        ok)       matrix_status="pass"; pass_count=$((pass_count + 1)) ;;
        FAILED)   matrix_status="fail"; fail_count=$((fail_count + 1)) ;;
        ignored)  matrix_status="skipped-with-reason" ;;
      esac
      echo "| $server | $test_name | (from test name) | tdd | $matrix_status | cargo test output |" >> "$MATRIX"
    fi
  done <<< "$test_output"

  echo "  $server: $pass_count passed, $fail_count failed"

  # If cargo test itself failed to run (not just test failures), check timeout.
  if ! echo "$test_output" | grep -q '^test result:'; then
    echo "::error:: $server contract tests did not produce a result line"
    echo "| $server | (no-result) | (no-result) | n/a | fail | no test result line |" >> "$MATRIX"
    return 1
  fi
}

# Main
[ -f "$MATRIX" ] || init_matrix

if [ "$SERVER" = "all" ]; then
  rc=0
  for s in "${ALL_SERVERS[@]}"; do
    run_server "$s" || rc=1
  done
else
  is_known "$SERVER" || { echo "unknown server: $SERVER"; usage; }
  run_server "$SERVER"
  rc=$?
fi

# Convergence check: count pending rows.
pending=$(grep -c '| pending |' "$MATRIX" 2>/dev/null || true)
pending=${pending:-0}
if [ "$pending" -gt 0 ]; then
  echo "::warning:: $pending pending cell(s) — not converged"
  rc=1
fi

echo "coverage matrix: $MATRIX"
exit "$rc"
