//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! Scans `src/**/*.rs` for `pub async fn <name>` and emits a
//! `pub const TOOL_NAMES: &[&str]`. The media server's tools span multiple
//! prefixes (gallery_, image_, video_, audio_, face_, generate_, voice_,
//! transcribe, model_, job_, workflow_), so we match all `pub async fn`
//! names except `run` (the server entry point, not a tool). Mirrors
//! `hkask-mcp-portfolio/build.rs`.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    // Match all `pub async fn <name>(` — the media server's tools don't
    // share a single prefix. Exclude `run` (the server entry point).
    let pattern = regex::Regex::new(r"pub async fn (\w+)\s*\(").expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    scan_dir(&src_dir, &pattern, &mut names);

    // Remove non-tool functions.
    names.remove("run");

    let mut entries = String::new();
    for name in &names {
        entries.push_str(&format!("    \"{name}\",\n"));
    }
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/**/*.rs` for `pub async fn *` signatures (excluding `run`).\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n"
    );

    let existing = fs::read_to_string(&out_path).unwrap_or_default();
    if existing != generated {
        fs::write(&out_path, generated).expect("writable OUT_DIR");
    }

    println!("cargo:rerun-if-changed={}", src_dir.display());
}

fn scan_dir(dir: &Path, pattern: &regex::Regex, names: &mut BTreeSet<String>) {
    for entry in fs::read_dir(dir).expect("src directory exists") {
        let entry = entry.expect("readable dir entry");
        let path = entry.path();
        if path.is_dir() {
            scan_dir(&path, pattern, names);
            continue;
        }
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        for caps in pattern.captures_iter(&source) {
            names.insert(caps[1].to_string());
        }
    }
}
