#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! hkask-mcp-spreadsheet — the central spreadsheet mutation owner.
//!
//! One server owns persisted spreadsheet edits (plan §4): analytical servers
//! remain producers; `hkask-spreadsheet` owns workbook construction and
//! artifact publication; THIS server owns the two mutation tools:
//!
//! - `spreadsheet_apply` — verify a base revision digest, apply typed cell
//!   edits, publish a NEW immutable revision, and return the workbook block
//!   as a server-authoritative ` ```spreadsheet ` display hint.
//! - `spreadsheet_operation_get` — reconcile an interrupted operation by its
//!   idempotency key (§7). An absent record means the outcome is UNKNOWN,
//!   never "not applied"; the widget must not blindly replay.
//!
//! The engine actor (`WorkbookService`) runs on a dedicated thread inside
//! this process (the LogiSheets `Workbook` is `!Send`); every tool call
//! exchanges `Send` commands and responses with it.

pub mod server;

// ── Canonical tool-name list ─────────────────────────────────────────────
//
// Generated by `build.rs` from `pub async fn spreadsheet_*` signatures in
// `src/*.rs`. The `tool_names_match_live_router` test pins the generated
// list against the live router.
include!(concat!(env!("OUT_DIR"), "/tool_names.gen.rs"));

pub use server::run;

#[cfg(test)]
mod tool_surface_tests {
    use super::*;

    hkask_mcp_server::tool_surface_pin!(
        crate::server::SpreadsheetServer::spreadsheet_router(),
        "spreadsheet_router",
        2,
        tool_surface_is_exactly_2_registered_tools,
    );
}
