#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! hkask-mcp-spreadsheet — the central spreadsheet mutation owner.
//!
//! One server owns persisted spreadsheet edits (plan §4): analytical servers
//! remain producers; `hkask-spreadsheet` owns workbook construction and
//! artifact publication; THIS server owns the two mutation tools:
//!
//! - `spreadsheet_apply` — verify a base revision digest, apply typed cell
//!   edits, publish a NEW immutable revision, and return the workbook block
//!   as a server-authoritative ` ```spreadsheet ` display hint.
//! - `spreadsheet_operation_get` — reconcile an interrupted operation by its
//!   idempotency key (§7). An absent record means the outcome is UNKNOWN,
//!   never "not applied"; the widget must not blindly replay.
//!
//! The engine actor (`WorkbookService`) runs on a dedicated thread inside
//! this process (the LogiSheets `Workbook` is `!Send`); every tool call
//! exchanges `Send` commands and responses with it.

pub mod server;

// ── Canonical tool-name list ─────────────────────────────────────────────
//
// Generated by `build.rs` from `pub async fn spreadsheet_*` signatures in
// `src/*.rs`. The `tool_names_match_live_router` test pins the generated
// list against the live router.
include!(concat!(env!("OUT_DIR"), "/tool_names.gen.rs"));

pub use server::run;

#[cfg(test)]
mod tool_name_pin {
    // Pins the generated TOOL_NAMES const against the live rmcp tool
    // surface — a tool added/renamed fails here instead of degrading to
    // "tool not found" at dispatch.
    #[test]
    fn tool_names_match_live_router() {
        let mut live: Vec<String> = crate::server::SpreadsheetServer::spreadsheet_router()
            .list_all()
            .iter()
            .map(|tool| tool.name.to_string())
            .collect();
        live.sort();
        let generated: Vec<&str> = crate::TOOL_NAMES.to_vec();
        assert_eq!(
            generated,
            live.iter().map(String::as_str).collect::<Vec<_>>(),
            "TOOL_NAMES (build.rs-generated) must match the live spreadsheet_router surface"
        );
    }
}
