#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! # hKask Ledger — Double-Entry Accounting
//!
//! Immutable double-entry ledger backed by the provider-agnostic `DatabaseDriver`
//! abstraction (ADR-043). Three domain ledgers (cost, crypto, securities) share
//! this crate with separate database files.
//!
//! ## Invariants
//!
//! 1. **Idempotency** — same `reference` with identical postings is a no-op.
//!    Different postings with the same reference return `IdempotencyConflict`.
//! 2. **Double-entry** — every transaction's postings must sum to 0.
//! 3. **Immutability** — committed transactions are never modified or deleted.
//!    DO NOT use INSERT OR REPLACE on the transactions table — it would
//!    cascade-delete postings and retroactively change account balances.

mod schema;
mod types;

pub use types::{AccountBalance, DateRange, LedgerError, LedgerTransaction, Posting, QueryFilter};

use hkask_storage::database::driver::DatabaseDriver;
use hkask_storage::database::types::DbError;
use hkask_storage::database::value::DbValue;
use hkask_storage::define_driver_store;
use std::sync::Arc;

// The double-entry ledger.
//
// Backed by a provider-agnostic `DatabaseDriver` (ADR-043). The driver
// abstracts over SQLite and PostgreSQL, so the ledger works with either
// provider. `Ledger` is `Send + Sync` and can be shared via `Arc`.
//
// `from_driver` and the `driver` accessor are generated by
// `define_driver_store!`. The macro is invoked with `LedgerError` (rather
// than the default `InfrastructureError`) so the generated `from_driver`
// returns the ledger's domain error directly instead of forcing an
// infrastructure-error boundary at the store seam.
define_driver_store!(Ledger, LedgerError);

impl Ledger {
    /// Initialize the ledger schema. Delegates to `schema::init_schema`,
    /// which is idempotent and safe to call on an existing database.
    ///
    /// Called by the macro-generated `from_driver`.
    fn init_schema(driver: &Arc<dyn DatabaseDriver>) -> Result<(), LedgerError> {
        schema::init_schema(driver)
    }

    /// REQ: P8-ledger-ensure-account
    /// expect: "I can create a named account and doing it twice is harmless" \[P8\]
    /// pre:  id and namespace are non-empty strings
    /// post: account exists in the database; second call with same id is a no-op
    /// inv:  idempotent — calling ensure_account twice with same id does not error
    /// \[P8\] Constraining: Persistence — account survives restarts
    pub fn ensure_account(&self, id: &str, namespace: &str) -> Result<(), LedgerError> {
        let now = chrono::Utc::now().to_rfc3339();
        self.driver.execute(
            "INSERT OR IGNORE INTO accounts (id, namespace, created_at) VALUES (?1, ?2, ?3)",
            &[
                DbValue::Text(id.to_string()),
                DbValue::Text(namespace.to_string()),
                DbValue::Text(now),
            ],
        )?;
        Ok(())
    }

    /// REQ: P8-ledger-commit
    /// expect: "I can commit a transaction and the postings are stored immutably" \[P8\]
    /// pre:  tx.id is unique, tx.reference is unique, tx.postings is non-empty
    /// post: transaction and all postings are stored; balances reflect new postings
    /// inv:  idempotent by reference — identical postings succeed silently;
    ///       different postings with same reference return IdempotencyConflict
    /// \[P4\] Constraining: Clear Boundaries — committed transactions cannot be modified
    /// \[P8\] Constraining: Persistence — committed data survives restarts
    pub fn commit(&self, tx: &LedgerTransaction) -> Result<(), LedgerError> {
        if tx.postings.is_empty() {
            return Err(LedgerError::DoubleEntryViolation(0));
        }

        let now = chrono::Utc::now().to_rfc3339();

        // Check if this reference already exists
        let existing = self.driver.query_optional(
            "SELECT id FROM transactions WHERE reference = ?1",
            &[DbValue::Text(tx.reference.clone())],
        )?;

        if let Some(row) = existing {
            let existing_id = row.get_str(0)?.to_string();
            // Reference exists — verify the postings match for true idempotency
            let existing_postings = self.driver.query(
                "SELECT source, destination, asset, amount
                 FROM postings WHERE transaction_id = ?1 ORDER BY id",
                &[DbValue::Text(existing_id)],
            )?;

            if existing_postings.len() != tx.postings.len() {
                return Err(LedgerError::IdempotencyConflict {
                    reference: tx.reference.clone(),
                });
            }
            for (i, p) in tx.postings.iter().enumerate() {
                let row = &existing_postings[i];
                let src = row.get_str(0)?;
                let dst = row.get_str(1)?;
                let ast = row.get_str(2)?;
                let amt = row.get_int(3)?;
                if p.source != src || p.destination != dst || p.asset != ast || p.amount != amt {
                    return Err(LedgerError::IdempotencyConflict {
                        reference: tx.reference.clone(),
                    });
                }
            }
            // Postings match — true idempotent, no-op
            return Ok(());
        }

        // Wrap in transaction for atomicity
        self.driver.execute_batch("BEGIN IMMEDIATE")?;
        let result: Result<(), LedgerError> = (|| {
            self.driver.execute(
                "INSERT INTO transactions (id, timestamp, reference, metadata, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                &[
                    DbValue::Text(tx.id.clone()),
                    DbValue::Text(tx.timestamp.clone()),
                    DbValue::Text(tx.reference.clone()),
                    DbValue::Text(tx.metadata.to_string()),
                    DbValue::Text(now.clone()),
                ],
            )?;

            for posting in &tx.postings {
                self.driver.execute(
                    "INSERT INTO postings (transaction_id, source, destination, asset, amount, created_at)
                     VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                    &[
                        DbValue::Text(tx.id.clone()),
                        DbValue::Text(posting.source.clone()),
                        DbValue::Text(posting.destination.clone()),
                        DbValue::Text(posting.asset.clone()),
                        DbValue::Integer(posting.amount),
                        DbValue::Text(now.clone()),
                    ],
                )?;
            }
            Ok(())
        })();
        match result {
            Ok(()) => {
                self.driver.execute_batch("COMMIT")?;
                Ok(())
            }
            Err(e) => {
                if let Err(rollback_err) = self.driver.execute_batch("ROLLBACK") {
                    tracing::error!(
                        target: "hkask.ledger",
                        error = %rollback_err,
                        "Failed to rollback ledger transaction"
                    );
                }
                Err(e)
            }
        }
    }

    /// Atomically debit `amount` of `asset` from `account` to `external`,
    /// enforcing the non-negative balance invariant.
    ///
    /// The balance check and the posting insert happen inside a single
    /// `BEGIN IMMEDIATE` transaction. `BEGIN IMMEDIATE` acquires the write
    /// lock before the balance read, so two concurrent `debit_if_funds`
    /// calls serialize: the first commits its debit, the second re-reads the
    /// now-reduced balance and rejects if it has dropped below `amount`.
    /// This closes the TOCTOU window that a separate check-then-commit path
    /// leaves open (both callers read the pre-debit balance, both commit,
    /// the account goes negative).
    ///
    /// `reference` must be unique (it backs the transactions.reference
    /// UNIQUE constraint); callers mint a fresh UUID per debit. `metadata` is
    /// stored verbatim on the committed transaction (e.g. `{"action":"debit"}`).
    ///
    /// Returns the post-debit balance of `(account, asset)`, or
    /// `Err(InsufficientFunds)` if the balance (read inside the transaction)
    /// is less than `amount`.
    pub fn debit_if_funds(
        &self,
        account: &str,
        asset: &str,
        amount: i64,
        reference: &str,
        metadata: &serde_json::Value,
    ) -> Result<i64, LedgerError> {
        if amount <= 0 {
            return Err(LedgerError::InsufficientFunds {
                account: account.to_string(),
                asset: asset.to_string(),
                balance: 0,
                required: amount,
            });
        }

        let tx_id = uuid::Uuid::new_v4().to_string();
        let now = chrono::Utc::now().to_rfc3339();

        // Acquire the write lock up front. Any concurrent writer (another
        // debit, a commit) blocks until this transaction finishes, so the
        // balance read below sees the committed effect of all prior writers.
        self.driver.execute_batch("BEGIN IMMEDIATE")?;
        let result: Result<(), LedgerError> = (|| {
            // Re-read the balance INSIDE the transaction. The write lock
            // guarantees no other writer can land a debit between this read
            // and the insert below.
            let row = self.driver.query_optional(
                "SELECT COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE (source = ?1 OR destination = ?1) AND asset = ?2",
                &[
                    DbValue::Text(account.to_string()),
                    DbValue::Text(asset.to_string()),
                ],
            )?;
            let balance = match row {
                Some(r) => r.get_int(0)?,
                None => 0,
            };
            if balance < amount {
                return Err(LedgerError::InsufficientFunds {
                    account: account.to_string(),
                    asset: asset.to_string(),
                    balance,
                    required: amount,
                });
            }

            self.driver.execute(
                "INSERT INTO transactions (id, timestamp, reference, metadata, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                &[
                    DbValue::Text(tx_id.clone()),
                    DbValue::Text(now.clone()),
                    DbValue::Text(reference.to_string()),
                    DbValue::Text(metadata.to_string()),
                    DbValue::Text(now.clone()),
                ],
            )?;
            self.driver.execute(
                "INSERT INTO postings (transaction_id, source, destination, asset, amount, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                &[
                    DbValue::Text(tx_id),
                    DbValue::Text(account.to_string()),
                    DbValue::Text("external".to_string()),
                    DbValue::Text(asset.to_string()),
                    DbValue::Integer(amount),
                    DbValue::Text(now),
                ],
            )?;
            Ok(())
        })();
        match result {
            Ok(()) => {
                self.driver.execute_batch("COMMIT")?;
            }
            Err(e) => {
                if let Err(rollback_err) = self.driver.execute_batch("ROLLBACK") {
                    tracing::error!(
                        target: "hkask.ledger",
                        error = %rollback_err,
                        "Failed to rollback debit_if_funds transaction"
                    );
                }
                return Err(e);
            }
        }

        self.balance(account, Some(asset))
    }

    /// REQ: P9-ledger-balance
    /// expect: "I can query the balance of any account and see all credits minus debits" \[P9\]
    /// pre:  account is a valid account ID (may or may not exist)
    /// post: returns sum(destination amounts) - sum(source amounts) for matching asset
    /// inv:  read-only — does not modify the ledger; non-existent account returns 0
    /// \[P9\] Constraining: Observability — balances are visible to the user
    pub fn balance(&self, account: &str, asset: Option<&str>) -> Result<i64, LedgerError> {
        let (sql, params) = if let Some(a) = asset {
            (
                "SELECT
                        COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE (source = ?1 OR destination = ?1) AND asset = ?2",
                vec![
                    DbValue::Text(account.to_string()),
                    DbValue::Text(a.to_string()),
                ],
            )
        } else {
            (
                "SELECT
                        COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE source = ?1 OR destination = ?1",
                vec![DbValue::Text(account.to_string())],
            )
        };
        let row = self.driver.query_optional(sql, &params)?;
        // No row → account has no postings → balance is legitimately 0.
        // A get_int error on a present row is a real DB failure and must
        // propagate rather than read as a zero balance.
        let balance = match row {
            Some(r) => r.get_int(0)?,
            None => 0,
        };
        Ok(balance)
    }

    /// REQ: P9-ledger-namespace-balances
    /// expect: "I can see all balances in a domain (cost, wallet, portfolio) at once" \[P9\]
    /// pre:  namespace is a valid namespace string
    /// post: returns all (account, asset, balance) h_mems for accounts in the namespace
    /// inv:  read-only; returns empty vec for unknown namespace
    /// \[P9\] Constraining: Observability — all domain balances are visible at once
    pub fn namespace_balances(&self, namespace: &str) -> Result<Vec<AccountBalance>, LedgerError> {
        let rows = self.driver.query(
            "SELECT a.id,
                    COALESCE(p.asset, '') AS asset,
                    COALESCE(SUM(CASE WHEN p.destination = a.id THEN p.amount ELSE 0 END), 0)
                  - COALESCE(SUM(CASE WHEN p.source = a.id THEN p.amount ELSE 0 END), 0) AS balance
             FROM accounts a
             LEFT JOIN postings p ON (p.source = a.id OR p.destination = a.id)
             WHERE a.namespace = ?1
             GROUP BY a.id, p.asset
             ORDER BY a.id, p.asset",
            &[DbValue::Text(namespace.to_string())],
        )?;

        let mut balances = Vec::new();
        for row in rows {
            balances.push(AccountBalance {
                account: row.get_str(0)?.to_string(),
                asset: row.get_str(1)?.to_string(),
                balance: row.get(2)?.as_int()?,
            });
        }
        Ok(balances)
    }

    /// REQ: P9-ledger-transaction-count
    /// expect: "I can count how many transactions reference a specific account" \[P9\]
    /// pre:  destination is a valid account ID
    /// post: returns count of unique transactions with a posting to that account
    /// inv:  read-only
    /// \[P9\] Constraining: Observability — transaction volume is queryable
    pub fn transaction_count(&self, destination: &str) -> Result<u64, LedgerError> {
        let row = self.driver.query_optional(
            "SELECT COUNT(DISTINCT transaction_id) FROM postings WHERE destination = ?1",
            &[DbValue::Text(destination.to_string())],
        )?;
        // No row → no transactions for this account → count is legitimately 0.
        // A get_int error on a present row must propagate rather than read as
        // a zero count.
        let count = match row {
            Some(r) => r.get_int(0)?,
            None => 0,
        };
        Ok(u64::try_from(count).unwrap_or_else(|_| {
            tracing::warn!(target: "ledger", count, "Negative transaction count from database — clamping to 0");
            0
        }))
    }

    /// REQ: P9-ledger-query
    /// expect: "I can query transactions by time range and filter by account or asset" \[P9\]
    /// pre:  range.start <= range.end (ISO 8601 strings)
    /// post: returns all transactions whose timestamp falls within the range,
    ///       filtered by optional account/asset/namespace criteria
    /// inv:  read-only; returns empty vec if no matches
    /// \[P9\] Constraining: Observability — transaction history is queryable
    pub fn query(
        &self,
        range: &DateRange,
        filter: &QueryFilter,
    ) -> Result<Vec<LedgerTransaction>, LedgerError> {
        // Build query with parameterized conditions
        let mut conditions = vec!["t.timestamp >= ?1 AND t.timestamp <= ?2".to_string()];
        if filter.account.is_some() {
            conditions.push("(p.source = ?3 OR p.destination = ?3)".to_string());
        }
        if filter.asset.is_some() {
            let idx = if filter.account.is_some() { 4 } else { 3 };
            conditions.push(format!("p.asset = ?{idx}"));
        }
        if filter.namespace.is_some() {
            let idx = 3 + filter.account.is_some() as usize + filter.asset.is_some() as usize;
            conditions.push(format!(
                "EXISTS (SELECT 1 FROM accounts a WHERE (a.id = p.source OR a.id = p.destination) AND a.namespace = ?{idx})"
            ));
        }

        let sql = format!(
            "SELECT DISTINCT t.id, t.timestamp, t.reference, t.metadata, t.created_at
             FROM transactions t
             JOIN postings p ON p.transaction_id = t.id
             WHERE {}
             ORDER BY t.timestamp, t.id",
            conditions.join(" AND ")
        );

        let params = build_query_params(range, filter);
        let tx_rows = self.driver.query(&sql, &params)?;

        // For each transaction, load its postings
        let mut result = Vec::new();
        for row in tx_rows {
            let id = row.get_str(0)?.to_string();
            let timestamp = row.get_str(1)?.to_string();
            let reference = row.get_str(2)?.to_string();
            let metadata_str = row.get_str(3)?.to_string();

            let postings = self.driver.query(
                "SELECT source, destination, asset, amount
                 FROM postings WHERE transaction_id = ?1 ORDER BY id",
                &[DbValue::Text(id.clone())],
            )?;

            let postings: Vec<Posting> = postings
                .iter()
                .map(|p| {
                    Ok(Posting {
                        source: p.get_str(0)?.to_string(),
                        destination: p.get_str(1)?.to_string(),
                        asset: p.get_str(2)?.to_string(),
                        amount: p.get_int(3)?,
                    })
                })
                .collect::<Result<Vec<_>, DbError>>()?;

            let tx_id = id.clone();
            result.push(LedgerTransaction {
                id,
                timestamp,
                reference,
                postings,
                metadata: serde_json::from_str(&metadata_str).unwrap_or_else(|e| {
                    tracing::warn!(target: "ledger", error = %e, transaction_id = %tx_id, "Corrupted metadata JSON");
                    serde_json::Value::Null
                }),
            });
        }

        Ok(result)
    }
}

/// Build parameter list for the query() method.
fn build_query_params(range: &DateRange, filter: &QueryFilter) -> Vec<DbValue> {
    let mut params: Vec<DbValue> = vec![
        DbValue::Text(range.start.clone()),
        DbValue::Text(range.end.clone()),
    ];
    if let Some(ref account) = filter.account {
        params.push(DbValue::Text(account.clone()));
    }
    if let Some(ref asset) = filter.asset {
        params.push(DbValue::Text(asset.clone()));
    }
    if let Some(ref ns) = filter.namespace {
        params.push(DbValue::Text(ns.clone()));
    }
    params
}

#[cfg(test)]
mod tests {
    use super::*;
    use hkask_storage::database::sqlite::SqliteDriver;

    fn db() -> Ledger {
        Ledger::from_driver(SqliteDriver::in_memory_driver()).expect("ledger from driver")
    }

    #[test]
    fn ledger_open_creates_schema() {
        let ledger = db();
        // Verify tables exist by inserting and querying
        ledger.ensure_account("test:asset", "test").unwrap();
        let bal = ledger.balance("test:asset", None).unwrap();
        assert_eq!(bal, 0);
    }

    #[test]
    fn ledger_open_is_idempotent() {
        let driver = SqliteDriver::in_memory_driver();
        let _l1 = Ledger::from_driver(driver.clone()).unwrap();
        let _l2 = Ledger::from_driver(driver).unwrap();
        // No error — schema creation is idempotent
    }

    #[test]
    fn ensure_account_creates() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        let bal = ledger.balance("alice", None).unwrap();
        assert_eq!(bal, 0);
    }

    #[test]
    fn ensure_account_is_idempotent() {
        let ledger = db();
        ledger.ensure_account("bob", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();
        // No error — second call is a no-op
    }

    fn sample_tx(reference: &str) -> LedgerTransaction {
        LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            reference: reference.to_string(),
            postings: vec![
                Posting {
                    source: "alice".to_string(),
                    destination: "bob".to_string(),
                    asset: "usd".to_string(),
                    amount: 100,
                },
                Posting {
                    source: "bob".to_string(),
                    destination: "alice".to_string(),
                    asset: "usd".to_string(),
                    amount: -100,
                },
            ],
            metadata: serde_json::json!({"reason": "test"}),
        }
    }

    #[test]
    fn commit_stores_transaction() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();
        let tx = sample_tx("tx-001");
        ledger.commit(&tx).unwrap();

        let bal = ledger.balance("bob", Some("usd")).unwrap();
        assert_eq!(bal, 200); // +100 from alice, -(-100) from alice's second posting
    }

    #[test]
    fn commit_is_idempotent() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();
        let tx = sample_tx("tx-002");
        ledger.commit(&tx).unwrap();
        // Second commit with same reference + same postings — no-op
        ledger.commit(&tx).unwrap();
        let bal = ledger.balance("bob", Some("usd")).unwrap();
        assert_eq!(bal, 200); // unchanged
    }

    #[test]
    fn commit_rejects_idempotency_conflict() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();
        let tx1 = sample_tx("tx-003");
        ledger.commit(&tx1).unwrap();

        let mut tx2 = sample_tx("tx-003"); // same reference
        tx2.postings[0].amount = 999; // different postings
        let result = ledger.commit(&tx2);
        assert!(matches!(
            result,
            Err(LedgerError::IdempotencyConflict { .. })
        ));
    }

    #[test]
    fn commit_rejects_empty_postings() {
        let ledger = db();
        let tx = LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            reference: "tx-empty".to_string(),
            postings: vec![],
            metadata: serde_json::json!({}),
        };
        let result = ledger.commit(&tx);
        assert!(matches!(result, Err(LedgerError::DoubleEntryViolation(0))));
    }

    #[test]
    fn balance_after_commit() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();

        let tx = LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            reference: "tx-bal-1".to_string(),
            postings: vec![
                Posting {
                    source: "alice".to_string(),
                    destination: "bob".to_string(),
                    asset: "usd".to_string(),
                    amount: 500,
                },
                Posting {
                    source: "bob".to_string(),
                    destination: "alice".to_string(),
                    asset: "usd".to_string(),
                    amount: -500,
                },
            ],
            metadata: serde_json::json!({}),
        };
        ledger.commit(&tx).unwrap();

        assert_eq!(ledger.balance("bob", Some("usd")).unwrap(), 1000);
        assert_eq!(ledger.balance("alice", Some("usd")).unwrap(), -1000);
    }

    #[test]
    fn balance_nonexistent_returns_zero() {
        let ledger = db();
        assert_eq!(ledger.balance("nobody", None).unwrap(), 0);
    }

    #[test]
    fn balances_sum_to_zero() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();
        ledger.ensure_account("carol", "wallet").unwrap();

        let tx = LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            reference: "tx-sum-1".to_string(),
            postings: vec![
                Posting {
                    source: "alice".to_string(),
                    destination: "bob".to_string(),
                    asset: "usd".to_string(),
                    amount: 300,
                },
                Posting {
                    source: "bob".to_string(),
                    destination: "carol".to_string(),
                    asset: "usd".to_string(),
                    amount: 300,
                },
                Posting {
                    source: "carol".to_string(),
                    destination: "alice".to_string(),
                    asset: "usd".to_string(),
                    amount: 300,
                },
                Posting {
                    source: "alice".to_string(),
                    destination: "alice".to_string(),
                    asset: "usd".to_string(),
                    amount: -900,
                },
            ],
            metadata: serde_json::json!({}),
        };
        ledger.commit(&tx).unwrap();

        let total: i64 = ["alice", "bob", "carol"]
            .iter()
            .map(|a| ledger.balance(a, Some("usd")).unwrap())
            .sum();
        assert_eq!(total, 0);
    }

    #[test]
    fn namespace_balances_returns_all_accounts() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();
        ledger.ensure_account("carol", "cost").unwrap();

        let tx = LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            reference: "tx-ns-1".to_string(),
            postings: vec![
                Posting {
                    source: "alice".to_string(),
                    destination: "bob".to_string(),
                    asset: "usd".to_string(),
                    amount: 100,
                },
                Posting {
                    source: "bob".to_string(),
                    destination: "alice".to_string(),
                    asset: "usd".to_string(),
                    amount: -100,
                },
            ],
            metadata: serde_json::json!({}),
        };
        ledger.commit(&tx).unwrap();

        let wallet_balances = ledger.namespace_balances("wallet").unwrap();
        assert!(wallet_balances.iter().any(|b| b.account == "alice"));
        assert!(wallet_balances.iter().any(|b| b.account == "bob"));
        assert!(!wallet_balances.iter().any(|b| b.account == "carol"));
    }

    #[test]
    fn namespace_balances_empty_for_unknown() {
        let ledger = db();
        let balances = ledger.namespace_balances("nonexistent").unwrap();
        assert!(balances.is_empty());
    }

    #[test]
    fn query_by_time_range() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();

        let tx = sample_tx("tx-query-1");
        ledger.commit(&tx).unwrap();

        let range = DateRange {
            start: "2000-01-01T00:00:00Z".to_string(),
            end: "2099-12-31T23:59:59Z".to_string(),
        };
        let results = ledger.query(&range, &QueryFilter::default()).unwrap();
        assert!(!results.is_empty());
        assert!(results.iter().any(|t| t.reference == "tx-query-1"));
    }

    #[test]
    fn query_empty_when_no_matches() {
        let ledger = db();
        let range = DateRange {
            start: "2000-01-01T00:00:00Z".to_string(),
            end: "2000-01-02T00:00:00Z".to_string(),
        };
        let results = ledger.query(&range, &QueryFilter::default()).unwrap();
        assert!(results.is_empty());
    }

    #[test]
    fn query_filter_by_account() {
        let ledger = db();
        ledger.ensure_account("alice", "wallet").unwrap();
        ledger.ensure_account("bob", "wallet").unwrap();

        let tx = sample_tx("tx-filter-1");
        ledger.commit(&tx).unwrap();

        let range = DateRange {
            start: "2000-01-01T00:00:00Z".to_string(),
            end: "2099-12-31T23:59:59Z".to_string(),
        };
        let filter = QueryFilter {
            account: Some("alice".to_string()),
            ..Default::default()
        };
        let results = ledger.query(&range, &filter).unwrap();
        assert!(!results.is_empty());
    }

    fn fund_account(ledger: &Ledger, account: &str, asset: &str, amount: i64, reference: &str) {
        let tx = LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            reference: reference.to_string(),
            postings: vec![Posting {
                source: "external".to_string(),
                destination: account.to_string(),
                asset: asset.to_string(),
                amount,
            }],
            metadata: serde_json::json!({ "action": "fund" }),
        };
        ledger.commit(&tx).unwrap();
    }

    #[test]
    fn debit_if_funds_debits_and_returns_new_balance() {
        let ledger = db();
        ledger.ensure_account("op", "wallet").unwrap();
        fund_account(&ledger, "op", "rj", 500, "fund-1");

        let new_balance = ledger
            .debit_if_funds(
                "op",
                "rj",
                200,
                "debit-1",
                &serde_json::json!({ "action": "debit" }),
            )
            .unwrap();
        assert_eq!(new_balance, 300);
        assert_eq!(ledger.balance("op", Some("rj")).unwrap(), 300);
    }

    #[test]
    fn debit_if_funds_rejects_insufficient_balance() {
        let ledger = db();
        ledger.ensure_account("op", "wallet").unwrap();
        fund_account(&ledger, "op", "rj", 100, "fund-2");

        let result = ledger.debit_if_funds(
            "op",
            "rj",
            200,
            "debit-2",
            &serde_json::json!({ "action": "debit" }),
        );
        assert!(matches!(
            result,
            Err(LedgerError::InsufficientFunds {
                balance: 100,
                required: 200,
                ..
            })
        ));
        // Balance is unchanged — the transaction was rolled back.
        assert_eq!(ledger.balance("op", Some("rj")).unwrap(), 100);
    }

    #[test]
    fn debit_if_funds_rejects_zero_and_negative() {
        let ledger = db();
        ledger.ensure_account("op", "wallet").unwrap();
        fund_account(&ledger, "op", "rj", 500, "fund-3");

        let zero = ledger.debit_if_funds("op", "rj", 0, "debit-zero", &serde_json::json!({}));
        assert!(matches!(zero, Err(LedgerError::InsufficientFunds { .. })));

        let negative = ledger.debit_if_funds("op", "rj", -10, "debit-neg", &serde_json::json!({}));
        assert!(matches!(
            negative,
            Err(LedgerError::InsufficientFunds { .. })
        ));

        // No spurious postings were inserted.
        assert_eq!(ledger.balance("op", Some("rj")).unwrap(), 500);
    }

    #[test]
    fn debit_if_funds_sequential_debits_serial_correctly() {
        // Simulates the TOCTOU scenario: two debits that each individually
        // would pass a non-atomic pre-check (balance >= amount), but the
        // second must reject because the first already committed. The atomic
        // balance re-read inside BEGIN IMMEDIATE is the gate.
        let ledger = db();
        ledger.ensure_account("op", "wallet").unwrap();
        fund_account(&ledger, "op", "rj", 300, "fund-4");

        let first = ledger
            .debit_if_funds("op", "rj", 200, "debit-a", &serde_json::json!({}))
            .unwrap();
        assert_eq!(first, 100);

        // A second debit of 200 must reject — only 100 remains. A pre-check
        // that read the pre-first-debit balance (300) would have passed.
        let second = ledger.debit_if_funds("op", "rj", 200, "debit-b", &serde_json::json!({}));
        assert!(matches!(
            second,
            Err(LedgerError::InsufficientFunds {
                balance: 100,
                required: 200,
                ..
            })
        ));
        assert_eq!(ledger.balance("op", Some("rj")).unwrap(), 100);
    }
}
