#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! # hKask Ledger — Double-Entry Accounting
//!
//! Immutable double-entry ledger backed by the provider-agnostic `DatabaseDriver`
//! abstraction (ADR-043). Three domain ledgers (cost, crypto, securities) share
//! this crate with separate database files.
//!
//! ## Invariants
//!
//! 1. **Idempotency** — same `reference` with identical postings is a no-op.
//!    Different postings with the same reference return `IdempotencyConflict`.
//! 2. **Double-entry** — every transaction's postings must sum to 0.
//! 3. **Immutability** — committed transactions are never modified or deleted.
//!    DO NOT use INSERT OR REPLACE on the transactions table — it would
//!    cascade-delete postings and retroactively change account balances.

mod schema;
mod types;

pub use types::{DateRange, LedgerError, LedgerTransaction, Posting, QueryFilter};

use hkask_storage::database::driver::DatabaseDriver;
use hkask_storage::database::types::DbError;
use hkask_storage::database::value::DbValue;
use hkask_storage::define_driver_store;
use std::sync::Arc;

// The double-entry ledger.
//
// Backed by a `DatabaseDriver` (ADR-043). `Ledger` is `Send + Sync` and
// can be shared via `Arc`.
//
// `from_driver` and the `driver` accessor are generated by
// `define_driver_store!`. The macro is invoked with `LedgerError` (rather
// than the default `InfrastructureError`) so the generated `from_driver`
// returns the ledger's domain error directly instead of forcing an
// infrastructure-error boundary at the store seam.
define_driver_store!(Ledger, LedgerError);

impl Ledger {
    /// Initialize the ledger schema. Delegates to `schema::init_schema`,
    /// which is idempotent and safe to call on an existing database.
    ///
    /// Called by the macro-generated `from_driver`.
    fn init_schema(driver: &Arc<dyn DatabaseDriver>) -> Result<(), LedgerError> {
        schema::init_schema(driver)
    }

    /// REQ: P8-ledger-ensure-account
    /// expect: "I can create a named account and doing it twice is harmless" \[P8\]
    /// pre:  id and namespace are non-empty strings
    /// post: account exists in the database; second call with same id is a no-op
    /// inv:  idempotent — calling ensure_account twice with same id does not error
    /// \[P8\] Constraining: Persistence — account survives restarts
    pub fn ensure_account(&self, id: &str, namespace: &str) -> Result<(), LedgerError> {
        let now = chrono::Utc::now().to_rfc3339();
        self.driver.execute(
            "INSERT OR IGNORE INTO accounts (id, namespace, created_at) VALUES (?1, ?2, ?3)",
            &[
                DbValue::Text(id.to_string()),
                DbValue::Text(namespace.to_string()),
                DbValue::Text(now),
            ],
        )?;
        Ok(())
    }

    /// REQ: P8-ledger-commit
    /// expect: "I can commit a transaction and the postings are stored immutably" \[P8\]
    /// pre:  tx.id is unique, tx.reference is unique, tx.postings is non-empty
    /// post: transaction and all postings are stored; balances reflect new postings
    /// inv:  idempotent by reference — identical postings succeed silently;
    ///       different postings with same reference return IdempotencyConflict
    /// \[P4\] Constraining: Clear Boundaries — committed transactions cannot be modified
    /// \[P8\] Constraining: Persistence — committed data survives restarts
    pub fn commit(&self, tx: &LedgerTransaction) -> Result<(), LedgerError> {
        if tx.postings.is_empty() {
            return Err(LedgerError::DoubleEntryViolation(0));
        }

        let now = chrono::Utc::now().to_rfc3339();

        // Check if this reference already exists
        let existing = self.driver.query_optional(
            "SELECT id FROM transactions WHERE reference = ?1",
            &[DbValue::Text(tx.reference.clone())],
        )?;

        if let Some(row) = existing {
            let existing_id = row.get_str(0)?.to_string();
            // Reference exists — verify the postings match for true idempotency
            let existing_postings = self.driver.query(
                "SELECT source, destination, asset, amount
                 FROM postings WHERE transaction_id = ?1 ORDER BY id",
                &[DbValue::Text(existing_id)],
            )?;

            if existing_postings.len() != tx.postings.len() {
                return Err(LedgerError::IdempotencyConflict {
                    reference: tx.reference.clone(),
                });
            }
            for (i, p) in tx.postings.iter().enumerate() {
                let row = &existing_postings[i];
                let src = row.get_str(0)?;
                let dst = row.get_str(1)?;
                let ast = row.get_str(2)?;
                let amt = row.get_int(3)?;
                if p.source != src || p.destination != dst || p.asset != ast || p.amount != amt {
                    return Err(LedgerError::IdempotencyConflict {
                        reference: tx.reference.clone(),
                    });
                }
            }
            // Postings match — true idempotent, no-op
            return Ok(());
        }

        // Wrap in transaction for atomicity
        self.driver.execute_batch("BEGIN IMMEDIATE")?;
        let result: Result<(), LedgerError> = (|| {
            self.driver.execute(
                "INSERT INTO transactions (id, timestamp, reference, metadata, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                &[
                    DbValue::Text(tx.id.clone()),
                    DbValue::Text(tx.timestamp.clone()),
                    DbValue::Text(tx.reference.clone()),
                    DbValue::Text(tx.metadata.to_string()),
                    DbValue::Text(now.clone()),
                ],
            )?;

            for posting in &tx.postings {
                self.driver.execute(
                    "INSERT INTO postings (transaction_id, source, destination, asset, amount, created_at)
                     VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                    &[
                        DbValue::Text(tx.id.clone()),
                        DbValue::Text(posting.source.clone()),
                        DbValue::Text(posting.destination.clone()),
                        DbValue::Text(posting.asset.clone()),
                        DbValue::Integer(posting.amount),
                        DbValue::Text(now.clone()),
                    ],
                )?;
            }
            Ok(())
        })();
        match result {
            Ok(()) => {
                self.driver.execute_batch("COMMIT")?;
                Ok(())
            }
            Err(e) => {
                if let Err(rollback_err) = self.driver.execute_batch("ROLLBACK") {
                    tracing::error!(
                        target: "reg.ledger",
                        error = %rollback_err,
                        "Failed to rollback ledger transaction"
                    );
                }
                Err(e)
            }
        }
    }

    /// Atomically debit `amount` of `asset` from `account` to `external`,
    /// enforcing the non-negative balance invariant.
    ///
    /// The balance check and the posting insert happen inside a single
    /// `BEGIN IMMEDIATE` transaction. `BEGIN IMMEDIATE` acquires the write
    /// lock before the balance read, so two concurrent `debit_if_funds`
    /// calls serialize: the first commits its debit, the second re-reads the
    /// now-reduced balance and rejects if it has dropped below `amount`.
    /// This closes the TOCTOU window that a separate check-then-commit path
    /// leaves open (both callers read the pre-debit balance, both commit,
    /// the account goes negative).
    ///
    /// `reference` must be unique (it backs the transactions.reference
    /// UNIQUE constraint); callers mint a fresh UUID per debit. `metadata` is
    /// stored verbatim on the committed transaction (e.g. `{"action":"debit"}`).
    ///
    /// Returns the post-debit balance of `(account, asset)`, or
    /// `Err(InsufficientFunds)` if the balance (read inside the transaction)
    /// is less than `amount`.
    pub fn debit_if_funds(
        &self,
        account: &str,
        asset: &str,
        amount: i64,
        reference: &str,
        metadata: &serde_json::Value,
    ) -> Result<i64, LedgerError> {
        if amount <= 0 {
            return Err(LedgerError::InsufficientFunds {
                account: account.to_string(),
                asset: asset.to_string(),
                balance: 0,
                required: amount,
            });
        }

        let tx_id = uuid::Uuid::new_v4().to_string();
        let now = chrono::Utc::now().to_rfc3339();

        // Acquire the write lock up front. Any concurrent writer (another
        // debit, a commit) blocks until this transaction finishes, so the
        // balance read below sees the committed effect of all prior writers.
        self.driver.execute_batch("BEGIN IMMEDIATE")?;
        let result: Result<(), LedgerError> = (|| {
            // Re-read the balance INSIDE the transaction. The write lock
            // guarantees no other writer can land a debit between this read
            // and the insert below.
            let row = self.driver.query_optional(
                "SELECT COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE (source = ?1 OR destination = ?1) AND asset = ?2",
                &[
                    DbValue::Text(account.to_string()),
                    DbValue::Text(asset.to_string()),
                ],
            )?;
            let balance = match row {
                Some(r) => r.get_int(0)?,
                None => 0,
            };
            if balance < amount {
                return Err(LedgerError::InsufficientFunds {
                    account: account.to_string(),
                    asset: asset.to_string(),
                    balance,
                    required: amount,
                });
            }

            self.driver.execute(
                "INSERT INTO transactions (id, timestamp, reference, metadata, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                &[
                    DbValue::Text(tx_id.clone()),
                    DbValue::Text(now.clone()),
                    DbValue::Text(reference.to_string()),
                    DbValue::Text(metadata.to_string()),
                    DbValue::Text(now.clone()),
                ],
            )?;
            self.driver.execute(
                "INSERT INTO postings (transaction_id, source, destination, asset, amount, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                &[
                    DbValue::Text(tx_id),
                    DbValue::Text(account.to_string()),
                    DbValue::Text("external".to_string()),
                    DbValue::Text(asset.to_string()),
                    DbValue::Integer(amount),
                    DbValue::Text(now),
                ],
            )?;
            Ok(())
        })();
        match result {
            Ok(()) => {
                self.driver.execute_batch("COMMIT")?;
            }
            Err(e) => {
                if let Err(rollback_err) = self.driver.execute_batch("ROLLBACK") {
                    tracing::error!(
                        target: "reg.ledger",
                        error = %rollback_err,
                        "Failed to rollback debit_if_funds transaction"
                    );
                }
                return Err(e);
            }
        }

        self.balance(account, Some(asset))
    }

    /// REQ: P9-ledger-balance
    /// expect: "I can query the balance of any account and see all credits minus debits" \[P9\]
    /// pre:  account is a valid account ID (may or may not exist)
    /// post: returns sum(destination amounts) - sum(source amounts) for matching asset
    /// inv:  read-only — does not modify the ledger; non-existent account returns 0
    /// \[P9\] Constraining: Observability — balances are visible to the user
    pub fn balance(&self, account: &str, asset: Option<&str>) -> Result<i64, LedgerError> {
        let (sql, params) = if let Some(a) = asset {
            (
                "SELECT
                        COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE (source = ?1 OR destination = ?1) AND asset = ?2",
                vec![
                    DbValue::Text(account.to_string()),
                    DbValue::Text(a.to_string()),
                ],
            )
        } else {
            (
                "SELECT
                        COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE source = ?1 OR destination = ?1",
                vec![DbValue::Text(account.to_string())],
            )
        };
        let row = self.driver.query_optional(sql, &params)?;
        // No row → account has no postings → balance is legitimately 0.
        // A get_int error on a present row is a real DB failure and must
        // propagate rather than read as a zero balance.
        let balance = match row {
            Some(r) => r.get_int(0)?,
            None => 0,
        };
        Ok(balance)
    }

    /// REQ: P9-ledger-transaction-count
    /// expect: "I can count how many transactions reference a specific account" \[P9\]
    /// pre:  destination is a valid account ID
    /// post: returns count of unique transactions with a posting to that account
    /// inv:  read-only
    /// \[P9\] Constraining: Observability — transaction volume is queryable
    pub fn transaction_count(&self, destination: &str) -> Result<u64, LedgerError> {
        let row = self.driver.query_optional(
            "SELECT COUNT(DISTINCT transaction_id) FROM postings WHERE destination = ?1",
            &[DbValue::Text(destination.to_string())],
        )?;
        // No row → no transactions for this account → count is legitimately 0.
        // A get_int error on a present row must propagate rather than read as
        // a zero count.
        let count = match row {
            Some(r) => r.get_int(0)?,
            None => 0,
        };
        Ok(u64::try_from(count).unwrap_or_else(|_| {
            tracing::warn!(target: "ledger", count, "Negative transaction count from database — clamping to 0");
            0
        }))
    }

    /// REQ: P9-ledger-query
    /// expect: "I can query transactions by time range and filter by account or asset" \[P9\]
    /// pre:  range.start <= range.end (ISO 8601 strings)
    /// post: returns all transactions whose timestamp falls within the range,
    ///       filtered by optional account/asset/namespace criteria
    /// inv:  read-only; returns empty vec if no matches
    /// \[P9\] Constraining: Observability — transaction history is queryable
    pub fn query(
        &self,
        range: &DateRange,
        filter: &QueryFilter,
    ) -> Result<Vec<LedgerTransaction>, LedgerError> {
        // Build query with parameterized conditions
        let mut conditions = vec!["t.timestamp >= ?1 AND t.timestamp <= ?2".to_string()];
        if filter.account.is_some() {
            conditions.push("(p.source = ?3 OR p.destination = ?3)".to_string());
        }
        if filter.asset.is_some() {
            let idx = if filter.account.is_some() { 4 } else { 3 };
            conditions.push(format!("p.asset = ?{idx}"));
        }
        if filter.namespace.is_some() {
            let idx = 3 + filter.account.is_some() as usize + filter.asset.is_some() as usize;
            conditions.push(format!(
                "EXISTS (SELECT 1 FROM accounts a WHERE (a.id = p.source OR a.id = p.destination) AND a.namespace = ?{idx})"
            ));
        }

        let sql = format!(
            "SELECT DISTINCT t.id, t.timestamp, t.reference, t.metadata, t.created_at
             FROM transactions t
             JOIN postings p ON p.transaction_id = t.id
             WHERE {}
             ORDER BY t.timestamp, t.id",
            conditions.join(" AND ")
        );

        let params = build_query_params(range, filter);
        let tx_rows = self.driver.query(&sql, &params)?;

        // For each transaction, load its postings
        let mut result = Vec::new();
        for row in tx_rows {
            let id = row.get_str(0)?.to_string();
            let timestamp = row.get_str(1)?.to_string();
            let reference = row.get_str(2)?.to_string();
            let metadata_str = row.get_str(3)?.to_string();

            let postings = self.driver.query(
                "SELECT source, destination, asset, amount
                 FROM postings WHERE transaction_id = ?1 ORDER BY id",
                &[DbValue::Text(id.clone())],
            )?;

            let postings: Vec<Posting> = postings
                .iter()
                .map(|p| {
                    Ok(Posting {
                        source: p.get_str(0)?.to_string(),
                        destination: p.get_str(1)?.to_string(),
                        asset: p.get_str(2)?.to_string(),
                        amount: p.get_int(3)?,
                    })
                })
                .collect::<Result<Vec<_>, DbError>>()?;

            let tx_id = id.clone();
            result.push(LedgerTransaction {
                id,
                timestamp,
                reference,
                postings,
                metadata: serde_json::from_str(&metadata_str).unwrap_or_else(|e| {
                    tracing::warn!(target: "ledger", error = %e, transaction_id = %tx_id, "Corrupted metadata JSON");
                    serde_json::Value::Null
                }),
            });
        }

        Ok(result)
    }
}

/// Build parameter list for the query() method.
fn build_query_params(range: &DateRange, filter: &QueryFilter) -> Vec<DbValue> {
    let mut params: Vec<DbValue> = vec![
        DbValue::Text(range.start.clone()),
        DbValue::Text(range.end.clone()),
    ];
    if let Some(ref account) = filter.account {
        params.push(DbValue::Text(account.clone()));
    }
    if let Some(ref asset) = filter.asset {
        params.push(DbValue::Text(asset.clone()));
    }
    if let Some(ref ns) = filter.namespace {
        params.push(DbValue::Text(ns.clone()));
    }
    params
}
