#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! # hKask Ledger — Double-Entry Accounting
//!
//! Immutable double-entry ledger backed by the provider-agnostic `DatabaseDriver`
//! abstraction (ADR-043). Three domain ledgers (cost, crypto, securities) share
//! this crate with separate database files.
//!
//! ## Invariants
//!
//! 1. **Idempotency** — same `reference` with identical postings is a no-op.
//!    Different postings with the same reference return `IdempotencyConflict`.
//! 2. **Double-entry** — every transaction's postings must sum to 0.
//! 3. **Immutability** — committed transactions are never modified or deleted.
//!    DO NOT use INSERT OR REPLACE on the transactions table — it would
//!    cascade-delete postings and retroactively change account balances.

mod schema;
mod types;

pub use types::{DateRange, LedgerError, LedgerTransaction, Posting, QueryFilter};

use hkask_storage::database::driver::DatabaseDriver;
use hkask_storage::database::types::DbError;
use hkask_storage::database::value::DbValue;
use hkask_storage::define_driver_store;
use rusqlite::{OptionalExtension, Transaction, TransactionBehavior, params};
use std::sync::Arc;

// The double-entry ledger.
//
// Backed by a `DatabaseDriver` (ADR-043). `Ledger` is `Send + Sync` and
// can be shared via `Arc`.
//
// `from_driver` and the `driver` accessor are generated by
// `define_driver_store!`. The macro is invoked with `LedgerError` (rather
// than the default `InfrastructureError`) so the generated `from_driver`
// returns the ledger's domain error directly instead of forcing an
// infrastructure-error boundary at the store seam.
define_driver_store!(Ledger, LedgerError);

impl Ledger {
    /// Initialize the ledger schema. Delegates to `schema::init_schema`,
    /// which is idempotent and safe to call on an existing database.
    ///
    /// Called by the macro-generated `from_driver`.
    fn init_schema(driver: &Arc<dyn DatabaseDriver>) -> Result<(), LedgerError> {
        schema::init_schema(driver)
    }

    /// REQ: P8-ledger-ensure-account
    /// expect: "I can create a named account and doing it twice is harmless" \[P8\]
    /// pre:  id and namespace are non-empty strings
    /// post: account exists in the database; second call with same id is a no-op
    /// inv:  idempotent — calling ensure_account twice with same id does not error
    /// \[P8\] Constraining: Persistence — account survives restarts
    pub fn ensure_account(&self, id: &str, namespace: &str) -> Result<(), LedgerError> {
        let now = chrono::Utc::now().to_rfc3339();
        self.driver.execute(
            "INSERT OR IGNORE INTO accounts (id, namespace, created_at) VALUES (?1, ?2, ?3)",
            &[
                DbValue::Text(id.to_string()),
                DbValue::Text(namespace.to_string()),
                DbValue::Text(now),
            ],
        )?;
        Ok(())
    }

    /// REQ: P8-ledger-commit
    /// expect: "I can commit a transaction and the postings are stored immutably" \[P8\]
    /// pre:  tx.id is unique, tx.reference is unique, tx.postings is non-empty
    /// post: transaction and all postings are stored; balances reflect new postings
    /// inv:  idempotent by reference — identical postings succeed silently;
    ///       different postings with same reference return IdempotencyConflict
    /// \[P4\] Constraining: Clear Boundaries — committed transactions cannot be modified
    /// \[P8\] Constraining: Persistence — committed data survives restarts
    pub fn commit(&self, tx: &LedgerTransaction) -> Result<(), LedgerError> {
        if tx.postings.is_empty() {
            return Err(LedgerError::DoubleEntryViolation(0));
        }

        let now = chrono::Utc::now().to_rfc3339();

        self.with_transaction(|transaction| {
            // The reference check shares the write lock with insertion: concurrent
            // identical commits must observe a no-op, not a UNIQUE violation.
            let existing: Option<String> = transaction.query_row(
                "SELECT id FROM transactions WHERE reference = ?1",
                [&tx.reference],
                |row| row.get(0),
            ).optional()?;
            if let Some(existing_id) = existing {
                let mut statement = transaction.prepare(
                    "SELECT source, destination, asset, amount
                     FROM postings WHERE transaction_id = ?1 ORDER BY id",
                )?;
                let existing_postings = statement.query_map([existing_id], |row| {
                    Ok(Posting {
                        source: row.get(0)?,
                        destination: row.get(1)?,
                        asset: row.get(2)?,
                        amount: row.get(3)?,
                    })
                })?.collect::<Result<Vec<_>, _>>()?;
                if existing_postings.len() != tx.postings.len()
                    || existing_postings.iter().zip(&tx.postings).any(|(existing, proposed)| {
                        existing.source != proposed.source
                            || existing.destination != proposed.destination
                            || existing.asset != proposed.asset
                            || existing.amount != proposed.amount
                    })
                {
                    return Err(LedgerError::IdempotencyConflict { reference: tx.reference.clone() });
                }
                return Ok(());
            }
            transaction.execute(
                "INSERT INTO transactions (id, timestamp, reference, metadata, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                params![tx.id, tx.timestamp, tx.reference, tx.metadata.to_string(), now],
            )?;
            for posting in &tx.postings {
                transaction.execute(
                    "INSERT INTO postings (transaction_id, source, destination, asset, amount, created_at)
                     VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                    params![tx.id, posting.source, posting.destination, posting.asset, posting.amount, now],
                )?;
            }
            Ok(())
        })
    }

    /// Atomically debit `amount` of `asset` from `account` to `external`,
    /// enforcing the non-negative balance invariant.
    ///
    /// The balance check and the posting insert happen inside a single
    /// `BEGIN IMMEDIATE` transaction. `BEGIN IMMEDIATE` acquires the write
    /// lock before the balance read, so two concurrent `debit_if_funds`
    /// calls serialize: the first commits its debit, the second re-reads the
    /// now-reduced balance and rejects if it has dropped below `amount`.
    /// This closes the TOCTOU window that a separate check-then-commit path
    /// leaves open (both callers read the pre-debit balance, both commit,
    /// the account goes negative).
    ///
    /// `reference` must be unique (it backs the transactions.reference
    /// UNIQUE constraint); callers mint a fresh UUID per debit. `metadata` is
    /// stored verbatim on the committed transaction (e.g. `{"action":"debit"}`).
    ///
    /// Returns the post-debit balance of `(account, asset)`, or
    /// `Err(InsufficientFunds)` if the balance (read inside the transaction)
    /// is less than `amount`.
    pub fn debit_if_funds(
        &self,
        account: &str,
        asset: &str,
        amount: i64,
        reference: &str,
        metadata: &serde_json::Value,
    ) -> Result<i64, LedgerError> {
        if amount <= 0 {
            return Err(LedgerError::InsufficientFunds {
                account: account.to_string(),
                asset: asset.to_string(),
                balance: 0,
                required: amount,
            });
        }

        let tx_id = uuid::Uuid::new_v4().to_string();
        let now = chrono::Utc::now().to_rfc3339();

        // Acquire the write lock up front. Any concurrent writer (another
        // debit, a commit) blocks until this transaction finishes, so the
        // balance read below sees the committed effect of all prior writers.
        self.with_transaction(|transaction| {
            let balance: i64 = transaction.query_row(
                "SELECT COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE (source = ?1 OR destination = ?1) AND asset = ?2",
                params![account, asset],
                |row| row.get(0),
            )?;
            if balance < amount {
                return Err(LedgerError::InsufficientFunds {
                    account: account.to_string(),
                    asset: asset.to_string(),
                    balance,
                    required: amount,
                });
            }

            transaction.execute(
                "INSERT INTO transactions (id, timestamp, reference, metadata, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5)",
                params![tx_id, now, reference, metadata.to_string(), now],
            )?;
            transaction.execute(
                "INSERT INTO postings (transaction_id, source, destination, asset, amount, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                params![tx_id, account, "external", asset, amount, now],
            )?;
            // Return this debit's balance, not a later writer's observation.
            Ok(if account == "external" { balance } else { balance - amount })
        })
    }

    fn with_transaction<T>(
        &self,
        operation: impl FnOnce(&Transaction<'_>) -> Result<T, LedgerError>,
    ) -> Result<T, LedgerError> {
        let pool = self.driver.sqlite_pool().ok_or_else(|| {
            DbError::Database("Ledger transactions require a SqliteDriver".into())
        })?;
        let mut connection = pool
            .get()
            .map_err(|error| DbError::Connection(error.to_string()))?;
        let transaction = connection.transaction_with_behavior(TransactionBehavior::Immediate)?;
        let result = operation(&transaction);
        match result {
            Ok(value) => {
                transaction.commit()?;
                tracing::debug!(target: "reg.ledger", "Ledger transaction committed");
                Ok(value)
            }
            Err(error) => {
                if let Err(rollback_error) = transaction.rollback() {
                    tracing::error!(target: "reg.ledger", error = %rollback_error, "Failed to rollback ledger transaction");
                }
                Err(error)
            }
        }
    }

    /// REQ: P9-ledger-balance
    /// expect: "I can query the balance of any account and see all credits minus debits" \[P9\]
    /// pre:  account is a valid account ID (may or may not exist)
    /// post: returns sum(destination amounts) - sum(source amounts) for matching asset
    /// inv:  read-only — does not modify the ledger; non-existent account returns 0
    /// \[P9\] Constraining: Observability — balances are visible to the user
    pub fn balance(&self, account: &str, asset: Option<&str>) -> Result<i64, LedgerError> {
        let (sql, params) = if let Some(a) = asset {
            (
                "SELECT
                        COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE (source = ?1 OR destination = ?1) AND asset = ?2",
                vec![
                    DbValue::Text(account.to_string()),
                    DbValue::Text(a.to_string()),
                ],
            )
        } else {
            (
                "SELECT
                        COALESCE(SUM(CASE WHEN destination = ?1 THEN amount ELSE 0 END), 0)
                      - COALESCE(SUM(CASE WHEN source = ?1 THEN amount ELSE 0 END), 0)
                     FROM postings WHERE source = ?1 OR destination = ?1",
                vec![DbValue::Text(account.to_string())],
            )
        };
        let row = self.driver.query_optional(sql, &params)?;
        // No row → account has no postings → balance is legitimately 0.
        // A get_int error on a present row is a real DB failure and must
        // propagate rather than read as a zero balance.
        let balance = match row {
            Some(r) => r.get_int(0)?,
            None => 0,
        };
        Ok(balance)
    }

    /// REQ: P9-ledger-query
    /// expect: "I can query transactions by time range and filter by account or asset" \[P9\]
    /// pre:  range.start <= range.end (ISO 8601 strings)
    /// post: returns all transactions whose timestamp falls within the range,
    ///       filtered by optional account/asset/namespace criteria
    /// inv:  read-only; returns empty vec if no matches
    /// \[P9\] Constraining: Observability — transaction history is queryable
    pub fn query(
        &self,
        range: &DateRange,
        filter: &QueryFilter,
    ) -> Result<Vec<LedgerTransaction>, LedgerError> {
        // Build query with parameterized conditions
        let mut conditions = vec!["t.timestamp >= ?1 AND t.timestamp <= ?2".to_string()];
        if filter.account.is_some() {
            conditions.push("(p.source = ?3 OR p.destination = ?3)".to_string());
        }
        if filter.asset.is_some() {
            let idx = if filter.account.is_some() { 4 } else { 3 };
            conditions.push(format!("p.asset = ?{idx}"));
        }
        if filter.namespace.is_some() {
            let idx = 3 + filter.account.is_some() as usize + filter.asset.is_some() as usize;
            conditions.push(format!(
                "EXISTS (SELECT 1 FROM accounts a WHERE (a.id = p.source OR a.id = p.destination) AND a.namespace = ?{idx})"
            ));
        }

        let sql = format!(
            "SELECT DISTINCT t.id, t.timestamp, t.reference, t.metadata, t.created_at
             FROM transactions t
             JOIN postings p ON p.transaction_id = t.id
             WHERE {}
             ORDER BY t.timestamp, t.id",
            conditions.join(" AND ")
        );

        let params = build_query_params(range, filter);
        let tx_rows = self.driver.query(&sql, &params)?;

        // For each transaction, load its postings
        let mut result = Vec::new();
        for row in tx_rows {
            let id = row.get_str(0)?.to_string();
            let timestamp = row.get_str(1)?.to_string();
            let reference = row.get_str(2)?.to_string();
            let metadata_str = row.get_str(3)?.to_string();

            let postings = self.driver.query(
                "SELECT source, destination, asset, amount
                 FROM postings WHERE transaction_id = ?1 ORDER BY id",
                &[DbValue::Text(id.clone())],
            )?;

            let postings: Vec<Posting> = postings
                .iter()
                .map(|p| {
                    Ok(Posting {
                        source: p.get_str(0)?.to_string(),
                        destination: p.get_str(1)?.to_string(),
                        asset: p.get_str(2)?.to_string(),
                        amount: p.get_int(3)?,
                    })
                })
                .collect::<Result<Vec<_>, DbError>>()?;

            let tx_id = id.clone();
            result.push(LedgerTransaction {
                id,
                timestamp,
                reference,
                postings,
                metadata: serde_json::from_str(&metadata_str).unwrap_or_else(|e| {
                    tracing::warn!(target: "ledger", error = %e, transaction_id = %tx_id, "Corrupted metadata JSON");
                    serde_json::Value::Null
                }),
            });
        }

        Ok(result)
    }
}

/// Build parameter list for the query() method.
fn build_query_params(range: &DateRange, filter: &QueryFilter) -> Vec<DbValue> {
    let mut params: Vec<DbValue> = vec![
        DbValue::Text(range.start.clone()),
        DbValue::Text(range.end.clone()),
    ];
    if let Some(ref account) = filter.account {
        params.push(DbValue::Text(account.clone()));
    }
    if let Some(ref asset) = filter.asset {
        params.push(DbValue::Text(asset.clone()));
    }
    if let Some(ref ns) = filter.namespace {
        params.push(DbValue::Text(ns.clone()));
    }
    params
}

#[cfg(test)]
mod tests {
    use super::*;
    use hkask_storage::database::sqlite::{SqliteDriver, init_wal_pragmas};
    use std::sync::Barrier;

    fn fixture() -> (tempfile::TempDir, Arc<Ledger>) {
        let directory = tempfile::tempdir().expect("temporary ledger directory");
        let manager =
            hkask_storage::SqliteConnectionManager::file(directory.path().join("ledger.db"))
                .with_init(|connection| {
                    init_wal_pragmas(connection)?;
                    connection.execute_batch("PRAGMA foreign_keys = ON;")?;
                    connection.busy_timeout(std::time::Duration::from_secs(3))
                });
        let pool = r2d2::Pool::builder()
            .max_size(4)
            .build(manager)
            .expect("four-connection pool");
        let ledger = Ledger::from_driver(Arc::new(SqliteDriver::new(pool))).expect("ledger schema");
        (directory, Arc::new(ledger))
    }

    fn funding(reference: &str, amount: i64) -> LedgerTransaction {
        LedgerTransaction {
            id: uuid::Uuid::new_v4().to_string(),
            reference: reference.to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
            metadata: serde_json::json!({}),
            postings: vec![Posting {
                source: "external".into(),
                destination: "operator".into(),
                asset: "credits".into(),
                amount,
            }],
        }
    }

    /// expect: "Concurrent pool users cannot split ledger transactions or double-charge references" [P8]
    #[test]
    fn ledger_commit_isolated_from_concurrent_pool_users() {
        let (_directory, ledger) = fixture();
        ledger
            .commit(&funding("initial", 100))
            .expect("initial funding");
        let barrier = Arc::new(Barrier::new(9));
        let mut workers = Vec::new();
        for worker in 0..9 {
            let ledger = ledger.clone();
            let barrier = barrier.clone();
            workers.push(std::thread::spawn(move || -> Result<(), LedgerError> {
                barrier.wait();
                for iteration in 0..5 {
                    if worker < 4 {
                        ledger.commit(&funding(&format!("fund-{iteration}"), 10))?;
                    } else if worker < 8 {
                        let balance = ledger.debit_if_funds(
                            "operator",
                            "credits",
                            3,
                            &format!("debit-{worker}-{iteration}"),
                            &serde_json::json!({}),
                        )?;
                        assert!(balance >= 0);
                    } else {
                        assert!(ledger.balance("operator", Some("credits"))? >= 0);
                    }
                }
                Ok(())
            }));
        }
        // Join every worker even when one fails, so temporary storage outlives all users.
        let results: Vec<_> = workers.into_iter().map(|worker| worker.join()).collect();
        for result in results {
            result
                .expect("worker does not panic")
                .expect("operation remains atomic");
        }
        assert_eq!(
            ledger
                .balance("operator", Some("credits"))
                .expect("balance"),
            90
        );
        let count = ledger
            .driver
            .query_optional("SELECT COUNT(*) FROM transactions", &[])
            .expect("transaction count")
            .expect("count row")
            .get_int(0)
            .expect("integer count");
        assert_eq!(count, 26);
        let conflict = funding("fund-0", 11);
        assert!(matches!(
            ledger.commit(&conflict),
            Err(LedgerError::IdempotencyConflict { .. })
        ));
    }

    /// expect: "Concurrent debits cannot spend more than the available balance" [P8]
    #[test]
    fn concurrent_debits_preserve_nonnegative_balance() {
        let (_directory, ledger) = fixture();
        ledger
            .commit(&funding("initial", 10))
            .expect("initial funding");
        let barrier = Arc::new(Barrier::new(2));
        let workers: Vec<_> = (0..2)
            .map(|index| {
                let ledger = ledger.clone();
                let barrier = barrier.clone();
                std::thread::spawn(move || {
                    barrier.wait();
                    ledger.debit_if_funds(
                        "operator",
                        "credits",
                        7,
                        &format!("debit-{index}"),
                        &serde_json::json!({}),
                    )
                })
            })
            .collect();
        let results: Vec<_> = workers
            .into_iter()
            .map(|worker| worker.join().expect("worker"))
            .collect();
        assert_eq!(
            results
                .iter()
                .filter(|result| matches!(result, Ok(3)))
                .count(),
            1
        );
        assert_eq!(
            results
                .iter()
                .filter(|result| matches!(
                    result,
                    Err(LedgerError::InsufficientFunds { balance: 3, .. })
                ))
                .count(),
            1
        );
        assert_eq!(
            ledger
                .balance("operator", Some("credits"))
                .expect("balance"),
            3
        );
    }

    /// expect: "A failed posting rolls back its header and earlier postings, not another operation" [P8]
    #[test]
    fn failed_posting_rolls_back_entire_transaction() {
        let (_directory, ledger) = fixture();
        ledger.driver.execute_batch(
            "CREATE TRIGGER reject_test_posting BEFORE INSERT ON postings WHEN NEW.amount = 9999
             BEGIN SELECT RAISE(ABORT, 'injected posting failure'); END;",
        ).expect("failure injection");
        ledger
            .commit(&funding("retained", 20))
            .expect("independent transaction");
        let mut transaction = funding("failed", 5);
        transaction
            .postings
            .push(funding("unused", 9999).postings.remove(0));
        assert!(ledger.commit(&transaction).is_err());
        assert!(
            ledger
                .driver
                .query_optional(
                    "SELECT id FROM transactions WHERE reference = 'failed'",
                    &[]
                )
                .expect("query header")
                .is_none()
        );
        assert_eq!(
            ledger
                .balance("operator", Some("credits"))
                .expect("balance"),
            20
        );
        ledger
            .commit(&funding("after-failure", 10))
            .expect("pool remains usable");
        assert_eq!(
            ledger
                .balance("operator", Some("credits"))
                .expect("balance"),
            30
        );
    }
}
