//! Ed25519 signing and verification for skill marketplace manifests.
//!
//! Publishers sign their manifests with an Ed25519 keypair. The signature and
//! public key travel with the manifest in S3. The collab server verifies
//! signatures on upload and poll; the client verifies on install.
//!
//! Key lifecycle: keys are generated by the publisher, stored in the OS
//! keychain, and expire 120 days after the server first sees the public key
//! (server-side `first_seen_at`). After expiration, all skills published
//! under that key are purged from the catalog. The publisher must generate
//! a new key and re-publish to keep skills alive.

use ed25519_dalek::{Signature, SigningKey, VerifyingKey};
use hkask_types::{Ed25519PublicKey, Ed25519Signature};
use rand::RngCore;
use zeroize::Zeroizing;

/// Maximum age of a publisher key before it expires and its skills are purged.
///
/// The server records `first_seen_at` when it first encounters a public key.
/// After this many days, the key is expired and all skills published under
/// it are removed from the catalog. The publisher must generate a new key
/// and re-publish to keep skills alive.
pub const KEY_MAX_AGE_DAYS: u64 = 120;

/// Generate a new Ed25519 signing keypair.
///
/// Returns a `SigningKey` (32-byte secret key) wrapped in `Zeroizing`.
/// Use `derive_public_key` to get the corresponding public key.
#[must_use]
pub fn generate_signing_keypair() -> Zeroizing<SigningKey> {
    let mut secret_bytes = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut secret_bytes);
    let signing_key = SigningKey::from_bytes(&secret_bytes);
    Zeroizing::new(signing_key)
}

/// Derive the public key from a signing key.
#[must_use]
pub fn derive_public_key(signing_key: &SigningKey) -> Ed25519PublicKey {
    let verifying_key = signing_key.verifying_key();
    Ed25519PublicKey(*verifying_key.as_bytes())
}

/// Sign arbitrary bytes with an Ed25519 signing key.
///
/// The signature is deterministic (RFC 8032) — the same input and key
/// always produce the same signature.
#[must_use]
pub fn sign(message: &[u8], signing_key: &SigningKey) -> Ed25519Signature {
    let signature: Signature = signing_key.sign(message);
    Ed25519Signature(signature.to_bytes())
}

/// Verify an Ed25519 signature against a public key.
///
/// Returns `true` if the signature is valid, `false` otherwise.
/// This function never panics — invalid keys or signatures return `false`.
#[must_use]
pub fn verify(message: &[u8], signature: &Ed25519Signature, public_key: &Ed25519PublicKey) -> bool {
    let Ok(verifying_key) = VerifyingKey::from_bytes(public_key.as_bytes()) else {
        return false;
    };
    let Ok(sig) = Signature::from_slice(signature.as_bytes()) else {
        return false;
    };
    verifying_key.verify_strict(message, &sig).is_ok()
}

/// Convert an `Ed25519PublicKey` to an `ed25519_dalek::VerifyingKey`.
///
/// Returns `None` if the key bytes are invalid (all-zero, etc.).
pub fn to_verifying_key(public_key: &Ed25519PublicKey) -> Option<VerifyingKey> {
    VerifyingKey::from_bytes(public_key.as_bytes()).ok()
}

/// Convert an `Ed25519Signature` to an `ed25519_dalek::Signature`.
pub fn to_dalek_signature(signature: &Ed25519Signature) -> Signature {
    Signature::from_bytes(signature.as_bytes())
}

/// Store a publisher's Ed25519 signing key in the OS keychain.
///
/// The key is stored as a hex string under `kask://signing-keys/{publisher}`.
/// The keychain service name is the default `hkask` (same as DB passphrase).
pub fn store_signing_key(
    publisher: &str,
    signing_key: &SigningKey,
) -> Result<(), crate::keychain::KeychainError> {
    let keychain = crate::keychain::Keychain::default();
    let key_hex = hex::encode(signing_key.to_bytes());
    keychain.store_by_key(&format!("signing-keys/{publisher}"), &key_hex)
}

/// Load a publisher's Ed25519 signing key from the OS keychain.
///
/// Returns `None` if no key is stored for this publisher.
pub fn load_signing_key(publisher: &str) -> Option<SigningKey> {
    let keychain = crate::keychain::Keychain::default();
    match keychain.retrieve_by_key(&format!("signing-keys/{publisher}")) {
        Ok(key_hex) => {
            let bytes = hex::decode(&key_hex).ok()?;
            if bytes.len() != 32 {
                return None;
            }
            let mut arr = [0u8; 32];
            arr.copy_from_slice(&bytes);
            Some(SigningKey::from_bytes(&arr))
        }
        Err(_) => None,
    }
}

/// Delete a publisher's Ed25519 signing key from the OS keychain.
pub fn delete_signing_key(publisher: &str) -> Result<(), crate::keychain::KeychainError> {
    let keychain = crate::keychain::Keychain::default();
    keychain.delete_by_key(&format!("signing-keys/{publisher}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sign_and_verify_round_trip() {
        let signing_key = generate_signing_keypair();
        let public_key = derive_public_key(&signing_key);
        let message = b"hello kask skills marketplace";

        let signature = sign(message, &signing_key);
        assert!(verify(message, &signature, &public_key));
    }

    #[test]
    fn verify_rejects_tampered_message() {
        let signing_key = generate_signing_keypair();
        let public_key = derive_public_key(&signing_key);
        let message = b"original message";
        let tampered = b"tampered message";

        let signature = sign(message, &signing_key);
        assert!(!verify(tampered, &signature, &public_key));
    }

    #[test]
    fn verify_rejects_wrong_public_key() {
        let signing_key_a = generate_signing_keypair();
        let signing_key_b = generate_signing_keypair();
        let public_key_b = derive_public_key(&signing_key_b);
        let message = b"signed by key a";

        let signature = sign(message, &signing_key_a);
        assert!(!verify(message, &signature, &public_key_b));
    }

    #[test]
    fn verify_rejects_invalid_public_key() {
        let signing_key = generate_signing_keypair();
        let message = b"some message";
        let signature = sign(message, &signing_key);

        // All-zeros is not a valid Ed25519 public key.
        let invalid_key = Ed25519PublicKey([0u8; 32]);
        assert!(!verify(message, &signature, &invalid_key));
    }

    #[test]
    fn keypair_generation_is_unique() {
        let key_a = generate_signing_keypair();
        let key_b = generate_signing_keypair();
        assert_ne!(key_a.to_bytes(), key_b.to_bytes());
    }

    #[test]
    fn derive_public_key_is_consistent() {
        let signing_key = generate_signing_keypair();
        let public_a = derive_public_key(&signing_key);
        let public_b = derive_public_key(&signing_key);
        assert_eq!(public_a, public_b);
    }

    #[test]
    fn signature_is_deterministic() {
        let signing_key = generate_signing_keypair();
        let message = b"deterministic test";
        let sig_a = sign(message, &signing_key);
        let sig_b = sign(message, &signing_key);
        assert_eq!(sig_a, sig_b);
    }

    #[test]
    fn key_max_age_days_is_120() {
        assert_eq!(KEY_MAX_AGE_DAYS, 120);
    }

    #[test]
    fn ed25519_public_key_from_str_round_trip() {
        let signing_key = generate_signing_keypair();
        let public_key = derive_public_key(&signing_key);
        let hex_str = public_key.to_string();
        let parsed: Ed25519PublicKey = hex_str.parse().unwrap();
        assert_eq!(public_key, parsed);
    }

    #[test]
    fn ed25519_signature_from_str_round_trip() {
        let signing_key = generate_signing_keypair();
        let public_key = derive_public_key(&signing_key);
        let message = b"round trip test";
        let signature = sign(message, &signing_key);
        let hex_str = signature.to_string();
        let parsed: Ed25519Signature = hex_str.parse().unwrap();
        assert_eq!(signature, parsed);
        assert!(verify(message, &parsed, &public_key));
    }
}
