//! Ed25519 signing and verification for skill marketplace manifests.
//!
//! Publishers sign their manifests with an Ed25519 keypair. The signature and
//! public key travel with the manifest in S3. The collab server verifies
//! signatures on upload and poll; the client verifies on install.
//!
//! Key lifecycle ("Kask Skill Signing & Trust Model" plan D2): keys are
//! generated by the publisher and stored in the OS keychain under
//! `signing-keys/{publisher}`. Expiration is set **at signing time** — the
//! manifest carries an `expires_at` (RFC 3339) the signature commits to, and
//! the server accepts `now < expires_at <= now + KEY_MAX_AGE_DAYS`. There is no
//! server-side key registry or `first_seen_at`; only signatures have lifetimes.

use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use hkask_types::{Ed25519PublicKey, Ed25519Signature};
use rand::RngCore;
use zeroize::{Zeroize, Zeroizing};

/// Maximum accepted lifetime of a signed manifest, in days.
///
/// The server rejects any manifest whose `expires_at` is more than this many
/// days in the future (judged by the server clock) and purges manifests whose
/// `expires_at` has passed. The publisher writes `expires_at` at signing time;
/// this constant is the cap the client defaults to.
pub const KEY_MAX_AGE_DAYS: u64 = 120;

/// Generate a new Ed25519 signing keypair.
///
/// Returns a `SigningKey`, whose secret is zeroized on drop by `ed25519_dalek`'s
/// `ZeroizeOnDrop` impl (enabled via the `zeroize` feature). The scratch buffer
/// the key is built from is wiped explicitly — `from_bytes` copies out of it, so
/// without this the raw scalar would outlive the call on the stack.
#[must_use]
pub fn generate_signing_keypair() -> SigningKey {
    let mut secret_bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut secret_bytes);
    let signing_key = SigningKey::from_bytes(&secret_bytes);
    secret_bytes.zeroize();
    signing_key
}

/// Derive the public key from a signing key.
#[must_use]
pub fn derive_public_key(signing_key: &SigningKey) -> Ed25519PublicKey {
    let verifying_key = signing_key.verifying_key();
    Ed25519PublicKey(*verifying_key.as_bytes())
}

/// Sign arbitrary bytes with an Ed25519 signing key.
///
/// The signature is deterministic (RFC 8032) — the same input and key
/// always produce the same signature.
#[must_use]
pub fn sign(message: &[u8], signing_key: &SigningKey) -> Ed25519Signature {
    let signature: Signature = signing_key.sign(message);
    Ed25519Signature(signature.to_bytes())
}

/// Verify an Ed25519 signature against a public key.
///
/// Returns `true` if the signature is valid, `false` otherwise.
/// This function never panics — invalid keys or signatures return `false`.
#[must_use]
pub fn verify(message: &[u8], signature: &Ed25519Signature, public_key: &Ed25519PublicKey) -> bool {
    let Ok(verifying_key) = VerifyingKey::from_bytes(public_key.as_bytes()) else {
        return false;
    };
    let Ok(sig) = Signature::from_slice(signature.as_bytes()) else {
        return false;
    };
    verifying_key.verify_strict(message, &sig).is_ok()
}

/// Convert an `Ed25519PublicKey` to an `ed25519_dalek::VerifyingKey`.
///
/// Returns `None` if the key bytes are invalid (all-zero, etc.).
pub fn to_verifying_key(public_key: &Ed25519PublicKey) -> Option<VerifyingKey> {
    VerifyingKey::from_bytes(public_key.as_bytes()).ok()
}

/// Convert an `Ed25519Signature` to an `ed25519_dalek::Signature`.
pub fn to_dalek_signature(signature: &Ed25519Signature) -> Signature {
    Signature::from_bytes(signature.as_bytes())
}

/// Store a publisher's Ed25519 signing key in the OS keychain.
///
/// The key is stored as a hex string under `kask://signing-keys/{publisher}`.
/// The keychain service name is the default `hkask` (same as DB passphrase).
pub fn store_signing_key(
    publisher: &str,
    signing_key: &SigningKey,
) -> Result<(), crate::keychain::KeychainError> {
    let keychain = crate::keychain::Keychain::default();
    // The hex encoding IS the private scalar in printable form. Wrapping it in
    // `Zeroizing` wipes the heap allocation on drop; a bare `String` here left the
    // raw key in freed memory (RR-0063). Same for the intermediate byte array.
    let mut key_bytes = signing_key.to_bytes();
    let key_hex = Zeroizing::new(hex::encode(key_bytes));
    key_bytes.zeroize();
    keychain.store_by_key(&format!("signing-keys/{publisher}"), &key_hex)
}

/// Load a publisher's Ed25519 signing key from the OS keychain.
///
/// Returns `None` when no key is stored for this publisher. Every other failure
/// mode (keychain unavailable, corrupt hex, wrong key length) also returns `None`
/// but logs a `warn` naming the classification first — collapsing them silently
/// made "this publisher has no key" indistinguishable from "the keychain is
/// broken" or "the stored key is corrupt" (RR-0063).
///
/// All intermediate buffers holding the secret scalar are zeroized.
pub fn load_signing_key(publisher: &str) -> Option<SigningKey> {
    let keychain = crate::keychain::Keychain::default();
    let key_hex = match keychain.retrieve_by_key(&format!("signing-keys/{publisher}")) {
        Ok(key_hex) => Zeroizing::new(key_hex),
        Err(error) => {
            // `NotFound` is the expected "no key configured" case; anything else
            // is an operational failure the caller cannot see from `None`.
            if !matches!(error, crate::keychain::KeychainError::NotFound(_)) {
                tracing::warn!(
                    target: "reg.keystore",
                    publisher = %publisher,
                    error = %error,
                    "signing key load failed - keychain unavailable, not absent"
                );
            }
            return None;
        }
    };

    let mut bytes = match hex::decode(&*key_hex) {
        Ok(bytes) => Zeroizing::new(bytes),
        Err(error) => {
            tracing::warn!(
                target: "reg.keystore",
                publisher = %publisher,
                error = %error,
                "stored signing key is not valid hex - the keychain entry is corrupt"
            );
            return None;
        }
    };

    let Ok(mut key_bytes) = <[u8; 32]>::try_from(bytes.as_slice()) else {
        tracing::warn!(
            target: "reg.keystore",
            publisher = %publisher,
            length = bytes.len(),
            "stored signing key has the wrong length - expected 32 bytes"
        );
        bytes.zeroize();
        return None;
    };
    let signing_key = SigningKey::from_bytes(&key_bytes);
    key_bytes.zeroize();
    Some(signing_key)
}

/// Delete a publisher's Ed25519 signing key from the OS keychain.
pub fn delete_signing_key(publisher: &str) -> Result<(), crate::keychain::KeychainError> {
    let keychain = crate::keychain::Keychain::default();
    keychain.delete_by_key(&format!("signing-keys/{publisher}"))
}
