//! Ed25519 signing and verification for skill marketplace manifests.
//!
//! Publishers sign their manifests with an Ed25519 keypair. The signature and
//! public key travel with the manifest in S3. The collab server verifies
//! signatures on upload and poll; the client verifies on install.
//!
//! Key lifecycle ("Kask Skill Signing & Trust Model" plan D2): keys are
//! generated by the publisher and stored in the OS keychain under
//! `signing-keys/{publisher}`. Expiration is set **at signing time** — the
//! manifest carries an `expires_at` (RFC 3339) the signature commits to, and
//! the server accepts `now < expires_at <= now + KEY_MAX_AGE_DAYS`. There is no
//! server-side key registry or `first_seen_at`; only signatures have lifetimes.

use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use hkask_types::{Ed25519PublicKey, Ed25519Signature};

/// Sign arbitrary bytes with an Ed25519 signing key.
///
/// The signature is deterministic (RFC 8032) — the same input and key
/// always produce the same signature.
#[must_use]
pub fn sign(message: &[u8], signing_key: &SigningKey) -> Ed25519Signature {
    let signature: Signature = signing_key.sign(message);
    Ed25519Signature(signature.to_bytes())
}

/// Verify an Ed25519 signature against a public key.
///
/// Returns `true` if the signature is valid, `false` otherwise.
/// This function never panics — invalid keys or signatures return `false`.
#[must_use]
pub fn verify(message: &[u8], signature: &Ed25519Signature, public_key: &Ed25519PublicKey) -> bool {
    let Ok(verifying_key) = VerifyingKey::from_bytes(public_key.as_bytes()) else {
        return false;
    };
    let Ok(sig) = Signature::from_slice(signature.as_bytes()) else {
        return false;
    };
    verifying_key.verify_strict(message, &sig).is_ok()
}
