//! Property tests for the hkask-guard pure functions.
//!
//! These replace the deleted stub-based tests that faked the `InferencePort`
//! (the `EchoPort` / `ReasoningEchoPort` doubles in the old `guarded_inference`
//! `mod tests`). No fake inference backends are constructed here: the tests
//! exercise the guard layer's pure synchronous functions —
//! `ContentGuard::scan_input` / `scan_output`, `CanaryToken`, and
//! `Spotlighter` — over arbitrary input generated by proptest, and adjudicate
//! the results through the `hkask-test-harness` Oracle taxonomy (invariant
//! oracles).
//!
//! Coverage focus:
//! - `scan_input` / `scan_output` never panic on arbitrary input and obey
//!   their structural invariants (`passed` ↔ no violations; clean output is
//!   preserved byte-for-byte; a failed scan always sanitizes).
//! - Canary detection redacts the canary from the returned content.
//! - `CanaryToken` uniqueness / format / self-detection.
//! - `Spotlighter` content preservation (Delimit), base64 round-trip (Encode),
//!   and token preservation (Datamark) over arbitrary strings, plus the
//!   instruction/output marker-consistency property across all modes.

use base64::Engine;
use hkask_guard::{
    CanaryToken, ContentGuard, GuardConfig, GuardOutput, SpotlightMode, Spotlighter,
};
use hkask_test_harness::{Oracle, OracleVerdict, arb_json_value, oracle_invariant};
use proptest::prelude::*;
use serde_json::Value as JsonValue;

/// A fresh mandatory guard for each property iteration.
fn guard() -> ContentGuard {
    ContentGuard::mandatory(&GuardConfig::default())
}

/// Assert an oracle returns `Pass`; panic with the verdict otherwise.
fn assert_pass(oracle: &dyn Oracle, input: &JsonValue, output: &JsonValue) {
    match oracle.verify(input, output) {
        OracleVerdict::Pass => {}
        other => panic!("oracle verdict was {other:?}"),
    }
}

// ── scan_input structural invariants ──────────────────────────────────────

proptest! {
    /// `scan_input` never sanitizes its input (it only blocks) and reports
    /// `passed` exactly when there are no violations, for any input string.
    #[test]
    fn scan_input_passed_iff_no_violations_and_never_modified(text in any::<String>()) {
        let result = guard().scan_input(&text);
        let input_json = serde_json::json!({ "text": text });
        let output_json = serde_json::json!({
            "passed": result.passed,
            "violation_count": result.violations.len() as u64,
            "is_modified": result.output.is_modified(),
        });
        let oracle = oracle_invariant(|_input, output| {
            let passed = output.get("passed").and_then(|v| v.as_bool()).unwrap_or(false);
            let count = output.get("violation_count").and_then(|v| v.as_u64()).unwrap_or(1);
            let modified = output.get("is_modified").and_then(|v| v.as_bool()).unwrap_or(true);
            if passed != (count == 0) {
                return Err(format!("passed={passed} but violation_count={count}"));
            }
            if modified {
                return Err(
                    "scan_input must never sanitize input (is_modified=true)".into(),
                );
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// `scan_input` never panics on JSON-shaped text (a common shape for
    /// structured prompts) and obeys the same `passed ↔ no violations` rule.
    #[test]
    fn scan_input_over_arbitrary_json_text(value in arb_json_value()) {
        let text = serde_json::to_string(&value).unwrap_or_default();
        let result = guard().scan_input(&text);
        let input_json = serde_json::json!({ "text": text });
        let output_json = serde_json::json!({
            "passed": result.passed,
            "violation_count": result.violations.len() as u64,
        });
        let oracle = oracle_invariant(|_input, output| {
            let passed = output.get("passed").and_then(|v| v.as_bool()).unwrap_or(false);
            let count = output.get("violation_count").and_then(|v| v.as_u64()).unwrap_or(1);
            if passed != (count == 0) {
                return Err(format!("passed={passed} but violation_count={count}"));
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

// ── scan_output structural invariants ─────────────────────────────────────

proptest! {
    /// `scan_output` over arbitrary strings: clean output is preserved
    /// byte-for-byte; a failed scan is always sanitized (never fails-and-clean).
    /// Also a no-panic regression over multibyte / arbitrary UTF-8 input.
    #[test]
    fn scan_output_clean_preserves_content_failed_sanitizes(text in any::<String>()) {
        let g = guard();
        let result = g.scan_output(&text);
        let content = result.output.content(&text).to_string();
        let input_json = serde_json::json!({ "text": text });
        let output_json = serde_json::json!({
            "passed": result.passed,
            "is_modified": result.output.is_modified(),
            "content": content,
        });
        let oracle = oracle_invariant(|input, output| {
            let text = input.get("text").and_then(|v| v.as_str()).unwrap_or("");
            let passed = output.get("passed").and_then(|v| v.as_bool()).unwrap_or(false);
            let modified = output.get("is_modified").and_then(|v| v.as_bool()).unwrap_or(false);
            let content = output.get("content").and_then(|v| v.as_str()).unwrap_or("");
            if passed != !modified {
                return Err(format!(
                    "passed={passed} but is_modified={modified} (must be opposite)"
                ));
            }
            if passed && content != text {
                return Err("clean output must preserve content byte-for-byte".into());
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// `scan_output` over JSON-shaped text: no panic, same clean/failed invariant.
    #[test]
    fn scan_output_over_arbitrary_json_text(value in arb_json_value()) {
        let text = serde_json::to_string(&value).unwrap_or_default();
        let g = guard();
        let result = g.scan_output(&text);
        let content = result.output.content(&text).to_string();
        let input_json = serde_json::json!({ "text": text });
        let output_json = serde_json::json!({
            "passed": result.passed,
            "is_modified": result.output.is_modified(),
            "content": content,
        });
        let oracle = oracle_invariant(|input, output| {
            let text = input.get("text").and_then(|v| v.as_str()).unwrap_or("");
            let passed = output.get("passed").and_then(|v| v.as_bool()).unwrap_or(false);
            let modified = output.get("is_modified").and_then(|v| v.as_bool()).unwrap_or(false);
            let content = output.get("content").and_then(|v| v.as_str()).unwrap_or("");
            if passed != !modified {
                return Err(format!("passed={passed} but is_modified={modified}"));
            }
            if passed && content != text {
                return Err("clean JSON output must be preserved".into());
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

// ── Canary token: detection + redaction ────────────────────────────────────

proptest! {
    /// When the per-session canary is present in model output, `scan_output`
    /// must fail, redact the canary from the returned content, and emit the
    /// `[REDACTED-CANARY]` marker. Verified for arbitrary surrounding text.
    #[test]
    fn canary_leak_is_redacted_from_output(suffix in any::<String>()) {
        let g = guard();
        let canary = g.canary().as_str().to_string();
        let leaked = format!("system-prompt-leak: {canary} trailing: {suffix}");
        let result = g.scan_output(&leaked);
        let content = result.output.content(&leaked).to_string();
        let input_json = serde_json::json!({ "canary": canary });
        let output_json = serde_json::json!({
            "passed": result.passed,
            "content": content,
        });
        let oracle = oracle_invariant(|input, output| {
            let canary = input.get("canary").and_then(|v| v.as_str()).unwrap_or("");
            let passed = output.get("passed").and_then(|v| v.as_bool()).unwrap_or(true);
            let content = output.get("content").and_then(|v| v.as_str()).unwrap_or("");
            if passed {
                return Err("canary present in output but scan passed".into());
            }
            if content.contains(canary) {
                return Err("sanitized content still contains the canary token".into());
            }
            if !content.contains("[REDACTED-CANARY]") {
                return Err("sanitized content missing [REDACTED-CANARY] marker".into());
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// Generated canary tokens are unique, 64 hex chars, and detect themselves
    /// (and do not cross-detect distinct tokens).
    #[test]
    fn canary_tokens_are_unique_well_formed_and_self_detecting(_ in 0u32..256) {
        let a = CanaryToken::generate();
        let b = CanaryToken::generate();
        let output_json = serde_json::json!({
            "a": a.as_str(),
            "b": b.as_str(),
        });
        let oracle = oracle_invariant(|_input, output| {
            let a = output.get("a").and_then(|v| v.as_str()).unwrap_or("");
            let b = output.get("b").and_then(|v| v.as_str()).unwrap_or("");
            if a == b {
                return Err("canary tokens must be unique per generation".into());
            }
            for (label, tok) in [("a", a), ("b", b)] {
                if tok.len() != 64 {
                    return Err(format!("{label}: canary len {} != 64", tok.len()));
                }
                if !tok.chars().all(|c| c.is_ascii_hexdigit()) {
                    return Err(format!("{label}: canary not hex: {tok}"));
                }
            }
            if !a.contains(a) || !b.contains(b) {
                return Err("canary must detect itself (string contains its own token)".into());
            }
            if a.contains(b) || b.contains(a) {
                return Err("distinct canaries must not contain each other".into());
            }
            Ok(())
        });
        assert_pass(&*oracle, &JsonValue::Null, &output_json);
    }
}

// ── Spotlighter: content-preservation properties ───────────────────────────

proptest! {
    /// Delimit mode preserves the input content verbatim and wraps it in the
    /// `<<HKASK_UNTRUSTED_*>>` / `<<END_HKASK_UNTRUSTED_*>>` markers.
    #[test]
    fn spotlight_delimit_preserves_arbitrary_content(content in any::<String>()) {
        let s = Spotlighter::new(SpotlightMode::Delimit);
        let out = s.spotlight(&content);
        let input_json = serde_json::json!({ "content": content });
        let output_json = serde_json::json!({ "out": out });
        let oracle = oracle_invariant(|input, output| {
            let content = input.get("content").and_then(|v| v.as_str()).unwrap_or("");
            let out = output.get("out").and_then(|v| v.as_str()).unwrap_or("");
            if !out.contains(content) {
                return Err("delimit output lost the input content".into());
            }
            if !out.contains("<<HKASK_UNTRUSTED_") || !out.contains("<<END_HKASK_UNTRUSTED_") {
                return Err("delimit output missing untrusted markers".into());
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// Encode mode embeds a base64 payload that matches an independent
    /// `STANDARD.encode(content)` of the input exactly (round-trip over
    /// arbitrary strings). The spotlight output is structured as
    /// `<<ENCODED_CONTENT_{marker}>>\n{b64}\n<<END_ENCODED_CONTENT_{marker}>>`,
    /// and base64 output contains no newlines, so the middle line is the payload.
    #[test]
    fn spotlight_encode_base64_roundtrips(content in any::<String>()) {
        let expected_b64 = base64::engine::general_purpose::STANDARD.encode(&content);
        let s = Spotlighter::new(SpotlightMode::Encode);
        let out = s.spotlight(&content);
        let actual_b64 = out.lines().nth(1).unwrap_or("").to_string();
        let input_json = serde_json::json!({ "expected": expected_b64 });
        let output_json = serde_json::json!({ "actual": actual_b64 });
        let oracle = oracle_invariant(|input, output| {
            let expected = input.get("expected").and_then(|v| v.as_str()).unwrap_or("");
            let actual = output.get("actual").and_then(|v| v.as_str()).unwrap_or("");
            if expected != actual {
                return Err(format!(
                    "encode round-trip mismatch: expected {expected:?}, got {actual:?}"
                ));
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// Datamark mode preserves every whitespace-delimited token of the input
    /// (the marker is interleaved between tokens, never inside them).
    #[test]
    fn spotlight_datamark_preserves_all_tokens(content in any::<String>()) {
        let s = Spotlighter::new(SpotlightMode::Datamark);
        let out = s.spotlight(&content);
        let input_json = serde_json::json!({ "content": content });
        let output_json = serde_json::json!({ "out": out });
        let oracle = oracle_invariant(|input, output| {
            let content = input.get("content").and_then(|v| v.as_str()).unwrap_or("");
            let out = output.get("out").and_then(|v| v.as_str()).unwrap_or("");
            for token in content.split_whitespace() {
                if !out.contains(token) {
                    return Err(format!("datamark output lost token {token:?}"));
                }
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

proptest! {
    /// `instruction_text` and `spotlight` output must reference the same
    /// per-session marker for every mode — otherwise the LLM is told to look
    /// for a token that never appears, defeating the defense.
    #[test]
    fn spotlight_instruction_and_output_share_marker(content in any::<String>()) {
        let modes = [
            SpotlightMode::Delimit,
            SpotlightMode::Datamark,
            SpotlightMode::Encode,
        ];
        let mut pairs: Vec<JsonValue> = Vec::new();
        for mode in modes {
            let s = Spotlighter::new(mode);
            let spotlit = s.spotlight(&content);
            let instr = s.instruction_text();
            pairs.push(serde_json::json!([spotlit, instr]));
        }
        let input_json = serde_json::json!({ "content": content });
        let output_json = serde_json::json!({ "pairs": pairs });
        let oracle = oracle_invariant(|_input, output| {
            let pairs = output
                .get("pairs")
                .and_then(|v| v.as_array())
                .expect("pairs array");
            for pair in pairs {
                let spotlit = pair.get(0).and_then(|v| v.as_str()).unwrap_or("");
                let instr = pair.get(1).and_then(|v| v.as_str()).unwrap_or("");
                let marker = longest_common_hex_run(spotlit, instr);
                if marker.len() < 32 {
                    return Err(format!(
                        "no shared 32-char hex marker between spotlight output and instruction (got {marker:?})"
                    ));
                }
                if !spotlit.contains(&marker) {
                    return Err("spotlight output does not contain the shared marker".into());
                }
            }
            Ok(())
        });
        assert_pass(&*oracle, &input_json, &output_json);
    }
}

/// Find the longest contiguous run of uppercase-hex characters present in
/// both `a` and `b`. Used to recover the per-session marker shared by
/// `spotlight` output and `instruction_text` without depending on the private
/// `marker` field.
fn longest_common_hex_run(a: &str, b: &str) -> String {
    fn hex_runs(s: &str) -> Vec<String> {
        let mut runs = Vec::new();
        let mut current = String::new();
        for c in s.chars() {
            // Uppercase-hex run: 0-9 or A-F (digits are case-neutral).
            if c.is_ascii_hexdigit() && !c.is_ascii_lowercase() {
                current.push(c);
            } else if !current.is_empty() {
                runs.push(std::mem::take(&mut current));
            }
        }
        if !current.is_empty() {
            runs.push(current);
        }
        runs
    }
    let b_runs = hex_runs(b);
    hex_runs(a)
        .into_iter()
        .filter(|r| r.len() >= 32 && b_runs.iter().any(|br| br == r))
        .max_by_key(|r| r.len())
        .unwrap_or_default()
}

// Keep `GuardOutput` in the import set even if a future edit removes a use.
#[allow(dead_code)]
fn _ensure_guardoutput_linked(_: GuardOutput) {}
