#![forbid(unsafe_code)]
#![warn(clippy::let_underscore_future)]
//! hKask MCP Portfolio — general-purpose transaction-ledger portfolio store.
//!
//! A portfolio is an append-only transaction ledger. Everything else —
//! holdings, returns, validation — is a projection over that ledger at a
//! point in time. This crate is provider-agnostic: it knows nothing about
//! FMP/EODHD stock prices or Kalshi/Polymarket contract feeds. Callers
//! resolve prices externally and feed them to [`returns`].
//!
//! ## Asset types and nested portfolios
//!
//! The ledger is polymorphic over the asset being transacted. [`AssetType`]
//! discriminates stocks, prediction-event contracts, and nested portfolios
//! (a portfolio of CMP indices, each of which is itself a portfolio of
//! contracts). A nested-portfolio holding is a weighted reference to another
//! portfolio by name — the store resolves it recursively on demand.
//!
//! ## Materialized views
//!
//! [`PortfolioStore::snapshot`] computes end-of-day holdings from the ledger.
//! The result is cached in a `daily_holdings` materialized-view table so the
//! portfolio viewer retrieves it without recomputing the full ledger history.
//! [`returns`] computes daily P&L from two snapshots + a price resolver; the
//! per-day result is cached in `daily_returns`. Both views are rebuildable
//! from the ledger (the append-only source of truth) via
//! [`PortfolioStore::rebuild_views`].

mod returns;
mod store;
mod types;

pub use returns::{
    CachedPriceResolver, compute_irr, export_csv, export_json, import_csv, import_json, parse_ymd,
    returns,
};
pub use store::PortfolioStore;
pub use types::{
    AssetType, DailyReturnRow, Holding, HoldingsSnapshot, LedgerFilter, NoPrices, PortfolioError,
    PriceResolver, ReturnsReport, Transaction, TxType,
};

#[allow(unused_imports)]
pub use types::{MAX_IMPORT_REQUEST_BYTES, MAX_IMPORT_TRANSACTION_COUNT, check_request_size};

pub mod server;

// ── Canonical tool-name list ─────────────────────────────────────────────
//
// Generated by `build.rs` from `pub async fn portfolio_*`/`ledger_*`
// signatures in `src/*.rs`. The `tool_names_match_live_router` test
// (server.rs) pins the generated list against the live router.
include!(concat!(env!("OUT_DIR"), "/tool_names.gen.rs"));

pub use server::{map_portfolio_error, run};

#[cfg(test)]
mod tool_name_pin {
    // Pins the generated TOOL_NAMES const against the live rmcp tool
    // surface — a tool added/renamed fails here instead of degrading to
    // "tool not found" at dispatch.
    #[test]
    fn tool_names_match_live_router() {
        let mut live: Vec<String> = crate::server::PortfolioServer::portfolio_router()
            .list_all()
            .iter()
            .map(|tool| tool.name.to_string())
            .collect();
        live.sort();
        let generated: Vec<&str> = crate::TOOL_NAMES.to_vec();
        assert_eq!(
            generated,
            live.iter().map(String::as_str).collect::<Vec<_>>(),
            "TOOL_NAMES (build.rs-generated) must match the live portfolio_router surface"
        );
    }
}

#[cfg(test)]
mod tests;
