//! Public Seam Watcher — "watcher on the wall" for API contract health.
//!
//! Loads the machine-readable public seam inventory at startup (embedded JSON
//! at compile time, file path as development override), registers per-crate
//! coverage as Regulation variety dimensions, detects drift from previous snapshots,
//! and closes the afferent signal path by incrementing variety on each check.
//!
//! Architecture:
//!   embedded JSON (include_str!) → SeamWatcher::load() → VarietyMonitor domains
//!       → check_drift() → increment_variety() → AlgedonicManager.check()
//!       → RuntimeAlert → CyberneticsLoop → Curator → CLI/REPL
//!
//! Non-fatal by design: if no inventory is available (no embedded JSON and
//! no file), seam watching is silently disabled. The system runs normally.
//!
//! Observation model: snapshot comparison, not event streaming. The
//! VarietyTracker's 60s sliding window is bypassed — check_drift() forces
//! an immediate variety check after incrementing.

use crate::runtime::RegulationLedger;
use crate::seam_span::SeamSpan;
use crate::seam_types::SeamInventory;
use hkask_types::event::{CyclePhase, RegulationRecord, RegulationSink, Span, SpanNamespace};
use hkask_types::id::WebID;
use std::path::PathBuf;
use tracing;

// ── Embedded inventory (compile-time, always available in production) ───────

/// Embedded public seam inventory JSON — compiled into the binary.
/// Generated by `scripts/audit/public-seam-inventory.sh` at build time.
/// This ensures seam watching works in deployed (`cargo install`) binaries
/// where `docs/status/` doesn't exist.
const EMBEDDED_INVENTORY: &str = include_str!("../../../docs/status/public-seam-inventory.json");

/// Environment variable for overriding the inventory path at runtime.
/// Set to a file path to use a freshly-generated inventory instead of the
/// compile-time embedded one. Used in development.
const INVENTORY_PATH_ENV: &str = "HKASK_SEAM_INVENTORY_PATH";

/// Expected variety per seam domain.
///
/// Seam watching observes a small number of distinct drift states per check
/// cycle (coverage up/down/stable, new/removed crate) — not hundreds of
/// individual items. Setting expected variety to the item count (e.g., 212)
/// would create a perpetual `deficit ≈ item_count` because variety grows
/// by 1 per cycle, not by the count of covered items.
const SEAM_EXPECTED_VARIETY: u64 = 10;

// ── Seam Drift ───────────────────────────────────────────────────────────────

/// Per-crate coverage delta since last snapshot.
///
/// Positive `delta_pct` = coverage improved (more items got REQ tests).
/// Negative `delta_pct` = coverage degraded (items added without tests,
/// or tests removed).
#[derive(Debug, Clone)]
pub struct SeamDrift {
    pub crate_name: String,
    pub previous_coverage_pct: f64,
    pub current_coverage_pct: f64,
    /// Positive = improvement, negative = degradation
    pub delta_pct: f64,
    /// Change in total public item count (positive = items added)
    pub items_added: i64,
    /// Change in covered item count (positive = more tests)
    pub items_covered_delta: i64,
}

// ── Seam Summary ─────────────────────────────────────────────────────────────

/// Workspace-wide seam coverage summary.
///
/// Consolidates `inventory()`, `overall_coverage()`, and `crate_coverage()`
/// into one struct to keep the public API surface ≤7 items (deep module discipline).
#[derive(Debug, Clone)]
pub struct SeamSummary {
    /// Total public items across all crates
    pub total_items: u64,
    /// Total covered items
    pub covered_items: u64,
    /// Total uncovered items
    pub uncovered_items: u64,
    /// Overall coverage percentage
    pub coverage_pct: f64,
    /// Number of crates analyzed
    pub crate_count: usize,
    /// Number of REQ-tagged tests
    pub req_tests: u64,
}

// ── Seam Watcher ────────────────────────────────────────────────────────────

/// Watches the public seam — loads inventory, tracks coverage, emits Regulation spans.
///
/// The watcher is initialized during
/// bootstrap Phase 7 (Regulation Active) and runs for the lifetime of the daemon.
///
/// # Public API (≤7 items — deep module discipline)
///
/// 1. `SeamDrift` — per-crate coverage delta
/// 2. `SeamSummary` — workspace-wide coverage summary
/// 3. `SeamWatcher` — core watcher struct
/// 4. `load()` — initialize from embedded JSON or file
/// 5. `register_domains()` — register per-crate variety domains in Regulation
/// 6. `check_drift()` — compare against previous snapshot, increment variety, emit spans
/// 7. `refresh()` — reload inventory from disk
pub struct SeamWatcher {
    /// Current inventory snapshot
    inventory: SeamInventory,
    /// Previous snapshot for drift detection (None on first load)
    previous: Option<SeamInventory>,
    /// Path to the JSON inventory file (only used when env var is set)
    inventory_path: Option<PathBuf>,
}

impl SeamWatcher {
    /// Load inventory — tries file path first (if `HKASK_SEAM_INVENTORY_PATH`
    /// is set), falls back to compile-time embedded JSON.
    ///
    /// Returns `None` if neither source is available — seam watching is
    /// non-fatal. The system runs normally without it.
    #[must_use]
    pub fn load() -> Option<Self> {
        // 1. Try file path override (development)
        if let Ok(path) = std::env::var(INVENTORY_PATH_ENV) {
            match std::fs::read_to_string(&path) {
                Ok(contents) => match serde_json::from_str::<SeamInventory>(&contents) {
                    Ok(inv) => {
                        tracing::info!(
                            target: "hkask.architecture.seam",
                            path = %path,
                            crates = %inv.crates.len(),
                            coverage_pct = %inv.totals.coverage_pct,
                            "Seam inventory loaded from file (HKASK_SEAM_INVENTORY_PATH)"
                        );
                        return Some(Self {
                            inventory: inv,
                            previous: None,
                            inventory_path: Some(PathBuf::from(path)),
                        });
                    }
                    Err(e) => {
                        tracing::warn!(
                            target: "hkask.architecture.seam",
                            path = %path,
                            error = %e,
                            "Seam inventory file parse failed, falling back to embedded"
                        );
                    }
                },
                Err(e) => {
                    tracing::warn!(
                        target: "hkask.architecture.seam",
                        path = %path,
                        error = %e,
                        "Seam inventory file not readable, falling back to embedded"
                    );
                }
            }
        }

        // 2. Fall back to compile-time embedded JSON
        if EMBEDDED_INVENTORY.trim().is_empty() {
            tracing::info!(
                target: "hkask.architecture.seam",
                "No embedded seam inventory available — seam watching disabled (non-fatal)"
            );
            return None;
        }

        match serde_json::from_str::<SeamInventory>(EMBEDDED_INVENTORY) {
            Ok(inv) => {
                tracing::info!(
                    target: "hkask.architecture.seam",
                    crates = %inv.crates.len(),
                    total_items = %inv.totals.total_items,
                    coverage_pct = %inv.totals.coverage_pct,
                    "Seam inventory loaded from embedded JSON — watching the public seam"
                );
                Some(Self {
                    inventory: inv,
                    previous: None,
                    inventory_path: None,
                })
            }
            Err(e) => {
                tracing::warn!(
                    target: "hkask.architecture.seam",
                    error = %e,
                    "Embedded seam inventory parse failed — seam watching disabled"
                );
                None
            }
        }
    }

    /// Register all per-crate seam domains in the Regulation runtime's VarietyMonitor.
    ///
    /// Each crate gets a domain `seam:{crate_name}` with expected variety
    /// set to `SEAM_EXPECTED_VARIETY` — a small constant reflecting the limited
    /// number of distinct drift states per check cycle (coverage up/down/stable,
    /// new/removed). The algedonic check supplements, not replaces, the
    /// snapshot-based drift detection in `check_drift`.
    ///
    /// Called once at startup after load.
    pub async fn register_domains(&self, runtime: &RegulationLedger) {
        for (crate_name, coverage) in &self.inventory.crates {
            let domain = format!("seam:{}", crate_name);

            runtime
                .calibrate_threshold(&domain, SEAM_EXPECTED_VARIETY)
                .await;

            tracing::debug!(
                target: "hkask.architecture.seam",
                crate_name = %crate_name,
                domain = %domain,
                expected_variety = SEAM_EXPECTED_VARIETY,
                covered_items = %coverage.covered_items,
                coverage_pct = %coverage.coverage_pct,
                "Registered seam variety domain"
            );
        }

        tracing::info!(
            target: "hkask.architecture.seam",
            domains = %self.inventory.crates.len(),
            "All seam variety domains registered"
        );
    }

    /// Check for drift, increment variety, and emit Regulation spans.
    ///
    /// This is the core "watching" operation — it:
    /// 1. Compares current inventory against previous snapshot
    /// 2. For each crate, calls `increment_variety()` with current covered_items
    ///    (closes the afferent signal path — G1 fix)
    /// 3. Immediately calls `check_variety()` to force an algedonic check
    ///    (bypasses the 60s VarietyTracker window — G4 fix)
    /// 4. Emits Regulation spans for coverage state and drift (merged from former
    ///    `emit_spans()` — G3 surface consolidation)
    ///
    /// On first call (no previous snapshot), stores current as baseline
    /// and returns empty vec — no drift to report.
    ///
    /// After calling this, the current inventory becomes the previous snapshot.
    #[must_use]
    pub async fn check_drift(
        &mut self,
        runtime: &RegulationLedger,
        sink: &dyn RegulationSink,
    ) -> Vec<SeamDrift> {
        let webid = WebID::default();

        // ── Step 1: Increment variety for every crate domain ──
        // This closes the afferent signal path: covered_items count → VarietyMonitor
        // → AlgedonicManager.check() → RuntimeAlert → CyberneticsLoop.
        for (crate_name, coverage) in &self.inventory.crates {
            let domain = format!("seam:{}", crate_name);
            // Increment variety with the current covered_items count.
            // The VarietyTracker counts distinct state keys, so we use the
            // count itself as the key — each check cycle produces one increment
            // with the current value.
            runtime
                .increment_variety(&domain, &coverage.covered_items.to_string())
                .await;

            // Force immediate algedonic check — bypasses the 60s sliding window.
            // Seam watching uses snapshot comparison, not event streaming.
            runtime.check_variety(&domain).await;
        }

        // ── Step 2: Emit coverage spans for each crate ──
        for (crate_name, coverage) in &self.inventory.crates {
            let span = Span::new(
                SpanNamespace::from_observable(&SeamSpan::ArchitectureSeamCoverage)
                    .expect("domain span must be canonical"),
                crate_name.as_str(),
            );
            let event = RegulationRecord::new(
                webid,
                span,
                CyclePhase::Compare,
                serde_json::json!({
                    "crate": crate_name,
                    "total_items": coverage.total_items,
                    "covered_items": coverage.covered_items,
                    "uncovered_items": coverage.uncovered_items,
                    "coverage_pct": coverage.coverage_pct,
                    "req_tests": coverage.req_tests,
                    "high_risk_uncovered": coverage.high_risk_uncovered,
                }),
                0,
            );
            if let Err(e) = sink.persist(&event) {
                tracing::debug!(
                    target: "hkask.architecture.seam",
                    error = %e,
                    crate_name = %crate_name,
                    "Failed to persist seam coverage span"
                );
            }
        }

        // ── Step 3: Compute drift ──
        let previous = match &self.previous {
            Some(p) => p,
            None => {
                self.previous = Some(self.inventory.clone());
                return Vec::new();
            }
        };

        let mut drifts = Vec::new();

        for (crate_name, current) in &self.inventory.crates {
            let prev = match previous.crates.get(crate_name) {
                Some(p) => p,
                None => {
                    drifts.push(SeamDrift {
                        crate_name: crate_name.clone(),
                        previous_coverage_pct: 0.0,
                        current_coverage_pct: current.coverage_pct,
                        delta_pct: current.coverage_pct,
                        items_added: current.total_items as i64,
                        items_covered_delta: current.covered_items as i64,
                    });
                    continue;
                }
            };

            let delta_pct = current.coverage_pct - prev.coverage_pct;
            let items_added = current.total_items as i64 - prev.total_items as i64;
            let items_covered_delta = current.covered_items as i64 - prev.covered_items as i64;

            if delta_pct != 0.0 || items_added != 0 || items_covered_delta != 0 {
                drifts.push(SeamDrift {
                    crate_name: crate_name.clone(),
                    previous_coverage_pct: prev.coverage_pct,
                    current_coverage_pct: current.coverage_pct,
                    delta_pct,
                    items_added,
                    items_covered_delta,
                });
            }
        }

        // Detect removed crates
        for (crate_name, prev) in &previous.crates {
            if !self.inventory.crates.contains_key(crate_name) {
                drifts.push(SeamDrift {
                    crate_name: crate_name.clone(),
                    previous_coverage_pct: prev.coverage_pct,
                    current_coverage_pct: 0.0,
                    delta_pct: -prev.coverage_pct,
                    items_added: -(prev.total_items as i64),
                    items_covered_delta: -(prev.covered_items as i64),
                });
            }
        }

        // ── Step 4: Emit drift spans ──
        for drift in &drifts {
            let span = Span::new(
                SpanNamespace::from_observable(&SeamSpan::ArchitectureSeamDrift)
                    .expect("domain span must be canonical"),
                drift.crate_name.as_str(),
            );
            let severity = if drift.delta_pct < -5.0 {
                "critical"
            } else if drift.delta_pct < 0.0 {
                "warning"
            } else {
                "improvement"
            };
            let event = RegulationRecord::new(
                webid,
                span,
                CyclePhase::Compare,
                serde_json::json!({
                    "crate": drift.crate_name,
                    "previous_coverage_pct": drift.previous_coverage_pct,
                    "current_coverage_pct": drift.current_coverage_pct,
                    "delta_pct": drift.delta_pct,
                    "items_added": drift.items_added,
                    "items_covered_delta": drift.items_covered_delta,
                    "severity": severity,
                }),
                0,
            );
            if let Err(e) = sink.persist(&event) {
                tracing::debug!(
                    target: "hkask.architecture.seam",
                    error = %e,
                    crate_name = %drift.crate_name,
                    "Failed to persist seam drift span"
                );
            }
        }

        // Store current as new baseline
        self.previous = Some(self.inventory.clone());

        if !drifts.is_empty() {
            tracing::info!(
                target: "reg.architecture.seam.drift",
                drift_count = %drifts.len(),
                "Seam drift detected"
            );
        }

        drifts
    }

    /// Refresh the inventory from disk (e.g., after a code update regenerates the JSON).
    ///
    /// Only works when a file path was set via `HKASK_SEAM_INVENTORY_PATH`.
    /// In production (embedded JSON only), this is a no-op — the embedded
    /// inventory is fixed at compile time.
    ///
    /// Moves current → previous, loads new from disk. Returns true if
    /// successful and the inventory changed.
    pub fn refresh(&mut self) -> bool {
        let path = match &self.inventory_path {
            Some(p) => p.clone(),
            None => {
                tracing::debug!(
                    target: "hkask.architecture.seam",
                    "Refresh skipped — no file path (using embedded inventory)"
                );
                return false;
            }
        };

        let contents = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!(
                    target: "hkask.architecture.seam",
                    path = %path.display(),
                    error = %e,
                    "Seam inventory refresh failed — file not readable"
                );
                return false;
            }
        };

        let new_inventory: SeamInventory = match serde_json::from_str(&contents) {
            Ok(inv) => inv,
            Err(e) => {
                tracing::warn!(
                    target: "hkask.architecture.seam",
                    path = %path.display(),
                    error = %e,
                    "Seam inventory refresh failed — JSON parse error"
                );
                return false;
            }
        };

        let changed = new_inventory.totals.total_items != self.inventory.totals.total_items
            || new_inventory.totals.covered_items != self.inventory.totals.covered_items
            || (new_inventory.totals.coverage_pct - self.inventory.totals.coverage_pct).abs()
                > 0.01;

        self.previous = Some(std::mem::replace(&mut self.inventory, new_inventory));

        if changed {
            tracing::info!(
                target: "hkask.architecture.seam",
                total_items = %self.inventory.totals.total_items,
                coverage_pct = %self.inventory.totals.coverage_pct,
                "Seam inventory refreshed — changes detected"
            );
        } else {
            tracing::debug!(
                target: "hkask.architecture.seam",
                "Seam inventory refreshed — no changes"
            );
        }

        true
    }

    /// Workspace-wide coverage summary.
    ///
    /// Consolidates inventory, coverage, and crate counts into one struct.
    #[must_use]
    pub fn summary(&self) -> SeamSummary {
        SeamSummary {
            total_items: self.inventory.totals.total_items,
            covered_items: self.inventory.totals.covered_items,
            uncovered_items: self.inventory.totals.uncovered_items,
            coverage_pct: self.inventory.totals.coverage_pct,
            crate_count: self.inventory.crates.len(),
            req_tests: self.inventory.totals.req_tests,
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::seam_types::SeamCoverage;
    use std::collections::HashMap;

    fn make_test_inventory(crates: Vec<(&str, u64, u64, u64)>) -> SeamInventory {
        let mut crate_map = HashMap::new();
        let mut total_items = 0u64;
        let mut total_covered = 0u64;
        let mut total_uncovered = 0u64;

        for (name, total, covered, high_risk) in &crates {
            let uncovered = total - covered;
            let pct = if *total > 0 {
                (*covered as f64 / *total as f64) * 100.0
            } else {
                0.0
            };
            crate_map.insert(
                name.to_string(),
                SeamCoverage {
                    crate_name: name.to_string(),
                    total_items: *total,
                    covered_items: *covered,
                    uncovered_items: uncovered,
                    coverage_pct: pct,
                    req_tests: *covered,
                    high_risk_uncovered: *high_risk,
                },
            );
            total_items += total;
            total_covered += covered;
            total_uncovered += uncovered;
        }

        let overall_pct = if total_items > 0 {
            (total_covered as f64 / total_items as f64) * 100.0
        } else {
            0.0
        };

        SeamInventory {
            generated: "2026-01-01T00:00:00Z".into(),
            totals: SeamCoverage {
                crate_name: "workspace".into(),
                total_items,
                covered_items: total_covered,
                uncovered_items: total_uncovered,
                coverage_pct: overall_pct,
                req_tests: total_covered,
                high_risk_uncovered: 0,
            },
            crates: crate_map,
        }
    }

    #[test]
    fn check_drift_detects_coverage_drop() {
        let inv1 = make_test_inventory(vec![("test-crate", 100, 50, 10)]);
        let inv2 = make_test_inventory(vec![("test-crate", 100, 45, 15)]);

        let mut watcher = SeamWatcher {
            inventory: inv2,
            previous: Some(inv1),
            inventory_path: None,
        };

        // Use a standalone runtime for the test — check_drift needs RegulationLedger
        let rt = tokio::runtime::Runtime::new().unwrap();
        let drifts = rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            // Register domain first so expected_variety is set
            watcher.register_domains(&ledger).await;
            // Now check drift — this increments variety and triggers algedonic check
            watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await
        });

        assert_eq!(drifts.len(), 1);
        assert_eq!(drifts[0].crate_name, "test-crate");
        assert!(
            drifts[0].delta_pct < 0.0,
            "Coverage drop must have negative delta"
        );
        assert_eq!(drifts[0].items_covered_delta, -5);
    }

    #[test]
    fn check_drift_detects_coverage_improvement() {
        let inv1 = make_test_inventory(vec![("test-crate", 100, 40, 20)]);
        let inv2 = make_test_inventory(vec![("test-crate", 100, 55, 10)]);

        let mut watcher = SeamWatcher {
            inventory: inv2,
            previous: Some(inv1),
            inventory_path: None,
        };

        let rt = tokio::runtime::Runtime::new().unwrap();
        let drifts = rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            watcher.register_domains(&ledger).await;
            watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await
        });

        assert_eq!(drifts.len(), 1);
        assert_eq!(drifts[0].crate_name, "test-crate");
        assert!(
            drifts[0].delta_pct > 0.0,
            "Coverage improvement must have positive delta"
        );
        assert_eq!(drifts[0].items_covered_delta, 15);
    }

    #[test]
    fn check_drift_returns_empty_when_no_change() {
        let inv = make_test_inventory(vec![("test-crate", 100, 50, 10)]);

        let mut watcher = SeamWatcher {
            inventory: inv.clone(),
            previous: Some(inv),
            inventory_path: None,
        };

        let rt = tokio::runtime::Runtime::new().unwrap();
        let drifts = rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            watcher.register_domains(&ledger).await;
            watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await
        });

        assert!(drifts.is_empty(), "No drift when inventories are identical");
    }

    #[test]
    fn check_drift_first_call_returns_empty() {
        let inv = make_test_inventory(vec![("test-crate", 100, 50, 10)]);

        let mut watcher = SeamWatcher {
            inventory: inv,
            previous: None,
            inventory_path: None,
        };

        let rt = tokio::runtime::Runtime::new().unwrap();
        let drifts = rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            watcher.register_domains(&ledger).await;
            watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await
        });

        assert!(
            drifts.is_empty(),
            "First check with no previous must return empty"
        );
        assert!(
            watcher.previous.is_some(),
            "First check must store baseline"
        );
    }

    #[test]
    fn check_drift_detects_new_crate() {
        let inv1 = make_test_inventory(vec![("crate-a", 100, 50, 10)]);
        let inv2 = make_test_inventory(vec![("crate-a", 100, 50, 10), ("crate-b", 50, 25, 5)]);

        let mut watcher = SeamWatcher {
            inventory: inv2,
            previous: Some(inv1),
            inventory_path: None,
        };

        let rt = tokio::runtime::Runtime::new().unwrap();
        let drifts = rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            watcher.register_domains(&ledger).await;
            watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await
        });

        let new_crate_drift: Vec<_> = drifts
            .iter()
            .filter(|d| d.crate_name == "crate-b")
            .collect();
        assert_eq!(new_crate_drift.len(), 1, "New crate must be reported");
        assert_eq!(new_crate_drift[0].previous_coverage_pct, 0.0);
        assert!(new_crate_drift[0].delta_pct > 0.0);
    }

    #[test]
    fn check_drift_detects_removed_crate() {
        let inv1 = make_test_inventory(vec![("crate-a", 100, 50, 10), ("crate-b", 50, 25, 5)]);
        let inv2 = make_test_inventory(vec![("crate-a", 100, 50, 10)]);

        let mut watcher = SeamWatcher {
            inventory: inv2,
            previous: Some(inv1),
            inventory_path: None,
        };

        let rt = tokio::runtime::Runtime::new().unwrap();
        let drifts = rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            watcher.register_domains(&ledger).await;
            watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await
        });

        let removed: Vec<_> = drifts
            .iter()
            .filter(|d| d.crate_name == "crate-b")
            .collect();
        assert_eq!(removed.len(), 1, "Removed crate must be reported");
        assert_eq!(removed[0].current_coverage_pct, 0.0);
        assert!(removed[0].delta_pct < 0.0);
    }

    //
    // When neither embedded JSON nor file path is available, load() returns None.
    // In test environment, EMBEDDED_INVENTORY will be the real inventory from
    // the repo, so this test verifies the fallback behavior by temporarily
    // clearing the env var (which would otherwise point to a file).
    #[test]
    fn load_returns_some_with_embedded_inventory() {
        // In the repo, EMBEDDED_INVENTORY is the real inventory JSON.
        // Verify it loads successfully. Item/crate counts depend on
        // the inventory being generated; test passes even if empty.
        let result = SeamWatcher::load();
        assert!(
            result.is_some(),
            "Embedded inventory must load in repo environment"
        );
        let watcher = result.unwrap();
        let summary = watcher.summary();
        // If inventory was generated, verify it has content.
        // If empty (inventory not yet generated), the load still succeeded.
        if summary.total_items > 0 {
            assert!(
                summary.crate_count > 0,
                "Embedded inventory must have crates when items > 0"
            );
        }
    }

    #[test]
    fn summary_returns_workspace_wide_totals() {
        let inv = make_test_inventory(vec![("crate-a", 100, 50, 10), ("crate-b", 50, 25, 5)]);

        let watcher = SeamWatcher {
            inventory: inv,
            previous: None,
            inventory_path: None,
        };

        let summary = watcher.summary();
        assert_eq!(summary.total_items, 150);
        assert_eq!(summary.covered_items, 75);
        assert_eq!(summary.uncovered_items, 75);
        assert_eq!(summary.crate_count, 2);
    }

    //
    // G1 fix: verify that check_drift() calls increment_variety() for each
    // crate domain, closing the afferent signal path.
    #[test]
    fn check_drift_increments_variety_for_afferent_signal() {
        let inv = make_test_inventory(vec![("test-crate", 100, 50, 10)]);

        let mut watcher = SeamWatcher {
            inventory: inv,
            previous: None,
            inventory_path: None,
        };

        let rt = tokio::runtime::Runtime::new().unwrap();
        rt.block_on(async {
            let ledger = RegulationLedger::with_threshold(100);
            watcher.register_domains(&ledger).await;

            // Before check_drift, variety for seam domain should be 0
            let before = ledger.variety_for_domain("seam:test-crate").await;
            assert_eq!(before, 0, "Variety should be 0 before first check");

            // After check_drift, variety should be >0 (incremented)
            let _drifts = watcher
                .check_drift(&ledger, &crate::runtime::NoopEventSink)
                .await;
            let after = ledger.variety_for_domain("seam:test-crate").await;
            assert!(
                after > 0,
                "Variety must be incremented after check_drift — afferent signal closed"
            );
        });
    }

    // ── Proptest: SeamInventory deserialization never panics ──────

    proptest::proptest! {
        #[test]
        fn seam_inventory_deserialize_never_panics(s in ".*") {
            let _ = serde_json::from_str::<crate::seam_types::SeamInventory>(&s);
        }

        #[test]
        fn seam_coverage_fields_are_non_negative(
            total in 0u64..1000u64,
            covered in 0u64..1000u64,
            uncovered in 0u64..1000u64,
            pct in 0.0f64..100.0f64,
            tests in 0u64..100u64,
        ) {
            let cov = crate::seam_types::SeamCoverage {
                crate_name: "test".into(),
                total_items: total,
                covered_items: covered,
                uncovered_items: uncovered,
                coverage_pct: pct,
                req_tests: tests,
                high_risk_uncovered: 0,
            };
            // Verify the JSON round-trips
            let json = serde_json::to_string(&cov).unwrap();
            let parsed: crate::seam_types::SeamCoverage = serde_json::from_str(&json).unwrap();
            assert_eq!(parsed.crate_name, cov.crate_name);
            assert_eq!(parsed.total_items, cov.total_items);
        }
    }
}
