//! Seam coverage and inventory types.
//!
//! Extracted from hkask-types/src/reg.rs during Regulation refactoring.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Loaded from the machine-readable JSON inventory at startup.
/// Tracked as variety dimensions by the public seam watcher.
///
/// Field names match the JSON output from `scripts/audit/public-seam-inventory.sh`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeamCoverage {
    /// Crate name — "workspace" for the totals aggregate.
    #[serde(default = "default_crate_name")]
    pub crate_name: String,
    pub total_items: u64,
    #[serde(rename = "covered", alias = "covered_items")]
    pub covered_items: u64,
    #[serde(rename = "uncovered", alias = "uncovered_items")]
    pub uncovered_items: u64,
    pub coverage_pct: f64,
    pub req_tests: u64,
    /// High-risk uncovered items — per-crate only, not present in totals.
    #[serde(default)]
    pub high_risk_uncovered: u64,
}

fn default_crate_name() -> String {
    "workspace".into()
}

/// Full public seam inventory, loaded from JSON at startup.
///
/// Generated by `scripts/audit/public-seam-inventory.sh` alongside
/// the human-readable markdown. This is the machine-readable form
/// that Regulation ingests for observability.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeamInventory {
    /// ISO 8601 generation timestamp
    #[serde(default)]
    pub generated: String,
    /// Workspace-wide aggregate
    pub totals: SeamCoverage,
    /// Per-crate coverage data, keyed by crate name
    pub crates: HashMap<String, SeamCoverage>,
}
