//! Build script — generates `tool_names.gen.rs` from `#[tool]` fn signatures.
//!
//! The experimentation tool surface has no shared prefix (the six designed tool
//! names come from repair plan §P8.4), so the pattern enumerates them
//! explicitly. Mirrors `hkask-mcp-spreadsheet/build.rs`; the
//! `tool_names_match_live_router` test in `hkask_mcp_experimentation.rs` pins the
//! generated list against the live `experimentation_router().list_all()` surface.

#[path = "../../crates/hkask-mcp-server/build_support/tool_names.rs"]
mod tool_names;

use std::collections::BTreeSet;
use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is set by cargo for build scripts");
    let src_dir = Path::new(&manifest_dir).join("src");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo for build scripts");
    let out_path = Path::new(&out_dir).join("tool_names.gen.rs");

    // The six designed tool names (§P8.4) — no common prefix, enumerated.
    let pattern = regex::Regex::new(
        r"pub async fn (experiment_propose|variant_register|fitness_record|selection_record|lineage_read|population_query)\s*\(",
    )
    .expect("valid regex");

    let mut names: BTreeSet<String> = BTreeSet::new();
    for source in tool_names::rust_sources(&src_dir, false) {
        for caps in pattern.captures_iter(&source) {
            names.insert(caps[1].to_string());
        }
    }

    let entries = tool_names::entries(&names);
    let generated = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // Scans `src/*.rs` for the six designed experimentation tool signatures.\n\
         pub const TOOL_NAMES: &[&str] = &[\n{entries}];\n"
    );

    tool_names::write_if_changed(&out_path, &generated, &src_dir);
}
